### ISSUE TITLE
Network Magic should be configurable

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#1006]
There are two places where network magic is set to `0` in `consensus`:
https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-consensus/src/Ouroboros/Consensus/Node.hs#L306
https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-consensus/src/Ouroboros/Consensus/Node.hs#L317

It should be configurable by the caller (e.g. `cardano-node`). If there is a mismatch, the network layer will terminate the connection right after the connection started.  It's meant to distinguish testnet vs mainnet (or any other -net).

**Comment by erikd** [comment]
> If there is a mismatch, the network layer will terminate the connection right after the connection started.

And provide a `logError` level log message.

**Comment by mrBliss** [comment]
> There are two places where network magic is set to `0` in `consensus`:
> https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-consensus/src/Ouroboros/Consensus/Node.hs#L306
> https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-consensus/src/Ouroboros/Consensus/Node.hs#L317

Hint: in the future, use *permalinks* when referring to lines of code, because when the files inevitably change, the lines move around. (In this case, it's easy to relocate the lines.)

**Comment by mrBliss** [comment]
Addressed by #1121.
