### ISSUE TITLE
Extract NTP client from `cardano-sl`

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#1007]

**Comment by MarcFontaine** [comment]
The NTP client should move from the `cardano-sl` repo to the new cabal-package within the `ouroboros-network` repo.
The NTP client is reused by the wallet-backend.

Minimal required changes (to make the package compile):
* Remove the `cardano-sl` style tracing.

Possible changes:
* Add new contra-tracers.
* Remove support for JSON configuration files/ move to new configuration-framework.
* Remove Universe-Prelude.

**Comment by dcoutts** [comment]
> Possible changes:
> * Add new contra-tracers.
> * Remove support for JSON configuration files/ move to new configuration-framework.
> * Remove Universe-Prelude.

I would say yes to all of these. But for the second, I'd say that since the NTP check is just a subcomponent it should simply accept its config as an input, and providing that input is up to the wallet (which will ultimately get it from its config system).

**Comment by MarcFontaine** [comment]
Todo: Make the API explict and remove the `TVar` from the API.
Replace `withNtpClient :: Tracer IO NtpTrace -> NtpClientSettings -> IO (TVar NtpStatus)`
with `withNtpClient :: Tracer IO NtpTrace -> NtpClientSettings -> IO Client`
where
```
data Client = Client {
   queryNTP :: IO NtpStatus
  ,triggerUpdate :: IO ()
}
```
From just looking at the existing API it is not obvious that the `triggerUpdate` feature even exists.

**Comment by MarcFontaine** [comment]
TODO: Do not open sockets with out closing them.
Only open sockets in a bracket.

**Comment by MarcFontaine** [comment]
TODO: Remove the use of  `These` (which effectively means rewriting everything).

**Comment by coot** [comment]
What about:
```
data NtpAPI = NtpAPI
  { ntpQuery          :: IO NtpStatus
  , ntpForceCheck :: IO NtpStatus
  }
```
The frist one would be non-blocking (just reading the the `TVar`), while the second would be a blocking call (with `30s` timeout).  Do I remember correctly that `NtpStatus` contains a failure as well?

**Comment by MarcFontaine** [comment]
Yes, I only just noticed that in the current implementation the user of the Ntp library can read and write to the TVar. I have no ideal how the write-direction is actually used or how the intended usecase it.

**Comment by coot** [comment]
One writes one of the `NtpStatus`-es to do the forcful ntp check.

**Comment by MarcFontaine** [comment]
TODO: Also don't forget to keep the tests from `cardano-sl`

**Comment by MarcFontaine** [comment]
Relevant PRs:
#1166
#1184
#1193
#1224
The NTP library from the cardano-sl repo has been moved to ouroboros-network.
Possible further refactorings are a new issue.
