### ISSUE TITLE
Craft `cardano-client` library

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#1013]
* export block, header, tx types from `ouroboros-consensus`
* export `NodeToClient`
* specialise all the codecs for the current version of consensus
* export common `tx-submission` client (which is common for `wallet`, `explorer`), and export null tx submission client for explorer
* prefix modules with `Cardano.Client` (?)

It should export everything that is required by `cardano-explorer` and `cardano-wallet` (in `cardano-node`), and hide the dependency on `ouroboros-network` and `ouroboros-consensus`.

**Comment by mrBliss** [comment]
@coot Is somebody working on this?

@erikd is this necessary for 1.0.0 or 1.1.0?

**Comment by coot** [comment]
@mrBliss not yet; I don't think this is necessary, but it's nice to have.

**Comment by erikd** [comment]
The time this was really needed was back in July when I started work on the explorer.

The explorer now uses the excessively complex `network` APIs and can continue using them (as long as people from the `network` team update the explorer when the `network` APIs break) until this new API is ready.

**Comment by coot** [comment]
@erikd I am aware that it's still needed, we didn't had time to start working on it. There will be substantial changes in the future, though I am not sure we'll have time to finish `cardano-client` before they will land. The wallet team will also appreciate a simpler interface.

**Comment by edsko** [comment]
I am removing the `consensus` label from this ticket. Once the networking layer has a clear API, we can use that as a basis for an API for consensus (though `consensus` already provides a reasonably concise API through `run`).

**Comment by dcoutts** [comment]
This is very useful to simplify clients, but it is not release critical.

**Comment by coot** [comment]
This is subsumed by the `cardano-cli` library in [cardano-node](https://github.com/input-output-hk/cardano-node) repository.
