### ISSUE TITLE
Non-deterministic test failure in "pipe sync demo"

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#105]
Travis failed an unrelated PR, and I can reproduce this on master:

```
tests -p 'pipe sync demo' --quickcheck-tests 10000
ouroboros-network
  Pipe
    pipe sync demo: FAIL
      Exception: ExceptionInLinkedThread ThreadId 39562 consumer end of input
      CallStack (from HasCallStack):
        error, called at src/Ouroboros/Network/Pipe.hs:82:50 in ouroboros-network-0.1.0.0-inplace:Ouroboros.Network.Pipe

1 out of 1 tests failed (197.14s)
```

The failure is non-deterministic and rare (yay :frowning_face:), but quite reliably reproducible with a high enough number of tests. 

It turns out that tasty does not give a seed in the case of an async failure. I experimented with some infrastructure to change that:

```haskell
```data TestFailedException = TestFailedException SomeException
  deriving (Show)

instance Exception TestFailedException where
  displayException (TestFailedException e) = displayException e

catchTestExceptions :: IO a -> IO a
catchTestExceptions act = catch act (throwIO . TestFailedException)

ioProperty' :: Testable prop => IO prop -> Property
ioProperty' = ioProperty . catchTestExceptions
```

and that did give me a seed, but sadly the non-determinism seems to come from the test itself, not anything QC generated, because with a given seed it was still not reproducible. 

Have not added the above code; not sure if it's worth adding somewhere or not.

**Comment by avieth** [comment]
To make a duplex from a pipe, this is used:

```
pipeDuplex
  :: Handle -- ^ Read
  -> Handle -- ^ Write
  -> Duplex IO IO CBOR.Encoding BS.ByteString
pipeDuplex hndRead hndWrite = uniformDuplex send recv
  where
    send = \encoding -> do
      BS.hPutBuilder hndWrite (CBOR.toBuilder encoding)
      hFlush hndWrite
    recv = do
      chunk <- BS.hGetSome hndRead LBS.smallChunkSize
      -- chunk will be null only if EOF (confirm?)
      pure $ if BS.null chunk then Nothing else Just chunk
```

So the receive side closes up at the first `BS.null` chunk delivered. Maybe this is wrong?

**Comment by avieth** [comment]
I've changed it to always give `Just chunk`, so that the `pipeDuplex` receive side _never_ closes. The 10000 quickcheck iterations would always show the bug for me, but with this change it hasn't come up.

**Comment by avieth** [comment]
#108

**Comment by avieth** [comment]
Seems to be fixed

**Comment by coot** [comment]
Closing, this hasn't accurded for almost a year now.
