### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by erikd** [input-output-hk/ouroboros-network#1085]
If I have the `cardano-explorer` connected to a local `cardano-node` and the `cardano-node` is killed, I get the following exception bubbling up to the explorer code and killing the program:
```
cardano-explorer-node-: writev: resource vanished (Broken pipe)
```

Yes, this is the explorer dying, but the exception is from the `ouroboros-network` code which should be catching that exception and handling it internally.

**Comment by coot** [comment]
Subscription manager for client application was implemented, the explorer is already using it, thus we can close this issue.
