### ISSUE TITLE
Endless stream of info events when chain is fully synced

### ISSUE THREAD

**Issue by erikd** [input-output-hk/ouroboros-network#1086]
The cardano-node displays some rather sub optimal behavior when the chain is fully synced.
basically it prints out an stream of messages:
```
[iohk.cardano.node.CoreId 0.ChainSyncBlockServer:Info:377] [2019-10-01 01:21:36.37 UTC] {"kind":"ChainSyncServerEvent"}
[iohk.cardano.node.CoreId 0.ChainSyncBlockServer:Info:377] [2019-10-01 01:21:36.38 UTC] {"kind":"ChainSyncServerEvent"}
[iohk.cardano.node.CoreId 0.ChainSyncBlockServer:Info:377] [2019-10-01 01:21:36.44 UTC] {"kind":"ChainSyncServerEvent"}
[iohk.cardano.node.CoreId 0.ChainSyncBlockServer:Info:377] [2019-10-01 01:21:36.47 UTC] {"kind":"ChainSyncServerEvent"}
[iohk.cardano.node.CoreId 0.ChainSyncBlockServer:Info:377] [2019-10-01 01:21:36.51 UTC] {"kind":"ChainSyncServerEvent"}
[iohk.cardano.node.CoreId 0.ChainSyncBlockServer:Info:377] [2019-10-01 01:21:36.52 UTC] {"kind":"ChainSyncServerEvent"}
```
as you can see, this message occurs multiple times every second.

This suggests the presence of a polling loop rather than event handling that waits until an event occurs.

**Comment by erikd** [comment]
Turns out these messages are only logged when something (eg the explorer) is connected to via the client-to-node protocol

**Comment by mrBliss** [comment]
As of https://github.com/input-output-hk/ouroboros-network/commit/f6e40e72f5c579490c90d274a524f3c89d110056#diff-82cfafafedae58e391f700d7deffe53aL133, the `TraceChainSyncServerIdle` is no longer traced, which I suspect is the one you're seeing.

I have created https://github.com/input-output-hk/cardano-node/issues/233 to get a more useful message than simply `ChainSyncServerEvent`.
