### ISSUE TITLE
Use Byron adapter to download blocks to new storage mechanism

### ISSUE THREAD

**Issue by avieth** [input-output-hk/ouroboros-network#109]
# Context

There is a new block storage layer. We'd like to populate it with some blocks.

# Decision

Let's download some blocks from existing *nets like mainnet, and put them into the new block storage layer!

# Acceptance criteria

1. We can download blocks from existing *nets like mainnet and put them into the new block storage layer.

# PR

None as of yet

# Consequences

We will be able to download blocks from existing *nets like mainnet, and put them into the new block storage layer.

**Comment by dcoutts** [comment]
This is a step towards a old->new protocol proxy. This first goal is just downloading and storing blocks.

For this step we can get away with just using the immutable store, given that in practice with Ouroboros classic we don't get forks. This first impl will just downloading blocks and put them straight into an immutable store. It can just panic and stop if we ever get a fork.

Follow ups to this task:
* The consensus team are also working on the "volatile" store too, which we could start to use once it's ready.
* Serving up the chain sync protocol with the immutable store as the backing, plus some derivative of the `ChainProducerState`.

Initial design ideas:
Make use of the existing work on the byron adapter that uses the diffusion layer within the `cardano-sl` repo to download blocks. One would have to supply all of the cardano-sl configuration, which allows the byron adapter to run, and that will execute a kind of monadic fold over all of the blocks it receives. So one would need to define such a fold which puts the blocks into this new store.

See also PR #90
