### ISSUE TITLE
Add a namespace for all the code.

### ISSUE THREAD

**Issue by erikd** [input-output-hk/ouroboros-network#11]
At some point this code is going to be integrated with other parts of new code base that exists in other repositories. At that point, this code will *need* to be name spaced. Since this will need to be name spaced at some point I would suggest doing it sooner rather than later.

All code in the `src` directory should be prefixed with either `Ouroboros`, `Cardano.Ouroboros` or something similar. Similarly, test modules in the `test` directory should be name spaced with `Test.X` where `X` is whatever is chosen for the name space for code in the `src` directory.

**Comment by adinapoli-iohk** [comment]
This has been done a while ago and I think should be enough to consider this ticket closed. @erikd , feel free to reopen if you disagree 😉
