### ISSUE TITLE
Properly handle MsgNoBlocks

### ISSUE THREAD

**Issue by nfrisby** [input-output-hk/ouroboros-network#1116]
A QuickCheck property found a bug. The original failure is https://hydra.iohk.io/build/1202792/nixlog/1, but it's not specific to that PR.

The repro involves a somewhat intricate test configuration. There is a linear topology `c1 <-> c0 <-> c2`. c2 joins in slot 35. The recent slots prior to 35 have either had no leaders or been lead by both c0 and c1. So at the onset of slot 35, c0 and c1 have competing chains. When c2 joins in slot 35, it starts fetching the blocks on c0's chain -- it's not connect to c1. However, c1 is also the sole leader of slot 35. Once c0 learns of c1's new block, it switches it chain. But this switch interferes with c2's fetching.

In particular, c2 sends a fetch request for `L -> M -> N0 -> O0 -> P0`. But before receiving that request, c0 switches from `L -> M -> N0 -> ...` to `L -> M -> N1 -> ...`. As a result, c0 fails to open the `L ... P0` iterator and so responds to c2 with merely `MsgNoBlocks`.

This causes the failure because, as of commit 1d748262, the BlockFetch client essentially ignores `MsgNoBlocks`. It therefore mistakenly still records that blocks `L` through `P0` are part of some in-flight request, which prevents it from ever actually fetching `L` and `M`, even though they are still on the chains of c0 (and c1). This prevents c2 from ever reaching consensus with c0 and c1.

Edit: This build failure also involved `MsgNoBlocks`, so we think it is related: https://hydra.iohk.io/build/1230823/nixlog/1

**Comment by nfrisby** [comment]
There is a related FIXME and TODO.

https://github.com/input-output-hk/ouroboros-network/blob/1d748262c26a36d97e83d72746f81b2b1f130460/ouroboros-network/src/Ouroboros/Network/BlockFetch/Client.hs#L200-L204

  * The FIXME is concerned about the opposite phenomenon as this bug: requesting extensions of a refused range more than once, where this bug fails the tests because the client _doesn't re-request_ a prefix of the refused range.

  * The TODO is related to this bug. What it refers to as "stats" somewhat surprisingly includes the set of points that record which blocks are assumed to be part of some inflight request.

**Comment by mrBliss** [comment]
Nice detective work :+1:. The protocol testing work you're doing is incredibly valuable!

**Comment by coot** [comment]
@dcoutts are we confident to close this issue now, or do we need to do some more testing?
