### ISSUE TITLE
Add pread to HasFS

### ISSUE THREAD

**Issue by kderme** [input-output-hk/ouroboros-network#1140]
At the moment the VolatileDB does not allow concurrent readers, since they are serialized on the MVar of the Internal State. Without this protection and after https://github.com/input-output-hk/ouroboros-network/issues/767, two readers could read from the same handle, which creates a race condition on the file offset. To make this thread safe, the `pread` unix sys-call should be used.

@mrBliss proposed the name `hGetSomeAt` which seems good to me.

Windows seem to provide similar functionality based on https://stackoverflow.com/questions/766477/are-there-equivalents-to-pread-on-different-platforms (I haven't tried yet).

This functionality shouldn't be needed in the ImmutableDB, since there are not concurrent readers of the same handle.

**Comment by mrBliss** [comment]
> This functionality shouldn't be needed in the ImmutableDB, since there are not concurrent readers of the same handle.

It's not necessary, but I would use it in the ImmutableDB too, as it saves us one system call.

**Comment by kderme** [comment]
In order to take full advantage of this design and make reads fully parallel, we may want to use some read locks in the fs layer. At the moment all syscalls are serialized from `MVar` (see `HandleOS`), but a different kind of lock (`Control.Concurrent.ReadWriteLock`?), which allows many parallel pread could be used.

Even without this, we get some benefit in terms of parallelism, however this will make it "more parallel".

**Comment by mrBliss** [comment]
> In order to take full advantage of this design and make reads fully parallel, we may want to use some read locks in the fs layer. At the moment all syscalls are serialized from `MVar` (see `HandleOS`), but a different kind of lock (`Control.Concurrent.ReadWriteLock`?), which allows many parallel pread could be used.
> 
> Even without this, we get some benefit in terms of parallelism, however this will make it "more parallel".

The `StrictMVar` that Edsko introduced supports this already: https://github.com/input-output-hk/ouroboros-network/blob/d3e71facd53da4a2c72e4947f551ddeac45fba41/ouroboros-consensus/src/Ouroboros/Consensus/Util/MonadSTM/StrictMVar.hs#L128

**Comment by kderme** [comment]
In the Windows implementation, there is another unfortunate issue with versions. `OVERLAPPED` was supported on a newer version, which katip blocks. https://github.com/haskell/win32/commit/760338e7d289a21281f5a5f62f385f3a3808354f#diff-a99994770dbe04188c1176136aef3d32
I think it's possible to rewrtite `data OVERLAPPED' = ...` in our codebase (like we did with seek) and then cast `Ptr  OVERLAPPED' ` to a `Ptr ()`.
However, I see some work is done towards supporting newer Win32 version, which is a better solution https://github.com/input-output-hk/iohk-monitoring-framework/issues/437

**Comment by mrBliss** [comment]
Done in #1164
