### ISSUE TITLE
Handle clock skew when producing a new block

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#1150]
When the node tries to produce a new block:
https://github.com/input-output-hk/ouroboros-network/blob/5bf6c1a3ca15f40dac50913d9168916ebeb62232/ouroboros-consensus/src/Ouroboros/Consensus/NodeKernel.hs#L346
It throws an `error` when the current chain's tip is a block with a slot that is in the future. However, this can happen in practice, as we allow for some [clock skew](https://github.com/input-output-hk/ouroboros-network/blob/5bf6c1a3ca15f40dac50913d9168916ebeb62232/ouroboros-consensus/src/Ouroboros/Consensus/NodeKernel.hs#L131).

We should handle this gracefully. We can ignore the block that is in the future so that *we* can produce our block in this slot, the slot of which we are the leader. Or, we could forfeit our leadership of the slot, but I think this is not a good idea, as it would open the door for attacks.

What should we do if it is still too far in the future, even while taking the clock skew into account? This should be impossible because the ChainSync client will reject headers that are too far in the future (taking the same clock skew into account). But what if we start a node with a wrong clock such that our initial chain loaded from disk is already too far in the future? See #759 and #1143.

**Comment by edsko** [comment]
The problem here is not that we should handle this case: we should never adopt blocks that are from the future (chain sync client might _store_ them, but the chain DB should not _adopt_ them). This should be fixed in the chain DB, not here.

**Comment by mrBliss** [comment]
Superseded by #1287.
