### ISSUE TITLE
Avoid use of `Tip Point`

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#1155]
In various places in the consensus layer we use a type from `consensus`

```haskell
data Tip r = Tip !r | TipGen
  deriving (Show, Eq, Generic, NoUnexpectedThunks)
```

instantiated at `Point`, from `network`

```haskell
newtype Point block = Point
    { getPoint :: WithOrigin (Point.Block SlotNo (HeaderHash block))
    }
```

Now that `Point` uses `WithOrigin`, however, that is no longer reasonable, and we should just use `Point` directly.

**Comment by mrBliss** [comment]
While we're at it, we should introduce a shorter name for `Point.Block SlotNo (HeaderHash block)`, e.g., `BlockPoint`, and use this to enforce that something cannot be genesis. For example, for some of the iterator bounds (`StreamToInclusive`) and for `getBlock` (we'll no longer need the `NoGenesisBlock` exception).
