### ISSUE TITLE
Wrap codec exceptions with additional context

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#1158]
These kind of errors are difficult to decypher:
```
chairman: DeserialiseFailure 4 "expected word"
```

It would be good to log protocol id, state singleton (which would give us which message we expect), peer id could also be useufl.

Related issue #778

**Comment by karknu** [comment]
The additional context is already provided by Mux, it logs all miniprotocols that fails due to exception with involved peers, specific miniprotocol and if it was the initiator or responder side.
