### ISSUE TITLE
Do we have more complicated network protocol pattern?

### ISSUE THREAD

**Issue by yihuang** [input-output-hk/ouroboros-network#1172]
I think ``typed-protocol`` is interesting and more powerful than RPC frameworks, but maybe a little bit overkill here? It seems current mini protocols can be summarised into two patterns:

* ``request -> response``
* ``request -> Stream response``

Which are already covered in existing RPC framework, e.g. protobuf.
Do we have a more complicated scenario to justify a more complicated ``typed-protocol`` framework?

**Comment by erikd** [comment]
Typed protocols also ensures that things like live lock and deadlock never occur because under this framework they become compile time errors, in a way that cannot be done with existing RPC protocols.

See: https://skillsmatter.com/skillscasts/14633-45-minute-talk-by-duncan-coutts

**Comment by yihuang** [comment]
For RPC style protocol, the roles of client/server request/response are well defined, It's like a subset of ``typed-protocol`` with only three basic states: ``Idle|Busy|Done``. So I think that live lock and deadlock don't exist here.
We can define more complicated state machine in ``typed-protocol`` though.

**Comment by coot** [comment]
We have more complex patterns than request / response (or stream of responses). The devil is always in the details ;)  In chain sync protocol and transaction submission protocol we have blocking / non-blocking responses. In the chain sync protocol there there are these path through the state machine states: `StIdle -> StIntersect -> StIdle` and `StIdle -> StNext StCanAwait -> StIdle`  or  `StIlde -> StNext -> StNext StCanAwait -> StNext StMustAwait -> StIdle`.  The blocking `MsgAwaitReply` does not shift agency, so it does not fit the request / response pattern. Our initial, non typed, version of chain sync had a subtle bug which is not possible to do with `typed-protocols`.

**Comment by yihuang** [comment]
That makes sense, thanks for the detailed explanation, closing now.
