### ISSUE TITLE
Do hash checks when reading blocks

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#1177]
Although the Chain DB is equipped with sophisticated checking and recovery facilities, this is only triggered during normal chain operation if (1) file I/O throws an exception, or (2) we fail to parse the block. In particular, we do _not_ check hashes, and so bit flips on disk that affect the payload of the block but not its structural content would not be detected. 

Instead we should check hashes whenever we deserialize blocks, so that we can detect such problems. Blocks in the volatile DB have not been checked for validity, but we _have_ checked that the body hash in the header actually matches the body, so if that check fails later, it must point to a disk failure and we should trigger recovery.

This has a number of consequences:

* The hash check should be _fast_. Related: https://github.com/input-output-hk/cardano-ledger/issues/671
* It makes it all the more important to have a binary-only interface to the DB, which could be used by the block fetch server.  https://github.com/input-output-hk/ouroboros-network/issues/1178

**Comment by edsko** [comment]
Moving to 1.1 as it's inessential and we need to cut the release soon.

**Comment by mrBliss** [comment]
Closed by #1299
