### ISSUE TITLE
Increase parallelism for ImmutableDB readers

### ISSUE THREAD

**Issue by kderme** [input-output-hk/ouroboros-network#1187]
We should think if parallelism can improve https://github.com/input-output-hk/ouroboros-network/pull/1165#pullrequestreview-309888177

**Comment by mrBliss** [comment]
Possible approach: change https://github.com/input-output-hk/ouroboros-network/blob/408f3a3fc8be601075ee2bacdb7b7b9ebac9d2c2/ouroboros-consensus/src/Ouroboros/Storage/ImmutableDB/Impl/State.hs#L256
to:
```haskell
open = atomically $ readMVarSTM _dbInternalState
```

The former first tries to obtain the lock and then immediately releases it. It will block while a block is being appended (which calls `modifyOpenState` and takes the `MVar`).

The latter will read a stale version of the `MVar` in case it is locked (by `modifyOpenState`). This means reads will never block and can happen concurrently with writes, which should be fine, as we only append in writes. Still only one write can happen at a time.

The change is simple, but making sure it is 100% safe is not so simple. Sensitive areas: closing the DB, opening iterators & checking their bounds, reading the last block (`CurrentEpochInfo`), stopping/starting the cache GC thread.

**Comment by mrBliss** [comment]
Done in #1907.

> The change is simple, but making sure it is 100% safe is not so simple. Sensitive areas: closing the DB, opening iterators & checking their bounds, reading the last block (`CurrentEpochInfo`), stopping/starting the cache GC thread.

Actually, it is as safe as before. Before, we were obtaining the state by briefly locking it, but then using the state to read from disk *concurrently* with other operations. That hasn't changed, we just don't require locking anymore to obtain it.
