### ISSUE TITLE
Use correct epoch number for tx validation during block production

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#1198]
Proper solution: add epoch number to `mkDelegationEnvironment` and then pass that all the way up so that we pass the right epoch number during block production. During regular validation this block number would be "still unknown".

**Comment by mrBliss** [comment]
We'll need to pass it to `Mempool.withSyncState`

**Comment by edsko** [comment]
Depends on implementing https://github.com/input-output-hk/ouroboros-network/issues/1291 first.

**Comment by edsko** [comment]
Implemented in https://github.com/input-output-hk/ouroboros-network/pull/1295.
