### ISSUE TITLE
Give user the ability to trigger full recovery after an exception

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#1200]
Dependent on #798. If disk corruption is detected or a file-system error is encountered, a fatal exception will be thrown. That exception should shut down the node. The user will manually have to restart it.

For example, when the disk is full, it doesn't make sense to keep restarting the node. Maybe for a server deployment, where the sysadmin is notified of the disk running out of space, but not for a user deployment.

When we shut down the node, we should tell the user what to do, e.g., restart with full recovery.

**Comment by edsko** [comment]
Since this deals with disk corruption, which has very low probability, moving this to 1.1, but leaving it at high priority..

**Comment by oneEdoubleD** [comment]
Quick test to check once this is finished:

1. Clone `cardano-byron-proxy`
2. Run `nix-build -A scripts.mainnnet.proxy`
3. Run `./proxy` in `terminal1`
4. Run the same `./proxy` in `terminal2`

Currently this corrupts the database and requires you to delete the `state-mainnet` folder to re-run. Ideally you could re-run the proxy and it would recover the database.

**Comment by mrBliss** [comment]
> Quick test to check once this is finished:
> 
>     1. Clone `cardano-byron-proxy`
> 
>     2. Run `nix-build -A scripts.mainnnet.proxy`
> 
>     3. Run `./proxy` in `terminal1`
> 
>     4. Run the same `./proxy` in `terminal2`
> 
> 
> Currently this corrupts the database and requires you to delete the `state-mainnet` folder to re-run. Ideally you could re-run the proxy and it would recover the database.

Note that we can't detect all kinds of corruption yet. We can detect truncated blocks but not yet random bitflips (#1253).

**Comment by mrBliss** [comment]
This can be closed when the following PRs are merged:
- [ ] https://github.com/input-output-hk/ouroboros-network/pull/1311
- [ ] https://github.com/input-output-hk/cardano-node/pull/353
- [ ] https://github.com/input-output-hk/cardano-node/pull/365

**Comment by mrBliss** [comment]
Even though https://github.com/input-output-hk/cardano-node/pull/365 is not (yet or ever?) merged, I'm closing this issue (as done), because the main point of the issue was to *have the ability to trigger recovery*, which is available through the `--validate-db` flag. Printing a human-readable warning would be nice, but is not strictly required.
