### ISSUE TITLE
Test with different epoch sizes

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#1203]
We already have the infrastructure (`EpochInfo`) in place to have epochs with varying sizes, but we are currently only testing with fixed epoch sizes.

**Comment by edsko** [comment]
Should probably be done after #1205.

**Comment by edsko** [comment]
As part https://github.com/input-output-hk/ouroboros-network/issues/1754 @mrBliss will test the immutable DB and chain DB with varying _chunk_ sizes. Leaving this ticket open to generalize the _consensus_ tests for varying _epoch_ sizes.

**Comment by edsko** [comment]
Obsoleted by #2078.
