### ISSUE TITLE
Adapt research-approved praos parameters

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#1204]

**Comment by edsko** [comment]
@nc6 Do you know what the status on this is?

**Comment by edsko** [comment]
If people can make actual money on the testnet (due to staking), this _must_ be verified for the testnet release.

**Comment by edsko** [comment]
@dcoutts do we _have_ sign off on these parameters yet?

**Comment by mrBliss** [comment]
@nc6 Can you make a list of parameters that we need? We can then get it verified by @dcoutts and/or the researchers.

**Comment by mrBliss** [comment]
@brunjlar: @dcoutts told us you would have some insights on this? Can you update your model with Neil's latest data?

BTW, in case you're interested in the code: https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-consensus-shelley/src/Ouroboros/Consensus/Shelley/Protocol.hs.

**Comment by mrBliss** [comment]
Final parameters from Lars and Neil:

```
s = 1s
f = 0.05
valancy = 20
pools 150..250
vast majority of stake in pools
waste: 10, 15%
stability: 3k/f, versus 4k/f
```

No more changes needed to consensus.
