### ISSUE TITLE
Throw a proper exception when started before the blockchain start time

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#1218]
See https://github.com/input-output-hk/cardano-node/issues/295 (which should have been an issue created in this repository, i.e. this issue), in particular https://github.com/input-output-hk/cardano-node/issues/295#issuecomment-553280148.

As the `systemStart` of the current blockchain is years in the past, this is not a problem.

However, we should handle it properly by throwing an exception instead of letting an [assertion](https://github.com/input-output-hk/ouroboros-network/blob/master/io-sim-classes/src/Control/Monad/Class/MonadTimer.hs#L190) fail.

**Comment by dcoutts** [comment]
> However, we should handle it properly by throwing an exception instead of letting an assertion fail.

It should actually just wait until the start time, and trace a message to say that's what it is doing.

This is to syncronise startup of new clusters: the start time can be set to a time shortly in the future.

**Comment by edsko** [comment]
This won't be an issue unless we start a brand new blockchain. Removing milestone.

**Comment by edsko** [comment]
@dcoutts properly supporting it is much less relevant; we won't need that until we start a fresh blockchain; that's #1219.

**Comment by edsko** [comment]
We will provide node operators with a config file containing the correct start time so this isn't a high priority. Moving to 1.1.

**Comment by dcoutts** [comment]
I think at this stage, unless #1219 turns out to be much harder, it'd be more efficient to go straight to that. It'll be useful for our benchmarking team, and for scripts used by CI and QA. This comes up more frequently now that we have to have the start time be recent (within K).
