### ISSUE TITLE
Remove transactions that cause invalid blocks to be created

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#1225]
If there's an inconsistency between the validation we use for the transactions in the mempool and the validation we use for the block we forged containing the transactions from the mempool, we end up making no progress and we get stuck. The mempool won't remove this transactions from the mempool, as they are valid and not in the current chain, but we cannot adopt the block as it is deemed invalid.

Note that #622 will eventually fix this.

Another idea: after adding a newly forged block to the ChainDB, check whether its point ends up in the set of invalid points. This can have false negatives: another chain was selected so our block was not validated yet. If the block point occurs in the invalid points set, we log it since it clearly is a bug and we purge all transactions in the invalid from the mempool.

**Comment by njd42** [comment]
this is a good idea. It will be the case (eventually) - even when the code is "perfect" where environmental factors will damage internal state (http://dance.csc.ncsu.edu/papers/ic2e2015.pdf captures such). Ensuring that systemic progress will be made in this eventually will be important.
