### ISSUE TITLE
ChainSync client "special case" ledger view is sometimes incorrect and/or unnecessary

### ISSUE THREAD

**Issue by nfrisby** [input-output-hk/ouroboros-network#1257]
## Context

  * The ChainSync (CS) client validates headers. The validation function requires a view of the ledger. This view should be contemporaneous with the header being validated; hence the `anachronisticProtocolLedgerView` functions.

  * In the `RealPBFT` protocol, we're using the Byron blocks. The chain's ledger therefore maintains a set of scheduled delegations. The ledger view necessary for validation is just the header's contemporaneous delegation map, which is the result of those delegations previously-scheduled to activate as of the new header's slot.

  * Delegations activate `2k` slots after the slot of the block that includes the delegation certificate as a transaction. Therefore, the anachronistic view cannot look farther than `2k` slots ahead of the local node's current ledger, since headers that far ahead could possibly rely on delegations that haven't yet been scheduled in the local node's current chain. (The `2k` count is derived from the chain density assumption that every span of `2k` slots includes at least `k` blocks.)

  * The CS client uses `anachronisticProtocolLedgerView` to obtain that delegation map from the client node's current ledger. Sometimes that will fail, due to limits on the range of the supported anachrony (eg `<= blockSlot headOfCurrentChain + 2k`). The CS client includes a special case in order to progress even when the anachronistic view is unavailable:

https://github.com/input-output-hk/ouroboros-network/blob/abee34c28b8a7dba6e5a3a82271fae403df22cc0/ouroboros-consensus/src/Ouroboros/Consensus/ChainSyncClient.hs#L617-L622

https://github.com/input-output-hk/ouroboros-network/blob/abee34c28b8a7dba6e5a3a82271fae403df22cc0/ouroboros-consensus/src/Ouroboros/Consensus/ChainSyncClient.hs#L643-L653

## Bug

The bug is two fold. The special case in the CS client is

  1. used even when it's not necessary (we should check for it only if `anachronisticProtocolLedgerView` fails) and
  2. sometimes incorrect: it ignores previously-scheduled delegations that activated between the node's current head block and the one we're validating.

I've observed a failure due to both of these while developing #1202. My prototype was correctly restarting a node with an updated operational key and issuing the necessary delegation certificate, but it was still failing the tests because the other nodes' CS clients were unnecessarily using a stale ledger view that incorrectly ignored the new delegation certificate.

## Suggested Fix

This suggestion is driven purely by my understanding of `RealPBFT`. I have not considered others, like `Praos` etc.

  * Is the special case absolutely necessary?
  * If so, I think it should be implemented as follows:
      * The `anachronisticProtocolLedgerView` should always yield the contemporaneous ledger view for the future, based on the previously-scheduled delegations.
      * If the header is farther than `2k` slots ahead, a flag should be set. Normally, this flag will prevent the CS client from validating the header, even though the client now has a delegation map contemporaneous with the header.
      * The "special case" should be implemented by simply ignoring that flag and still using the calculated futuristic ledger view if the header fits directly onto the local node's current chain.

**Comment by nfrisby** [comment]
PR #1260 removes the special case, but to do so also disables late joins in the test code. I'll open a PR that re-enables late joins, but only those that do not require the special case. I think that PR will let us close this ticket. (We could alternatively close it now and open another ticket for the test re-enabling, to reduce the Bug label count.)

**Comment by nfrisby** [comment]
#1197 seems similar, but focusing on block production instead of ChainSync.

**Comment by edsko** [comment]
@nfrisby can we close this ticket?

**Comment by nfrisby** [comment]
Closing. #1283 tracks the remaining work.
