### ISSUE TITLE
Revise ledger DB disk snapshot taking policy

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#1264]
We should probably

~1. Take a snapshot when the node shuts down~ *Moved to #1387.*
2. Adjust it so that when doing bulk sync, we take snapshots faster than once every 12 hours.

It seems that currently we also take a snapshot after replying? Not sure where/how.

**Comment by mrBliss** [comment]
I split off the most important, high priority part of this ticket to #1387.

**Comment by mrBliss** [comment]
Even when an error occurs will a snapshot be taken on shut down. Only in case of a hard shut down while we're bulk syncing is this going to be an issue.

**Comment by edsko** [comment]
Note that this ticket is about on-disk snapshots; see #1026 for the in-memory snapshots.

**Comment by edsko** [comment]
Re-prioritizing as high priority due to https://github.com/input-output-hk/ouroboros-network/issues/1454#issuecomment-573751671 .
