### ISSUE TITLE
Disallow opening the same ChainDB multiple times

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#1266]
Use a lockfile, as suggested [here](https://github.com/input-output-hk/ouroboros-network/blob/fc164b5a3cbcd239a5803b5d3925205d29837a7c/ouroboros-consensus/src/Ouroboros/Storage/ImmutableDB/Impl.hs#L64).

**Comment by mrBliss** [comment]
This looks like a good candidate to use for this: https://hackage.haskell.org/package/lukko

**Comment by kderme** [comment]
Isn't filelock enough for this?
I have done some work here https://github.com/input-output-hk/ouroboros-network/pull/1326

**Comment by mrBliss** [comment]
Addressed in #1326.
