### ISSUE TITLE
Make NodeToNode and NodeToClient api easier use

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#1277]
Switch from using enumeration data types (with existentials) to using normal lists of mini-protocols.

**Comment by dcoutts** [comment]
See #1247

**Comment by coot** [comment]
@duncan I will close this issue as #1247 is already merged, and I will open a follow up for integrating the changes with `ouroboros-network` (removing `ProtocolEnum`, updating handshake protocol, etc).
