### ISSUE TITLE
Predict the max number of clients based on the open file handle limit

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#1278]
Each process has a limited number of file handles it can open. Each client connecting to the node will require a number of additional open file handles. This is a potential DoS attack: if new clients keep connecting the process will eventually run out of file handles. If we're lucky, it's a client-specific thread that fails to open a file handle. In the worst case, it's a central component that fails to open a file handle, e.g., the ChainDB trying to open a new file, which would bring the whole node down.

There will be a bounded number of shared file handles:
* VolatileDB: one for the current file. In the future, we will keep a handle open for each file.
* ImmutableDB: one for the epoch file, one for the primary index, and one for the secondary index.
* ...

We need a number of spare handles for temporary things like reading a config file, writing a ledger snapshot, etc.

We should have a **static upper bound on the number of file handles a client will require**. For example, the BlockFetchServer uses an ImmutableDB iterator which requires at least one file handle at all times.

Based on these bounds we can predict how many clients we will safely be able to serve concurrently without running out of open file handles. We can check the configured file handle limit and if it is too low compared to the required number of clients, we can warn (throw an error?) about this.

We can verify this bound in the property tests using the mock file-system, and maybe the `ResourceRegistry` too.

This will be needed when the network topology is decentralised.

**Comment by edsko** [comment]
Related: https://github.com/input-output-hk/ouroboros-network/pull/1378#issuecomment-569390257

**Comment by mrBliss** [comment]
Closing in favour of #1396 and #1397.
