### ISSUE TITLE
Chain DB: never adopt blocks from the future

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#1287]
Replaces #1150. Because the ChainSync client allows for some clock skew, blocks from the future might be added to the ChainDB. The current implementation simply treats them as any other block, even though the spec tells us to ignore them: https://github.com/input-output-hk/ouroboros-network/blob/c23a5bdd212d4b550036cbf21836566bda2aa054/ouroboros-consensus/docs/ChainDB.md#L286

However, there is a problem with the spec: if the clock of our node is running behind, all blocks we receive might be from the future. Since we ignore all of them for chain selection, we will adopt no blocks at all. Forging a new block doesn't help, since it will fit onto the current tip of our chain, which does not include any of those blocks.

Note that receiving a single or a few blocks from the future is not a big deal, because when we receive a new block extending the fork they're in that is not from the future, we can still adopt that fork, including the blocks that were from the future at the time we received them.

What we should do instead is the following. Ignore the newly arrived block from the future, but run chain selection again using the blocks we already have *that are not from the future*. This makes sure that we eventually adopt blocks from the future when they no longer are from the future, *even when we only receive blocks from the future*. The spec and implementation must be updated accordingly.

**Comment by edsko** [comment]
> even though the spec tells us to ignore them

:roll_eyes: 

:trollface:

**Comment by mrBliss** [comment]
Addressed in #1288.
