### ISSUE TITLE
Test that we use the right slot number for transaction validation throughout

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#1297]
The edge case we want to test: a transaction is valid when added to the mempool, but has become invalid by the time that the node gets around to producing the block.

(If the mempool would use the wrong slot number to validate it, it wouldn't notice this, and actually produce an invalid block.)

The easiest way to test this is to add a TTL to a transaction.

Note that this is *not* a Mempool test, but a protocol test, as it requires  the Mempool, block forging, and a ticking blockchain time.

This would exercise the chain ticking stuff introduced in #1295.

**Comment by mrBliss** [comment]
There is nothing in Byron (transactions) that depends on the current time/slot. But there is in Shelley, so moving to Shelley.

**Comment by edsko** [comment]
@nfrisby Moving this to the next sprint, though feel free to close it whenever you feel we've sufficiently tested this.
