### ISSUE TITLE
Introduce golden tests for serialization

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#1302]
Consensus should have golden tests for its binary serialization functions so that we'd notice if by mistake we change the serialization format: the roundtrip tests would still pass, but we'd break existing deployments.

**Comment by mrBliss** [comment]
To be clear: this is not about the serialisation of Byron blocks, which is defined in `cardano-ledger` (which has golden tests already), but about the serialisation of types we define in consensus.
