### ISSUE TITLE
Check block validity when copying from VolatileDB to ImmutableDB

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#1304]
When we compute the CRC of a block written to the ImmutableDB, we should first check whether the block has not already been corrupted while in the VolatileDB, i.e., we should whether the body matches its hash in the header. If we don't do this check, we'd compute the CRC of the corrupted block and wouldn't notice the corruption of the block when reading it again from the ImmutableDB.

**Comment by mrBliss** [comment]
What if we detect that a block in the VolatileDB has gotten corrupted? We can't simply delete or overwrite that block, that's not supported by the VolatileDB (and that's a deliberate decision). We can only try to garbage collect all the block by triggering a garbage collection for its slot number, but that's not guaranteed to delete the block from disk, as newer blocks can reside in the same file.

Even if we manage to delete the invalid block, what should we do next? How do we let the BlockFetch client download it again? I think this will quickly become very complex and will break many of the assumptions upon which we based our design.

I think for now the simplest solution is to **wipe the entire VolatileDB and shut down the node**. When restarting the node, we'll restart from a valid immutable chain, and redownload the missing blocks, including the corrupted block. Let's call this plan A.

We can improve this by *adding validation support to the VolatileDB*: check the integrity of each block. This will not be a checksum check like in the ImmutableDB (as we'd need to store the checksums on disk too), but the more expensive "block matches header" check + "check the signature of the header". This validation can detect incorrect blocks in files, but what should be done when encountering such an invalid block? The simplest thing would be **delete the file in question** (plan B). This is still better than wiping the entire VolatileDB, as we leave the other files in place. One step better: **truncate the file in question to the offset before the first invalid block** (plan C). If that means truncating to 0, delete the file.

If we want to save even more blocks from truncation, we could think about the following: if a file contains at least one invalid block that is followed by at least one valid block, create a new file (with a special filename), copy all valid blocks from the corrupted file to the new file. At the end, delete the corrupted file and rename the new file to the file that was corrupted (plan D). This approach avoids in-place mutation and gives us atomicity.

**Comment by kderme** [comment]
Should I consider adding an api call `deleteBlock`, which implements some of the plans above? Maybe with an additional argument to choose a specific plan B,C,D?

**Comment by mrBliss** [comment]
> Should I consider adding an api call `deleteBlock`, which implements some of the plans above? Maybe with an additional argument to choose a specific plan B,C,D?

No, this should *definitely not* be an API call. This validation will happen on start-up, so before the VolatileDB is available.

The plan is something we choose to implement, not an option to a function. For example, why would we ever choose `B` if we could do `C`? I am talking about different plans because they differ in implementation complexity. The idea is that we can initially implement plan C and when we have more time and think it is worth it, we can implement D. (I only included A and B because I wrote down my whole thought process).

**Comment by mrBliss** [comment]
Plan:

1. When copying blocks from the VolatileDB to the ImmutableDB, first check their validity. That should be done after this line: https://github.com/input-output-hk/ouroboros-network/blob/a43961c1133b9e1b0826f3d4d1bc5b93819037d6/ouroboros-consensus/src/Ouroboros/Storage/ChainDB/Impl/Background.hs#L149 Use this function: https://github.com/input-output-hk/ouroboros-network/blob/a43961c1133b9e1b0826f3d4d1bc5b93819037d6/ouroboros-consensus/src/Ouroboros/Storage/ChainDB/Impl/Args.hs#L93 When that check fails, an exception should be thrown, e.g., `VolDbCorruptBlock`, to be added to this type: https://github.com/input-output-hk/ouroboros-network/blob/a43961c1133b9e1b0826f3d4d1bc5b93819037d6/ouroboros-consensus/src/Ouroboros/Storage/ChainDB/API.hs#L667 This will close the ChainDB and the node.
2. During the validation of the VolatileDB, the integrity of each block should be checked. The ImmutableDB already does such a check.
   * Pass the integrity checking function like the ImmDB does: https://github.com/input-output-hk/ouroboros-network/blob/a43961c1133b9e1b0826f3d4d1bc5b93819037d6/ouroboros-consensus/src/Ouroboros/Storage/ChainDB/Impl/ImmDB.hs#L154
   * When parsing a file containing blocks, that function should be called on each block. As soon as a block doesn't pass this check, that file should be truncated (plan C). Appropriate tracing needs to be done so the user can be warned about this.
   * This integrity checking is expensive, so it should be optional. #1551 will take care of enabling it when necessary.

**Comment by kderme** [comment]
For the VolatileDB this validation happens only when opening the DB, so when we parse the blocks, or in other cases also?

**Comment by mrBliss** [comment]
> For the VolatileDB this validation happens only when opening the DB, so when we parse the blocks, or in other cases also?

Yes, only when opening and reopening the VolatileDB.
