### ISSUE TITLE
Support starting and restarting of miniprotcols.

### ISSUE THREAD

**Issue by karknu** [input-output-hk/ouroboros-network#1318]
Support starting and restarting of individual miniprotocols within a given mux bearer. This is needed to reduce resource consumption for p2p and it will make it possible to pause a chainsync client instead of having it bring down the entire Mux bearer incase the peer is too far behind.

**Comment by karknu** [comment]
This feature is needed for the shelley testnet because without it chainsyc would trigger a disconnect for every peer that is more than `k` blocks behind once #1319 is implemented.

**Comment by coot** [comment]
Done in #1536

**Comment by coot** [comment]
Done #2221
