### ISSUE TITLE
Use duplex sockets over NodeToNode Interface

### ISSUE THREAD

**Issue by karknu** [input-output-hk/ouroboros-network#1319]
Mux bearers are bidirectional by default and we should take advantage of that fact in NodeToNode. This is especially important in p2p scenarios where it is possible that host A can open connections to host B, but not the other way around (due to NATs, Firewalls,...).

**Comment by karknu** [comment]
This feature is needed for the shelley testnet because without it all our nodes would have to be manually configured with the ip address/domain name and port number of every stake pool in the test network.

**Comment by coot** [comment]
This is done in `p2p-master`, we don't need to track it separately from `connection-manager`.
