### ISSUE TITLE
Please add function nullChainSyncWithBlocksPtcl

### ISSUE THREAD

**Issue by erikd** [input-output-hk/ouroboros-network#1334]
When initializing the `OuroborosInitiatorApplication` struct for the tx-submission webapi, I need a null function to provide to respond to `ChainSyncWithBlocksPtcl`. I am currently using this:

```
nullChainSyncWithBlocksPtcl :: Channel IO BSL.ByteString -> IO Void
nullChainSyncWithBlocksPtcl =
  const . forever $ threadDelay (1000 * 1000 * 1000)
```

**Comment by karknu** [comment]
#1318 will solve this.

**Comment by karknu** [comment]
> #1318 will solve this.

So, that is not correct. #1318 will change the way you start applications/miniprotocols, but you'll still need something like nullChainSyncWithBlocksPtcl.

**Comment by coot** [comment]
it's already there, it's called `Ouroboros.Network.NodeToClient.chainSyncClientNull`.

**Comment by coot** [comment]
@erikd we can rename it to `nullChainSyncClient` if you think it sounds better.

**Comment by coot** [comment]
That's assigned in #1333.
