### ISSUE TITLE
Integrate new cardano-ledger annotation infrastructure

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#1336]
The annotation infrastructure in `cardano-ledger` has changed in https://github.com/input-output-hk/cardano-ledger/pull/679. The consensus code needs to be updated accordingly.

This needs to be done so we can bump the dependency on `cardano-ledger`.

**Comment by mrBliss** [comment]
We reverted the annotation changes (https://github.com/input-output-hk/cardano-ledger/pull/691) until they have sorted that out. This means we can bump the dependency on `cardano-ledger` again.

**Comment by edsko** [comment]
Related: #1215. In fact, it's conceivable that closing this ticket will obsolete #1215.

**Comment by mrBliss** [comment]
Our next sprint (S8) is supposed to be focused on technical debt, so moving this issue to that sprint.

**Comment by mrBliss** [comment]
Removing it from the sprint: consensus is not asking for this. The driver for this issue should be the ledger integration team, which track it separately in JIRA.

**Comment by nc6** [comment]
There's now no plan to rejig the annotations in Byron. The corresponding work for Shelley has been done, so let's close this ticket.
