### ISSUE TITLE
Make `cardano-node` slot length derived from genesis

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/ouroboros-network#1344]
@deepfire commented on [Thu Nov 07 2019](https://github.com/input-output-hk/cardano-node/issues/288)

Subtask of #255

Slot length is currently hard-coded in `ourobboros-network` to 20s [1], which is counterproductive for short CI runs, that would benefit from 1s slots.

--
1. https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-consensus/src/Ouroboros/Consensus/Node.hs#L188

---

@Jimbo4350 commented on [Thu Nov 07 2019](https://github.com/input-output-hk/cardano-node/issues/288#issuecomment-551197310)

@deepfire  My branch `jordan/replace-cardano-configuration` has a key in the soon to be config yaml file to set the slot length.

---

@dcoutts commented on [Wed Dec 11 2019](https://github.com/input-output-hk/cardano-node/issues/288#issuecomment-564673985)

The slot length is already specified in the genesis file. It should be taken from there, not hard coded. But it should not be a config file or CLI item. It's critical for consensus that everyone agree on the slot length, so it is right that it comes from the genesis.

**Comment by dcoutts** [comment]
Duplicated https://github.com/input-output-hk/ouroboros-network/issues/1345
