### ISSUE TITLE
Take BFT slot length from genesis file rather than hard coding.

### ISSUE THREAD

**Issue by dcoutts** [input-output-hk/ouroboros-network#1345]
The slot length is currently hard coded to 20s:
https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-consensus/src/Ouroboros/Consensus/Node.hs#L188

But we can take it from the genesis file, since it is specified there. For example in the mainnet genesis:
```
        "slotDuration": "20000",
```
The unit there is milliseconds.

So this should be a simple matter of plumbing. We already take lots of other values from the genesis file. This one just got missed.

**Comment by mrBliss** [comment]
We started working on this a while ago: https://github.com/input-output-hk/ouroboros-network/pull/953. I went on vacation and it was forgotten about. I'll try to revive it.
