### ISSUE TITLE
New protocol version / migration for lazy mux and block sizes

### ISSUE THREAD

**Issue by karknu** [input-output-hk/ouroboros-network#1355]
We need to define a new protocol version to accommodate a couple changes in the network and consensus.

The new version will support one flag `InitiatorOnly`, which indicates that the peer that started the version negotiation is not running the responder side of the miniprotocols. This change may not be able to use the protocol versioning mechanism, needs further review.

The consensus layer also needs to instantiate the chain sync to include the block size (needed to provide that info to block fetch). This might be done by a breaking change, or by using the protocol versioning.

**Comment by edsko** [comment]
Consensus is ready after https://github.com/input-output-hk/ouroboros-network/pull/1632, we just need to enable it.
