### ISSUE TITLE
Refactoring the ntp-client

### ISSUE THREAD

**Issue by MarcFontaine** [input-output-hk/ouroboros-network#1362]
This is the followup on #1007.
The existing cardano-sl ntp-client has gone through many iterations of code changes and changes of the requirements what makes it difficult to understand the existing design.
There are several problems with the error-handling, start up and termination.
The plan for fixing this is to:

* [x] extract a minimal single request ntp-client.
* [x] extend this to multiple request with timeouts.
* [x] add logging and error-handling
* [x] add IPv6.
* [ ] and minimal spoofing protection.

**Comment by MarcFontaine** [comment]
Error handling of socket operations:
In case of an error the existing code open an new socket
(with infinite retries, without delay between the retries and while leaking of open sockets).

We discussed the following changes:
NTP uses UDP and there are no connections anyway.
Reopening a socket makes sense for TCP but not for UDP.
The NTP client should stop and report an error and not retry with a new socket.

**Comment by MarcFontaine** [comment]
Security model of the NTP client:
The NTP client is strictly only used to inform the user of a possible clock skew.
The NPT client is NOT used to set the system clock and the reported times are NOT uses for
the consensus algorithms.
The NTP client allows to queries several NTP servers in parallel and to use
a suitable policy such that a single evil NTP server cannot easily trick the client.

**Comment by MarcFontaine** [comment]
A prototype for the basic control flow with timeouts and support for multiple NTP servers is in
https://github.com/input-output-hk/ouroboros-network/commit/f0d2939e833d37affa43243a1350378d3e051648
This is IPv4 only.
TODO: extent this to IPv6.

This prototype has no spoofing protection:
It uses multiple servers, such that if servers fail to reply it can just work with the replies it gets.
However it cannot detect if multiple incoming replies are indeed valid replies from the servers or
spoofed packets from an adversary.

**Comment by MarcFontaine** [comment]
relevant PR is
https://github.com/input-output-hk/ouroboros-network/pull/1327

**Comment by coot** [comment]
Minimal spoofing protection is achieved by opening a short lived socket on an ephemeral port.
