### ISSUE TITLE
Account for block encoding overhead size when selecting txs to include in a block

### ISSUE THREAD

**Issue by intricate** [input-output-hk/ouroboros-network#1363]
> ... The max block size actually comes from the current ledger protocol params (with the initial value in the genesis).
> 
> The block size refers to the total block size, including the block header and all other encoding overheads.
> 
> I suggest that we approximate this by a per-ledger-instance constant max overhead, so we would end up taking `maxBlockSize - blockEncodingOverheadsSize` worth of txs.

_Originally posted by @dcoutts in https://github.com/input-output-hk/ouroboros-network/pull/1346_

> ... or `let maxBlockBodySize = maxBlockSize - blockEncodingOverheadsSize`

_From @dcoutts on Slack._

**Comment by mrBliss** [comment]
We don't need to be too precise here. High priority, as QA might run into it when benchmarking TPS.
