### ISSUE TITLE
Limit number of open file handles required by imm DB

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#1384]
Right now every client that connects and wants to read blocks from the immutable DB creates a number of open file handles. This means that the max number of files handles of the process might be reached fairly quickly. There are (at least) two possible solutions to this:

* Cache file handles, so that we only have one open per epoch (say), with a particular limit.
* Simply place a limit on how many file handles the imm DB will open, and reject further connections. This is not as unreasonable as it may seem, because only clients that are syncing will read from the Imm DB; clients reading from the chain near its tip (that are already up to date) will read from the vol DB, which _is_ caching file handles (or at least, will soon). Bounding the number of clients that can sync from the server is probably a good idea anyway; see https://github.com/input-output-hk/ouroboros-network/pull/1378#issuecomment-569390257 .

**Comment by mrBliss** [comment]
Current goal is to support 20, marking as low priority.

**Comment by edsko** [comment]
Note that this will become much higher priority once we start scaling up the number of clients, so reclassifying as medium priority instead.

**Comment by edsko** [comment]
Closing this; caching file handles is not quite right (we want predictable resource usage, see #1397) and the limit on the number of clients has a separate ticket (#1391).
