### ISSUE TITLE
Limit the number of accepted connections

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#1391]
At the moment, if a node runs out of file handles or other resources because too many clients have connected to it, it will shut down with an error. Clients will try the next node, which will also run out of resources and shut down, then they'll go to the next node and so on, leading to a cascading failure.

Instead, it should decline the new client so that it can keep on serving the connected clients. The client should wait or try the next server so that the network is unaffected.

To figure out the maximum number of clients, we should figure out a conservative maximum bound on the resources required to serve a client, see #1278.

Related: #1384 https://github.com/input-output-hk/ouroboros-network/pull/1378#issuecomment-569390257

**Comment by coot** [comment]
To account how many resources are available for downstream peers, we need to estimate how many resources are taken by upstream ones. Currently we have a static configuration which decides how many upstream peers we will connect to, with the peer2peer governor this will change but still we should be able to have a policy which governs that (@dcoutts).

**Comment by coot** [comment]
I assigned myself to work on the network level interface.

**Comment by mrBliss** [comment]
@coot This ticket is *only* about accepting a limited number of  accepted clients. We can use a relatively low value for it that is surely safe for now, e.g., 20. **Such a limit must be in place before the release**, otherwise the node will crash when too many clients connect.

Afterwards adding such a limit, we can do more precise accounting for resources, and increase the limit based on this accouting, but that's not what this ticket is about. We have #1396 and #1397 for that.

IMO, the network is the most logical place to have such a limit.

@coot Do you think the network team will be able to add such a limit in this sprint?

**Comment by edsko** [comment]
Blocked on #1473.

**Comment by edsko** [comment]
This is blocked on networking improvements, and the networking team tells me that this won't be done this sprint. Moving to the next.

**Comment by edsko** [comment]
This will be handled network side, so consensus is not involved.

**Comment by dcoutts** [comment]
@coot I suspect giving the timing we will need to implement this for the existing connection manager, and merge the new p2p-governor based connection manager after, targeting the Shelley testnet.

**Comment by coot** [comment]
@dcoutts, ok - I am working now on Windows issues (CI, and finishing the re-factorization of `Win32-network`) and then I'll work on this issue.

**Comment by coot** [comment]
PR #1831
