### ISSUE TITLE
Investigate blocks arriving out of order when syncing from a single node

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#1393]
In the following setup: an empty node syncing from a fully synced node, after a while (300-400k blocks), we start to see blocks arriving out of order, even though we're only syncing from one node. This is not supposed to happen. This manifests itself by having lots of `StoreButDontChange` trace message (tracing might have to be tweaked a little).

This is bad for performance, as when the missing block arrives, all the blocks after it will have to be read from disk and validated.

**Comment by karknu** [comment]
> tracing might have to be tweaked a little.
@mrBliss what kind of tweaking? Just log levels or is there a need to add more tracing code?

**Comment by mrBliss** [comment]
> > tracing might have to be tweaked a little.
> 
> @mrBliss what kind of tweaking? Just log levels or is there a need to add more tracing code?

I think tracing all ChainDB messages (`StoreButDontChange` in particular) suffices.

**Comment by karknu** [comment]
I've been unable to trigger a single instance of `StoreButDontChange`, when syncing mainnet against a byron-proxy. In what setup did you run into this? Can you still reproduce it?

**Comment by mrBliss** [comment]
> I've been unable to trigger a single instance of `StoreButDontChange`, when syncing mainnet against a byron-proxy. In what setup did you run into this? Can you still reproduce it?

Ah, sorry, forgot to mention: I only managed to reproduce this with the (local, I don't know whether that's relevant) server running with `-N1`.

**Comment by karknu** [comment]
Thanks, will try that.

**Comment by karknu** [comment]
I have been unable to reproduce this out of order issue with a single local peer, but I discovered that the standard `mainnet-topology.json`, is setup in a way that makes this scenario very common. `mainnet-topology.json` should be changed from using four separate IP addresses to a single  round robin dns name.

**Comment by karknu** [comment]
I've been unable to reproduce this issue and @mrBliss is no longer able to reproduce it.
