### ISSUE TITLE
Make immutable DB epoch type configurable

### ISSUE THREAD

**Issue by avieth** [input-output-hk/ouroboros-network#141]
In `Ouroboros.Storage.Immutable.DB` there is

```
-- This is just a placeholder as we don't have (yet) a proper 'Epoch' type in
-- this codebase.
type Epoch = Word
```

I suggest we make the index type a parameter of the immutable DB. For `cardano-sl` applications we can set it to be `Word64`, since that's the size of epoch indices there.

**Comment by edsko** [comment]
@mrBliss I don't think we need to be more general actually; let's just set `newtype Epoch = Epoch { epochToWord64 :: Word64 }` or some such. Could you include this in your PR, so we can close this issue?

**Comment by mrBliss** [comment]
@edsko Will do.

**Comment by mrBliss** [comment]
Completed in #341.
