### ISSUE TITLE
Complete Local Query Protocol

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#1412]
This is a prerequisite for #1366 and expands on #1209.

**Comment by i-o-m** [comment]
@coot @dcoutts From Duncan in Slack. This is needed for the Byron Re-write integration with Wallet in the next Sprint S5 "Duncan Coutts  Yes, it's essentially the same if it's targeting Byron. We'd re-target these tickets for Byron, and add one new one for the incremental change needed for Shelley."

**Comment by coot** [comment]
This is done in pr #1522

**Comment by coot** [comment]
@mrBliss I put you as an assignee, since you did the work in #1522 - thanks :)
