### ISSUE TITLE
test-consensus divergence: Two RealPBFT nodes exchange two BlockFetch messages forever

### ISSUE THREAD

**Issue by nfrisby** [input-output-hk/ouroboros-network#1435]
On master, this test case diverges.

```
      let ncn = NumCoreNodes 4 in
      prop_simple_real_pbft_convergence (SecurityParam 5) TestConfig
        { numCoreNodes = ncn
        , numSlots     = NumSlots 58
        , nodeJoinPlan = NodeJoinPlan $ Map.fromList [(CoreNodeId 0,SlotNo 3),(CoreNodeId 1,SlotNo 3),(CoreNodeId 2,SlotNo 5),(CoreNodeId 3,SlotNo 57)]
        , nodeTopology = meshNodeTopology ncn
        , slotLengths  = defaultSlotLengths
        , initSeed     = Seed (11044330969750026700,14522662956180538128,9026549867550077426,3049168255170604478,643621447671665184)
        }
```

I've observed this behavior as early as commit 8e0cab4f (merge PR 1402). I haven't yet checked when this behavior originated.

During slot 57, the two nodes indefinitely exchange two BlockFetch messages, `MsgRequestRange` and `MsgNoBlocks`. In the `io-sim` monad, this locks up the entire test.

```
$ cabal v2-run ouroboros-consensus:test:test-consensus
...
Send CoreId 0 MsgRequestRange ChainRange (At (Block {blockPointSlot = SlotNo {unSlotNo = 49}, blockPointHash = ByronHash {unByronHash = AbstractHash f89fba07311a080c9fafeb6318329373bba188a93acff8b3d6d9a6262df0b521}})) (At (Block {blockPointSlot = SlotNo {unSlotNo = 50}, blockPointHash = ByronHash {unByronHash = AbstractHash 4c35e8707e0588957598620e5e902448c9b947d9fd6ffebe470dbf4a639c07b9}}))
Recv CoreId 3 MsgRequestRange ChainRange (At (Block {blockPointSlot = SlotNo {unSlotNo = 49}, blockPointHash = ByronHash {unByronHash = AbstractHash f89fba07311a080c9fafeb6318329373bba188a93acff8b3d6d9a6262df0b521}})) (At (Block {blockPointSlot = SlotNo {unSlotNo = 50}, blockPointHash = ByronHash {unByronHash = AbstractHash 4c35e8707e0588957598620e5e902448c9b947d9fd6ffebe470dbf4a639c07b9}}))
Send CoreId 3 MsgNoBlocks
Recv CoreId 0 MsgNoBlocks
Send CoreId 0 MsgRequestRange ChainRange (At (Block {blockPointSlot = SlotNo {unSlotNo = 49}, blockPointHash = ByronHash {unByronHash = AbstractHash f89fba07311a080c9fafeb6318329373bba188a93acff8b3d6d9a6262df0b521}})) (At (Block {blockPointSlot = SlotNo {unSlotNo = 50}, blockPointHash = ByronHash {unByronHash = AbstractHash 4c35e8707e0588957598620e5e902448c9b947d9fd6ffebe470dbf4a639c07b9}}))
Recv CoreId 3 MsgRequestRange ChainRange (At (Block {blockPointSlot = SlotNo {unSlotNo = 49}, blockPointHash = ByronHash {unByronHash = AbstractHash f89fba07311a080c9fafeb6318329373bba188a93acff8b3d6d9a6262df0b521}})) (At (Block {blockPointSlot = SlotNo {unSlotNo = 50}, blockPointHash = ByronHash {unByronHash = AbstractHash 4c35e8707e0588957598620e5e902448c9b947d9fd6ffebe470dbf4a639c07b9}}))
Send CoreId 3 MsgNoBlocks
Recv CoreId 0 MsgNoBlocks
... ad infinitum ...
```

This Issue is to debug and fix this divergence. I'm unsure how this would manifest in `IO` as opposed to `io-sim`. Perhaps it's just adding unnecessary load on the network and compute (and log?). But since `io-sim` diverges, this causes the `test-consensus` to diverge, which is inconvenient.

**Comment by nfrisby** [comment]
cc: @mrBliss @edsko @dcoutts

**Comment by dcoutts** [comment]
Probably due to #802

**Comment by nfrisby** [comment]
Hmm. I just noticed that this live lock seems to only happen in the `RealPBFT` tests. So maybe it's EBB-related?

On my PR 1419, I workaround this Issue by using `System.Timeout` to discard those `RealPBFT` tests that timeout. And I consistently see timeouts; for example, it discarded ~60 test cases in order to reach 5000 test cases (4*1250 with `-N4`). But I just ran that same code for 5000 iterations each of BFT, LeaderSchedule, PBFT, and Praos, and they never live locked (recall that I only applied the `timeout` to RealPBFT).

**Comment by mrBliss** [comment]
> Hmm. I just noticed that this live lock seems to only happen in the `RealPBFT` tests. So maybe it's EBB-related?

The first thing in the BlockFetch client that is related to EBBs (and thus slot numbers) that comes to mind that to me is https://github.com/input-output-hk/ouroboros-network/blob/56bc665a604e11aa504cac833ae7f8a6dedb9170/ouroboros-network/src/Ouroboros/Network/BlockFetch/Decision.hs#L593
Does the live lock still happen if you remove the stop condition used in that function?

**Comment by nfrisby** [comment]
@mrBliss The tweak to `filterWithMaxSlotNo` doesn't seem to make a difference :(  This was my delta:

```
[nix-shell:~/iohk]$ git lg -1
* 6cd974b6 - (HEAD -> nfrisby/issue-1435-exploration) WIP test-consensus: focus on the Issue 1145 repro (4 minutes ago) <Nicolas Frisby>

[nix-shell:~/iohk]$ git diff
diff --git a/ouroboros-network/src/Ouroboros/Network/BlockFetch/Decision.hs b/ouroboros-network/src/Ouroboros/Network/BlockFetch/Decision.hs
index 692c35a1..b32614ff 100644
--- a/ouroboros-network/src/Ouroboros/Network/BlockFetch/Decision.hs
+++ b/ouroboros-network/src/Ouroboros/Network/BlockFetch/Decision.hs
@@ -597,7 +597,7 @@ filterWithMaxSlotNo
   -> ChainFragment header
   -> [ChainFragment header]
 filterWithMaxSlotNo p maxSlotNo =
-    ChainFragment.filterWithStop p ((> maxSlotNo) . MaxSlotNo . blockSlot)
+    ChainFragment.filter p `asTypeOf` ChainFragment.filterWithStop p ((> maxSlotNo) . MaxSlotNo . blockSlot)
 
 prioritisePeerChains
   :: forall header peer. HasHeader header

[nix-shell:~/iohk]$ 
```

**Comment by mrBliss** [comment]
> @mrBliss The tweak to `filterWithMaxSlotNo` doesn't seem to make a difference :(

You'll need to do some more debugging then :slightly_smiling_face: 

> +    ChainFragment.filter p `asTypeOf` ChainFragment.filterWithStop p ((> maxSlotNo) . MaxSlotNo . blockSlot)

Hmm, that `asTypeOf` is rather confusing to me. My first reading was: use the first argument as the type of/for the second argument, whose value we're actually going to use. Looking at the implementation (`const`), it's actually the opposite :confused:

**Comment by nfrisby** [comment]
> You'll need to do some more debugging then 🙂

Onward!

> Hmm, that `asTypeOf` is rather confusing to me. My first reading was: use the first argument as the type of/for the second argument, whose value we're actually going to use. Looking at the implementation (`const`), it's actually the opposite 😕

That definition is 19 years old :) (Give this link a second to fully load before scrolling, etc) https://github.com/ghc/ghc/commit/4fb94ae5e5d632748fa2e6c35e259eccc5a1a3f4#diff-4255ad26ea25b80cc5d2a001a2e23e1eR536

**Comment by nfrisby** [comment]
I looked into this some more today. At the moment, this particular repro has two features that seem problematic.

First, the BlockFetch server is sending `MsgNoBlocks` because its iterator fails here:

https://github.com/input-output-hk/ouroboros-network/blob/db34b1f6b9a6eff320c1661d9be72ba553fc6fd3/ouroboros-consensus/src/Ouroboros/Storage/ChainDB/Impl/Iterator.hs#L343-L347

In this repro, `predHash = HashT, hashes = [HashU], and tipHash = [HashV]` where the chain does contain blocks ... T, U, V, .... The wrinkle -- of course -- is that U is an EBB and both U and V were forged in slot 50.

Second -- while that may explain why the BlockFetch client is confused (the CS server says: "you can fetch T and U from me", but the same node's BF server then says "I can't give you T and U!") -- it seems wrong that the BF client just repeats the request immediately and indefinitely (which means divergently in `io-sim`).

So, @mrBliss: is this Issue two bugs in one?

**Comment by nfrisby** [comment]
The trace begins with

```
lots of events ...
CoreNodeId 0 CopiedBlockToImmDB (At (Block {blockPointSlot = SlotNo 49, blockPointHash = ByronHash {unByronHash = AbstractHash f89fba07311a080c9fafeb6318329373bba188a93acff8b3d6d9a6262df0b521}}))
CoreNodeId 0 CopiedBlockToImmDB (At (Block {blockPointSlot = SlotNo 50, blockPointHash = ByronHash {unByronHash = AbstractHash 4c35e8707e0588957598620e5e902448c9b947d9fd6ffebe470dbf4a639c07b9}}))
CoreNodeId 0 CopiedBlockToImmDB (At (Block {blockPointSlot = SlotNo 50, blockPointHash = ByronHash {unByronHash = AbstractHash 4b4adeb31cc25bea2514abaeecdc44ee3b6fa14e8c1af3250e3c18ccc3c8126a}}))
... lots of other events, but no more CopiedBlockToImmDB on c0 ...
```

I'll call those blocks and their hashes T, U, V, HashU, HashT, and HashV.

Thus: c0's ImmDB is T > U > V. Note that U is an EBB and U and V are both in slot 50.

We eventually reach this point in the trace. These then repeat for the rest of the run; we think due to Issue 802.


```
CoreNodeId 3 Send CoreId 0 MsgRequestRange ChainRange (At (Block {blockPointSlot = SlotNo 49, blockPointHash = HashT})) (At (Block {blockPointSlot = SlotNo 50, blockPointHash = HashU}))
CoreNodeId 0 TraceUnknownRange (ForkTooOld (StreamFromInclusive (At (Block {blockPointSlot = SlotNo 49, blockPointHash = HashT}))))
CoreNodeId 3 Recv CoreId 0 MsgNoBlocks
CoreNodeId 3 Send CoreId 0 MsgRequestRange ChainRange (At (Block {blockPointSlot = SlotNo 49, blockPointHash = HashT})) (At (Block {blockPointSlot = SlotNo 50, blockPointHash = HashU}))
...
```

The ChainDB bug here is that, though the ImmDB suffix is T > U > V, we fail when trying to stream T and U. EBBs complicate the logic here. Slot 50 is the first slot in the second epoch and has both an EBB (U) and a proper block (V). The tip of the ImmDB is V.

```
    start = lift itGetImmDBTip >>= \case
      GenesisPoint -> findPathInVolDB
      BlockPoint { atSlot = tipSlot, withHash = tipHash } ->
        case atSlot endPoint `compare` tipSlot of
          LT -> streamFromImmDB
          EQ | withHash endPoint == tipHash
             -> streamFromImmDB
             | otherwise
```

We end up here. The following comment from the code is correct. Our repro is not the given example, it's instead "the end point is an EBB and the tip of the ImmutableDB is the regular block after it."

```
		-- The end point /= the tip of the ImmutableDB. Either the
                -- fork is too old, or the end point (or the tip of the
                -- ImmutableDB) is an EBB. For example, the tip of the
                -- ImmutableDB is an EBB and the end point is the regular
                -- block after it.
             -> findPathInVolDB
          GT -> findPathInVolDB
```

This precondition is unsatisfied.

```
    -- | PRECONDITION: the upper bound > the tip of the ImmutableDB
    findPathInVolDB :: HasCallStack
                    => ExceptT (UnknownRange blk) m (DeserialisableIterator m blk)
```

In this particular repro's mechanics, that precondition seems irrelevant; `path` ends up as `VolDB.PartiallyInVolDB HashT [HashU]` since U happens to also be in the VolDB. But if U happened to not be in the VolDB, then I think the query would still unduly fail (via `VolDB.NotInVolDB`).

```
      path <- lift $ atomically $ VolDB.computePathSTM itVolDB from to
      case path of
        VolDB.NotInVolDB        _hash           -> throwError $ ForkTooOld from (prettyCallStack callStack)
        VolDB.PartiallyInVolDB  predHash hashes -> streamFromBoth predHash hashes
        VolDB.CompletelyInVolDB hashes          -> case NE.nonEmpty hashes of
          Just hashes' -> lift $ streamFromVolDB hashes'
          Nothing      -> lift $ emptyIterator
```

Therefore, it seems like we really shouldn't be using `findPathInVolDB` for this query.

Thus: How can `start` differentiate the two cases involving EBBs? It seems like we need to know the hash of the predecessor of the ImmutableDB tip. @mrBliss, thoughts?

**Comment by nfrisby** [comment]
Just to clarify: PR 1475 only fixed the ChainDB aspect of this Issue. But the BlockFetch aspect should fall under Issue 802, so we let PR 1475 close this Issue.

@mrBliss: Would you like to rename this Issue to clarify that?
