### ISSUE TITLE
Node may currently incorrectly reported that a block was not adopted

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#1463]
After we forge and add a block in block production, we check if that block is at the top of our chain. If not, we report the block as not adopted. This is incorrect. It is possible that additional blocks have been adopted _on top_ of our current block. 

Instead `addBlock` in the Chain DB should return the tip of the chain after chain selection (thereby also making it clear that `addBlock` is indeed synchronous), and _that_ is what we should check instead.

**Comment by denisshevchenko** [comment]
@edsko Can it be related to https://jira.iohk.io/browse/CAD-413?

**Comment by edsko** [comment]
No, almost certainly not.
