### ISSUE TITLE
Delay block production while waiting for delegation certificate to take effect

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#1469]
When a node posts a delegation certificate to the chain, and is restarted, it may produce blocks with that new certificate before the certificate takes effect.

**Comment by edsko** [comment]
Removed the `testing` label as this also applies to the real node.

**Comment by mrBliss** [comment]
Fixed in https://github.com/input-output-hk/ouroboros-network/pull/2176
