### ISSUE TITLE
Broken link in readme file

### ISSUE THREAD

**Issue by romainPellerin** [input-output-hk/ouroboros-network#1508]
Link in "See 45min Haskell eXchange 2019 ~~talk~~ by @dcoutts" is broken: https://skillsmatter.com/skillscasts/14633-45-minute-talk-by-duncan-coutts

**Comment by mrBliss** [comment]
> We are happy to announce that Skills Matter is back!
>
> Our first goal is to restore the library of SkillsCast videos in the coming weeks. Following that we will announce our first schedule of returning conferences and series of expert led courses and workshops.

It seems that this will be fixed in the near future. In any case, there's not much we can do about it.

**Comment by mrBliss** [comment]
FYI, the videos are back online, so the link is no longer broken :slightly_smiling_face:
