### ISSUE TITLE
txSize reports the incorrect size

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#1535]
`txSize` for `ByronBlock` includes the encoding overhead for the different `GenTx` constructors:

```haskell
  data GenTx ByronBlock
    = ByronTx             !Utxo.TxId                !(Utxo.ATxAux             ByteString)
    | ByronDlg            !Delegation.CertificateId !(Delegation.ACertificate ByteString)
    | ByronUpdateProposal !Update.UpId              !(Update.AProposal        ByteString)
    | ByronUpdateVote     !Update.VoteId            !(Update.AVote            ByteString)
    deriving (Eq, Generic)
    deriving NoUnexpectedThunks via UseIsNormalForm (GenTx ByronBlock)

  txSize tx =
        1 {- encodeListLen -}
      + 1 {- tag -}
      + (fromIntegral . Strict.length $ mempoolPayloadRecoverBytes tx')
    where
      tx' = toMempoolPayload tx
```
This means that we're over-estimating transaction sizes.

What it should be:
```haskell
  txSize =
     fromIntegral . Strict.length . mempoolPayloadRecoverBytes . toMempoolPayload
```

The `byronBlockEncodingOverhead` might have to be revisited and it might have to take the number of transactions an argument.

Important: we should check that the size we're reporting matches the expectation.

**Comment by dcoutts** [comment]
Yes I think this is correct, it's only the +2 that's wrong here. Otherwise it's counting the raw tx size, which is right.

> The byronBlockEncodingOverhead might have to be revisited and it might have to take the number of transactions an argument.

Probably not, unless we want to make it very precise. The encoding for the block tx list is at most 3 bytes (since there'll never be more than 64k txs in a block).
