### ISSUE TITLE
ImmutableDB is leaking file handles

### ISSUE THREAD

**Issue by nfrisby** [input-output-hk/ouroboros-network#1543]
On master (commit 62d8e669), this test case fails with `ImmutableDB is leaking file handles`.

```
          let ncn5 = NumCoreNodes 5 in
          prop_simple_real_pbft_convergence NoEBBs (SecurityParam 2) TestConfig
            { numCoreNodes = ncn5
            -- Still fails if I increase numSlots.
            , numSlots     = NumSlots 54
            , nodeJoinPlan = NodeJoinPlan $ Map.fromList
              [(CoreNodeId 0,SlotNo {unSlotNo = 0})
              ,(CoreNodeId 1,SlotNo {unSlotNo = 0})
              ,(CoreNodeId 2,SlotNo {unSlotNo = 0})
              ,(CoreNodeId 3,SlotNo {unSlotNo = 53}),(CoreNodeId 4,SlotNo {unSlotNo = 53})
              ]
              -- Passes if I drop either of these restarts.
            , nodeRestarts = NodeRestarts (Map.fromList [(SlotNo {unSlotNo = 50},Map.fromList [(CoreNodeId 0,NodeRestart)]),(SlotNo {unSlotNo = 53},Map.fromList [(CoreNodeId 3,NodeRestart)])])
            , nodeTopology = meshNodeTopology ncn5
              -- Slot length of 19s passes, and 21s also fails; I haven't seen this matter before.
            , slotLengths  = singletonSlotLengths (slotLengthFromSec 20)
            , initSeed     = Seed {getSeed = (15062108706768000853,6202101653126031470,15211681930891010376,1718914402782239589,12639712845887620121)}
            }
```

With some instrumentation, I determined that node c0 leaks one ImmDB file handle, for path @00000.epoch@, read only, offset at 0. It was opened by a `ChainSyncServer` thread.

The test case seems somewhat fragile, since the 'slotLengths' value seems to matter.

**Comment by nfrisby** [comment]
It seems to be fixed by adding 'uninterruptibleMask_' to the 'ResourceRegistry'-based allocation of the iterator in 'Ouroboros.Storage.ChainDB.Impl.ImmDB.registeredStream'. But there are several potential `MVar` and `IO` operations within that bracket; are we sure we want all of them to uninterruptible?

As an alternative, perhaps we could instead add the file handle to a registry ASAP instead of waiting for it to make it into an iterator which then gets added to a registry?

**Comment by nfrisby** [comment]
FYI, @mrBliss I pushed up a branch `mrBliss/fix-1543` that just has a commit on it that makes `test-consensus` only run this repro.

**Comment by mrBliss** [comment]
> FYI, @mrBliss I pushed up a branch `mrBliss/fix-1543` that just has a commit on it that makes `test-consensus` only run this repro.

Thanks for that! (After force-pushing my fix, that commit is now gone.)
