### ISSUE TITLE
Don't use `TraceAddBlockEvent.SwitchedToChain` when it's not a switch but an extension

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#1549]
It's confusing when the logs seem to suggest we're actually _switching_ (rather than just adopting a block).

**Comment by nfrisby** [comment]
As long as there is still some some tracer event recording the extension! :)

**Comment by edsko** [comment]
Oh, for sure. My point was that the logs should not record it as a "switch" when it's merely an extension of the existing chain; that's just confusing. I wasn't arguing it should disappear from the log altogether :)
