### ISSUE TITLE
Handle restarting with validation automatically

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#1551]
Related to #1200 and #1201. When the node is being run by the wallet, it uses error codes to communicate information about the fatal error to the wallet (see #1541). For example, in case a file from the database is missing, the wallet should restart the node with the validation flag enabled.

In a server setting, where the node process is being run by systemd or runit, the node process will automatically be restarted when it terminated. There will be no human reading the error message or checking the error code to enable the validation flag when necessary.

We should be able to automatically validate when necessary.

Plan: add a marker file to the database on a clean shutdown (TODO define "clean"). On startup, if the marker is there, then we don't have to do any additional validation (just the last epoch, as we always do by default). If the marker is missing, we do a full validation.

**Comment by edsko** [comment]
* Create marker on startup
* Delete marker on normal shutdown (as the last thing the Chain DB does)
* If marker present on startup, clean shutdown did not happen, and hence we should validate.

**Comment by mrBliss** [comment]
Comment that will have to be updated/removed:
https://github.com/input-output-hk/ouroboros-network/blob/9784cdccc1d3c774e74ce2f89ff59ba2f48c1378/ouroboros-consensus/src/Ouroboros/Consensus/Node/ErrorPolicy.hs#L53

**Comment by mrBliss** [comment]
>     * Create marker on startup
> 
>     * Delete marker on normal shutdown (as the last thing the Chain DB does)
> 
>     * If marker present on startup, clean shutdown did not happen, and hence we should validate.

Edsko and I discussed two possible interpretations of the marker and found them to be (almost?) isomorphic. However, the approach described in the description has the following advantage: the user can't accidentally delete the marker.

**Comment by edsko** [comment]
Note that this means we only need two exit codes: restart, or "don't bother restarting" (and automated tools can just treat both as "restart").

**Comment by edsko** [comment]
("Don't bother restarting" might still be useful to distinguish some subcases, to give better feedback to Daedalus.)
