### ISSUE TITLE
Check that block numbers are consecutive

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#1571]
Apparently, nowhere in the Byron or Shelley ledger is it verified that blocks have consecutive block numbers.

We do check it in [an assertion `ChainFragment`](https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-network/src/Ouroboros/Network/ChainFragment.hs#L221), but in production, assertions will be disabled.

We should verify this at the earliest opportunity we have, which is `applyChainState` (called for synced headers but also when we apply blocks we produced ourselves, as part of `applyExtLedgerState`). In addition to check whether block numbers are consecutive, we should also check that the first block has the right block number, i.e., `genesisBlockNo`.

It is important that we check this, because we're assuming that block numbers are a reliable proxy for chain length. So if this is not the case, we might prefer a chain that is actually shorter. So both consecutiveness and the right initial block number are important. For example, an attacker might forge a single block with a very large block number, and we would incorrectly prefer it over all other chains.

**Comment by edsko** [comment]
@nc6 , change of plan, no need to do this for each ledger (although the spec should still verify it, I think). I will do this once and for all for _all_ ledgers. You actually discussed doing that when discussing the Byron integration, albeit for hashes, not block numbers; I'm coming round to your point of view now :) PR to follow, unassigning you from this ticket.

**Comment by edsko** [comment]
WIP PR at #1577 .

**Comment by edsko** [comment]
So #1578 cleans up a lot of our `BlockNo` hygiene, but I'd like to fix https://github.com/input-output-hk/cardano-base/issues/78 before fixing this ticket, in order to ensure that we don't have other places with bad `BlockNo` hygiene.
