### ISSUE TITLE
Missing timeouts in connection handshake protocol driver

### ISSUE THREAD

**Issue by dcoutts** [input-output-hk/ouroboros-network#1575]
> `ouroboros-network/src/Ouroboros/Network/Socket.hs` implements lower levels of the network stack, including socket creation and connection primitives in `connectToNode`. When used as a client, it sets the `ReuseAddr` and if applicable, `ReusePort` socket options, calls `Socket.connect`, wraps in `socketAsMuxBearer`, and proceeds to `runPeerWithByteLimit`. The mux bearer acts as a thin wrapper of `Socket.sendAll` and `Socket.recv` calls. Without setting a socket timeout or using poll or select, these may block forever, as the remote side may simply continue to keep a connection alive without sending or receiving data. This will tie up resources on the node.

As reported by Root9B.

**Comment by coot** [comment]
#1395

**Comment by coot** [comment]
Core issues fixed in #1752; Expanding documentation will be done in another issues.
