### ISSUE TITLE
Changes in ntp-client.cabal file

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#1581]
* move `Network.NTP.Test` into `demo-ntp-client` executable
* `test-ntp-client`: pull the library rather than require `src` directory.
* we also could add a private library which  exposes more things (required for tests) and the main library which only exposes `Network.NTP.Client` module hiding all the implementation details from consumers of `ntp-client`.

**Comment by MarcFontaine** [comment]
This is the PR (WIP) https://github.com/input-output-hk/ouroboros-network/pull/1598
