### ISSUE TITLE
 Better retry-policy for the NTP client

### ISSUE THREAD

**Issue by MarcFontaine** [input-output-hk/ouroboros-network#1583]

**Comment by MarcFontaine** [comment]
When an NTP query fails it retries using the sequence retry delays:
[5, 10, 20, 40, 80, 160, 320, 600 ..600], i.e. it slows down the retries exponentially
until a maximum delay of 600s == 10 minutes.
This sequence should be reset to 5s when the queries start to fail (after at least one successful query)

**Comment by coot** [comment]
It would be nice to do that without a shared state.

**Comment by MarcFontaine** [comment]
https://github.com/input-output-hk/ouroboros-network/pull/1596
