### ISSUE TITLE
Make sure we have golden tests for everything we send across the network

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#1592]
We have _some_ tests but aren't very consistent.

**Comment by kderme** [comment]
Should this also target shelley or just byron?

**Comment by edsko** [comment]
Eventually also Shelley, but Byron is the high priority right now as that needs to be a stable interface, Shelley can still change.

**Comment by mrBliss** [comment]
Oh, @kderme, can you add golden tests for block, header, `HeaderHash`, `GenTx` and `ApplyTxErr` for Byron? (These would catch the breaking changes in https://github.com/input-output-hk/ouroboros-network/pull/1887)

**Comment by mrBliss** [comment]
Closed by #1857.
