### ISSUE TITLE
Use the transaction generators from the Mempool tests when forging blocks

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#1613]
In #1599, generators for valid and invalid transactions were added. These should replaced/augment https://github.com/input-output-hk/ouroboros-network/blob/bcd718c65c4846ab6f3dad2cec841b00df1ff274/ouroboros-consensus/test-consensus/Test/ThreadNet/TxGen.hs#L70

**Comment by nfrisby** [comment]
Are you referring to the following generator?

https://github.com/input-output-hk/ouroboros-network/blob/abc472c3149bdaa4a3b40e8a7163788db5f692dc/ouroboros-consensus/test-consensus/Test/Consensus/Mempool.hs#L374-L380

Does you have an estimate for how simple it will be to convert that function from `TestBlock` to `ByronBlock`?

**Comment by mrBliss** [comment]
Indeed, that generator, in particular:
https://github.com/input-output-hk/ouroboros-network/blob/abc472c3149bdaa4a3b40e8a7163788db5f692dc/ouroboros-consensus/test-consensus/Test/Consensus/Mempool.hs#L439 and
https://github.com/input-output-hk/ouroboros-network/blob/abc472c3149bdaa4a3b40e8a7163788db5f692dc/ouroboros-consensus/test-consensus/Test/Consensus/Mempool.hs#L475

These use the [mock UTxO](https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-consensus/ouroboros-consensus-mock/src/Ouroboros/Consensus/Mock/Ledger/UTxO.hs), so the generators would have to be converted to use the Byron UTxO.

**Comment by edsko** [comment]
Closing this since we have the dual Byron tests.
