### ISSUE TITLE
Enable NodeToNodeV_2

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#1633]
> In https://github.com/input-output-hk/ouroboros-network/pull/1632 we prepared consensus to be able to instantiate the chain sync protocol with a sized header. We did however not enable it yet, as we wanted to bundle this with other network protocol changes.
>
> Marking as medium priority because we are now able to enable this at any point without breaking compatibility, and moreover it is an optimization only, enabling the block fetch client to make better decisions.

**UPDATE:** We'll need `NodeToNodeV_2` for two things:

1. `ByronNodeToNodeVersion2`, which enables the block size hints to be sent along Byron headers, used by the ChainSync protocol, as described above.
2. `CardanoNodeToNodeVersion2`, which enables the hard-fork compatible format of the `CardanoBlock`. See https://github.com/input-output-hk/ouroboros-network/blob/f9469fa3885aefdfa852216a66c4e319a0d19c11/ouroboros-consensus-cardano/src/Ouroboros/Consensus/Cardano/Node.hs#L210

It seems like the network team are also planning to enable the [`MsgKThxBye` message](https://github.com/input-output-hk/ouroboros-network/blob/02ff4eaeb8c4fa47a6b6d99cbd1219f209de3c05/ouroboros-network/src/Ouroboros/Network/Protocol/TxSubmission/Type.hs#L231) with V2. There's also the [upcoming `KeepAlive` protocol](https://github.com/input-output-hk/ouroboros-network/pull/2251/) that will need to be enabled at some point.

Similarly, we'll need `NodeToNodeV_3` for [`CardanoNodeToNodeVersion3`](https://github.com/input-output-hk/ouroboros-network/blob/f9469fa3885aefdfa852216a66c4e319a0d19c11/ouroboros-consensus-cardano/src/Ouroboros/Consensus/Cardano/Node.hs#L216).

**Comment by mrBliss** [comment]
@coot @dcoutts If we want to be able to run a `cardano-node` with `CardanoBlock` that actually forks to Shelley, we'll need this new version.

**Comment by coot** [comment]
That's ok, there's no reason to be held back by us.
