### ISSUE TITLE
bug in `rewindHeaderState` triggered by EBBs

### ISSUE THREAD

**Issue by nfrisby** [input-output-hk/ouroboros-network#1690]
https://github.com/input-output-hk/ouroboros-network/blob/599afc730af5f8d64accc6ab1c8d05bdb27ee7d8/ouroboros-consensus/src/Ouroboros/Consensus/HeaderValidation.hs#L200-L209

If `p` is an EBB with a proper block in the same slot, then the `annTipPoint t > p` is correct only half of the time: it will either correctly rewind the tips to the EBB or it will incorrectly also retain the proper block, depending on how the hashes happen to compare.

**Comment by edsko** [comment]
`#@!%!@#!@%!@` EBBs `@#!#@^#!@#!@%!@#u@$*&@#*@&!#!`

I'm thinking maybe there is an easier solution here. Rewinding is only allowed to rewind to a point previously applied right? So perhaps we can just say 

```haskell
    rolledBack :: AnnTip blk -> Bool
    rolledBack t = annTipPoint  t /= p
```

instead? We are dropping from the right after all. @nfrisby , @mrBliss , what do you think?

**Comment by mrBliss** [comment]
I like Edsko's proposed fix, it's simple.
