### ISSUE TITLE
Introduce hard-coded list of EBBs?

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#1694]
Now that the OBFT hard fork has taken place, we can be sure that there will be no more EBBs forged, ever. This means that in principle we could hardcode a list of all known EBBs

```haskell
knownEBBs :: Set ByronHash
knownEBBs = Set.fromList [ .. 175 or so hashes .. ]
```

(potentially with an global `IORef` and an `unsafePerformIO` if we wanted to override this list for the benefit of testing). Such a constant would allow us to statically determine if a particular hash corresponds to an EBB or not. 

My gut feeling is that this will enable us to simplify the code in quite a few places, and avoid many of the EBB related bugs that have been plaguing `ouroboros-consensus`. So often we were unable to do the right thing because we did not know if a particular block was an EBB or not. However, I've so far failed spectacularly to convince @mrBliss of this, so I need to think this through.

**Comment by edsko** [comment]
One example where we needed this kind of context: we introduced annotated tips precisely so that we could pass through information on whether or not something is an EBB.

**Comment by mrBliss** [comment]
Done in #2339.
