### ISSUE TITLE
ntp-client does not work on Windows

### ISSUE THREAD

**Issue by piotr-iohk** [input-output-hk/ouroboros-network#1785]
While integrating ntp-client with cardano-wallet https://github.com/input-output-hk/cardano-wallet/issues/1394 we have learnt that ntp-client currently does not work on Windows platform (tested on Windows 10 VM).

The error reported is:
```
ntp client experienced error Network.Socket.recvBufFrom: failed (Invalid argument (WSAEINVAL)) when using IPv4 protocol
```

Please also note that, while working on the integration we also had observation that the `ouroboros-network/ntp-client` library is missing tests on error paths -> https://github.com/input-output-hk/cardano-wallet/issues/1394#issuecomment-595084104

**Comment by coot** [comment]
Related to #1548
