### ISSUE TITLE
Document ChainSync protocol

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#180]
Document:
* the state machine
* transitions and messages
* include a short prose description of the protocol

**Comment by MarcFontaine** [comment]
Done in #325
Documentation of the chain-sync mini-protocol is finished
(review of the document by the team will be done in extra task)

**Comment by MarcFontaine** [comment]
Sorry my failure in the workflow.
This should move to Done before being closed

**Comment by coot** [comment]
I got confused by this today as well.

**Comment by MarcFontaine** [comment]
I had accidentally clicked on the close button.
I guess the ticked should move to done before being closed.
The Section "Single Phase Chain Synchronization Protocol is ready for review"
