### ISSUE TITLE
Use toCBORABlockOrBoundaryHdr from cardano-ledger

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#1805]
The encoding of `byron` blocks should be defined in `cardano-ledger.  I introduced `toCBORABlockOrBoundaryHdr` in this PR: https://github.com/input-output-hk/cardano-ledger/pull/729/files#diff-94f1509fae28f932d972168733b3bf95R542 (about to be merged).

`cardano-ledger` contains size estimations of encoded messages including `toCBORABlockOrBoundaryHdr` - that was the original reason to move the function there.

**Comment by mrBliss** [comment]
We can use `toCBORABlockOrBoundaryHdr` in [`encodeUnsizedHeader`](https://github.com/input-output-hk/ouroboros-network/blob/50f059c4c6d0ccd20d5a06aba438373adbb8f832/ouroboros-consensus-byron/src/Ouroboros/Consensus/Byron/Ledger/Serialisation.hs#L302).
