### ISSUE TITLE
Document low level wire protocol, serialisation and frameing.

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#182]
Write the necessary documentation for the wire protocol, serialisation and frameing as developed in #59.

**Comment by MarcFontaine** [comment]
complete up to the wire format of the opening message

**Comment by MarcFontaine** [comment]
The implementation and the documentation have gone though several revisions.
I'm closing this issue as it is already quit old and new issues with the documentation should be tracked separately.
