### ISSUE TITLE
Set proper `AcceptedConnectionsLimit` limits

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#1836]
To set proper `AcceptConnectionsLimit` we need to know how many file descriptors per connection consensus will use (for both upstream and downstream connections); how many downstream peers we want to support.  This should allow us to estimate the `acceptConnectionsHardLimit` (hard limit of accepted connections).

**Comment by dcoutts** [comment]
One idea to sanity check this is the following:

 * We establish with the consensus team a linear function relating the number of clients and the number of FDs used.
 * On network subsystem startup we query the OS for the maximum number of FDs we can use (i.e. unix soft ulimits, and can ignore this problem on Windows for now)
 * We check that the number of FDs available is bigger than the number implied by the configured client connection count (via the linear function relationship) and fail if it is not

This way, we ensure that we do indeed have the FD resources available for the maximum number of clients.

As an additional bonus, we could have an automatic/default mode where if the number of clients is not set, that we derive it from the FDs available (with some sane caps).

**Comment by dcoutts** [comment]
Note that this ticket is about providing a more convenient way to set the limit, and sanity checking it against FD limits.

The current limit is hard coded in the node top level at 512.
