### ISSUE TITLE
Named pipes error when restoring wallet

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#1874]
Running a wallet server with 4 wallets (which means 5 connections through a named pipe), this error is thrown: 
```
ThreadId 19 CreateFile "\\\\.\\pipe\\cardano-node-mainnet_flight": invalid argument (All pipe instances are busy.)
```

**Comment by dcoutts** [comment]
QA confirm the changes in #1876 and #1881 fix things for the wallet backend and Daedalus, tested with multiple wallets.
