### ISSUE TITLE
P2P Governor needs to reinit the dns lib.

### ISSUE THREAD

**Issue by karknu** [input-output-hk/ouroboros-network#1893]
The p2p governor needs to reinitialize the dns library frequently to get around the limitation that the dns library only reads the `/etc/resolv.conf` file once.

https://github.com/input-output-hk/cardano-node/issues/731
#1891

**Comment by dcoutts** [comment]
Also related: #1961. Have to keep that aspect too.

**Comment by coot** [comment]
Done in #2311
