### ISSUE TITLE
Integrate pre-Shelley era ledger.

### ISSUE THREAD

**Issue by LizBancroftIOHK** [input-output-hk/ouroboros-network#191]

**Comment by edsko** [comment]
Although in an ideal world this would be simple, allowing a fair amount of time here since the first integration point will likely require some minor modifications on both sides.

**Comment by edsko** [comment]
WIP PR at https://github.com/input-output-hk/ouroboros-network/pull/531 .

**Comment by edsko** [comment]
The PR is near ready for merging, finishing touches. C
