### ISSUE TITLE
Include a connection identifier in the mini-protocol thread labels

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#1917]
In https://github.com/input-output-hk/ouroboros-network/commit/fa5f50583a8f19d9e70f8405fbbd782f9805ea0e (as part of #1916), consensus started labelling the mini-protocol threads, e.g., "ChainSyncClient".

It would be better if this label include an identifier for the connection so that it is possible to see which threads are related to the same node. This identifier should be short and simple, e.g., just a number that is the same for all threads connected to the same node. I think that a whole IP-address is too verbose.

Were the labelling is currently done, in `consensusNetworkApps`, we only have access to `Ord peer` and I think `Show peer` would be too verbose.

**Comment by karknu** [comment]
This was implemented in 1ffd9f2598f66812998c2020883c2e4dacade1c5
