### ISSUE TITLE
Anachronistic protocol ledger view is the wrong concept

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#1933]
The anachronistic ledger view returns a `LedgerView` within a certain window from the current ledger tip

```
                 <---------|--------->
                           |
---------------------------X-----------------
```

If we use Byron as our running example, the `LedgerView` is a `Delegation.Map`, and the range is `±2k`. This is fine as long this `LedgerView` is only on the same fork, but _this is wrong when used across forks_. Suppose we have 

```
                 <---------|--------->
                           |
--------------------A------X-----------------
                    \
                     -------------Y---
```

where we have a point `Y` on a different fork than `X`, where `Y` still falls within the bounds that the anachronistic ledger views, but is _outside_ that same `2k` range from `A`. Then the `Delegation.Map` as `X` may well not apply anymore to `Y`; after all, there could have been some delegation certificates on `Y`'s branch between `A` and `Y` that have come into effect. 

The primary use case of the anachronistic ledger view is to use _our current ledger_ to validate block headers received by the chain sync client, which may indeed well live on a different chain. This means that we may currently accept some headers as valid that aren't (although they will then subsequently be rejected by the chain DB), or -- potentially worse -- reject some headers as invalid that in fact are valid. 

The right approach is to split this into two steps: in principle at least, we should _first_ go back to the intersection point `A`, get the delegation state there (that is, the current mapping as well as any scheduled delegations), then use that to derive a "forecast" which we can use to derive conclusions about `Y`; moreover, the range of that forecast should be determined by `A`, not by `X`. We don't literally have to implement that (though we might want to, see #1935 ), but what we do implement should be equivalent to that.

**Comment by edsko** [comment]
Note that if the intersection point is `2k` slots back (worst case scenario, both because it's the most distant possible fork and the lowest possible chain density), then the range of the forecast is only up to the current slot, which means we can't look ahead at _all_. This implies that we would never adopt such a fork, because we would not be able to validate enough of it to get a chain that is longer than our current one, and so we would not prefer it. This means the effective maximum rollback is `k - 1`. We consider this acceptable.

**Comment by nfrisby** [comment]
> Note that if the intersection point is `2k` slots back, then the range of the forecast is only up to the current slot, which means we can't look ahead at _all_. This implies that we would never adopt such a fork, because we would not be able to validate enough of it to get a chain that is longer than our current one, and so we would not prefer it.

This doesn't seem right to me. In particular, I think that use of "look ahead" is too focused on slots. Is this following counterexample correct?

Suppose k is 3 and our current chain X is D16, which is as sparse as the chain density invariant allows.

`A10 > B12 > C14 > D16`

Suppose we suddenly learn about a chain Y = U14.

`A10 > R11 > S12 > T13 > U14`

Because Y is more dense than X, it has more blocks within 2k slots of A10, even though its tip is from an earlier slot. So we'll be able to project the A10 ledger view forward enough to validate Y. And then we'll switch to it. Am I missing something, or does that contradict the blockquote? @edsko

**Comment by edsko** [comment]
Sure, there are cases when we _can_ switch, but if the alternative chain is _also_ at it's lowest density, we won't be able to.

**Comment by edsko** [comment]
Draft PR fixing this at #1942.

**Comment by nfrisby** [comment]
> Sure, there are cases when we _can_ switch, but if the alternative chain is _also_ at it's lowest density, we won't be able to.

Ah, I see. So when the intersection is `2k` slots and `k` blocks back _from both tips_. 👍 

A10 > B12 > C14 > D16
A10 > R12 > S14 > T16
