### ISSUE TITLE
Avoid a-priori "in future" check in Chain DB

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#1948]
The goal of the proof discussed as part of #1933 to show whether or not we can use a ledger state at point `X` to derive timing conclusions (`SlotNo` to `UTCTime` conversion) for some point `Y`

```
------ A ----------X
       \
        \
         -------Y
```

or

```
------ A ----------X
       \
        \
         ---------------Y
```

The conclusion was that we can do this as long as `Y` is within the forecast range at the intersection point `A`. This makes sense, intuitively: if `Y` is outside of that range, a hard fork could have been confirmed somewhere between `A` and `Y`, which could have taken effect before `Y`, thereby effecting the timing conversion for `Y`.

The chain sync client knows what that intersection point `A` is (as of https://github.com/input-output-hk/ouroboros-network/pull/1942 it maintains it as part of its local state), and so it can pass that to `timingForecastAt` (as well as `ledgerViewForecastAt`). This then allows it to back off (block) when we have reached the end of the forecast range, and wait for the block fetch logic to catch up, or disconnect (if we end up switching to a fork).

However, when we pass the block to to the chain DB (using `addBlock`), we _no longer know what that intersection point is_. This means that the chain DB can no longer determine if it is able to to time conversion of the block's slot number given its own current ledger state (much less decide what to do it it can't). If it conservatively put that intersection at `2k` slots back, we may not be able to validate any headers past our own tip (in low density chain conditions); if it optimistically put the intersection at our own tip, we might reach the wrong conclusions, applying changes that happened on our branch to a block from a different branch.

So I propose that we don't check ahead of time _at all_ if a block is in the  future, and instead simply discover during chain selection if it or not, and if it is, don't include it in the chain selection yet. This has the nice added bonus that it will simplify the chain DB, and remove two places where we use time (`addBlock` and the scheduled chain selection runner). 

We should consider what the ramifications of this change are. The most important use case of the chain sync client. It has already done a "in the future" check, but will allow for some clock skew. If it only very occasionally happens that we get a block from the future, the additional wasted chain selection is not problematic. Suppose however that our system clock is behind (maybe the user is not running NTP), and _every_ block that comes in is (according to our clock) from the future. When the first block comes in, we will run chain selection, discover the block is from the future, and not change anything. Now the second block comes in; we again run chain selection, disregard the second block _but now discovering the first_, and so this chain selection is useful and we adopt the first block. From this point forward, each block that comes in will trigger a chain selection that discovers the previous, and no chain selection is wasted.

**Comment by edsko** [comment]
Marked as high priority as this is blocking the hard fork combinator.

**Comment by edsko** [comment]
WIP PR at https://github.com/input-output-hk/ouroboros-network/pull/1989 . This introduces a `CheckInFuture` abstraction and threads that through the Chain DB, making the chain DB independent from the `BlockchainTime`. Still needs to be done:

* Actually _use_ this abstraction during chain selection as a second validation step, excluding blocks in the future from chain selection, repeating the chain selection process just like for any other invalid block, _but_ only marking them as invalid if they exceed the clock skew.
* Re-enable the block-in-future tests of the Chain DB
* Add functionality to the Chain DB to consider the previously-set-aside blocks during `addBlock`.

Handing this over to @mrBliss while I will continue on the hard fork stuff.

**Comment by mrBliss** [comment]
Already done in #2003 (which includes #1989).
