### ISSUE TITLE
Consensus_Test Consensus Protocols

### ISSUE THREAD

**Issue by LizBancroftIOHK** [input-output-hk/ouroboros-network#195]
We have some tests for the consensus protocols already, but there are rather minimal and need to be seriously extended. 

- [ ] Currently we assume a fully connected network topology. We need to test with all kinds of topologies.
- [ ] We need to introduce network latencies
- [ ] We need to introduce network disconnects (either a single node disconnecting and later reconnecting), or the network temporarily becoming partitioned -- the later case being more important.
- [ ] Nodes joining the network later (this will be _especially_ important for genesis) (those nodes may or may not already have some initial state).
- [ ] Possibly we should also think about adversaries, though that might be difficult. However, @brunjlar tells me that the crypto people are working on some kind of "perfect/strongest adversary" definition. If we had such a definition perhaps that might help.

Ideally we'd like to test the above in a reproducible and shrinkable way. 

- [ ] In order to test whether things still work when we have no leaders in a slot, or more than one, we should have a way to specify the leader schedule explicitly. We already have a protocol combinator that makes this possible, so this has been done to some degree.
- [ ] Ideally we'd like to be able to generate some kind of script that tells us precisely how the network evolves, network latencies, the duration of the test, when errors occur (possibly which leaders are selected when), so that we can then construct q-s-m tests that produce these scripts, test for errors, and shrink them when an error is found.

We also need to check more properties.

- [x] We already check the common prefix property
- [ ] Chain growth (might be difficult, depends on parameters such as the "stake of the adversary")
- [ ] Chain quality
- [ ] Whether specific transactions get included into the blockchain

**Comment by edsko** [comment]
In `prop_simple_bft_convergence` we have

``` haskell
takeChainPrefix :: Chain (Block DemoBFT) -> Chain (Block DemoBFT)
takeChainPrefix = id -- in BFT, chains should indeed all be equal.
```

This however I think is not true once we start having network failures (@brunjlar , do you agree?)

**Comment by edsko** [comment]
Replaced this ticket with a more detailed breakdown.
