### ISSUE TITLE
cborg exceptions handling

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#1965]
`cborg` might throw other exceptions than `DeserialiseFailure`, @mrBliss found this example:

```
> let Right (_, oops :: Natural) = deserialiseFromBytes fromCBOR (toLazyByteString (toCBOR (-316462907602011424125126285746442964296)))
> oops
*** Exception: arithmetic underflow
```

We should investigate all possible exceptions and rethrow them using a  single wrapper which includes `DerserliaseFailure`.

Related to #1964

**Comment by mrBliss** [comment]
Note that `DeserialiseFailure` is not _thrown_, it is returned.

**Comment by dcoutts** [comment]
This is clearly a bug in the `Natural` instance for `FromCBOR`. It should indeed fail in the decoding monad, not throw an exception.

**Comment by dcoutts** [comment]
Ah, thanks @mrBliss you fixed in https://github.com/input-output-hk/cardano-base/pull/103

**Comment by coot** [comment]
Can we close this, or shall we keep this open for doing an audit of `FromCBOR` instances and/or `cborg`.
