### ISSUE TITLE
Integrate real crypto for Shelley testnet

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#1985]
We need to pick values for the type members of https://github.com/input-output-hk/cardano-ledger-specs/blob/9358418eb1a54c0f264d8d255025e0b020390bb4/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/Crypto.hs#L24.

At the moment we have:
```
instance Crypto TPraosStandardCrypto where
  type DSIGN TPraosStandardCrypto = Ed448DSIGN
  type KES   TPraosStandardCrypto = SimpleKES Ed448DSIGN
  type VRF   TPraosStandardCrypto = SimpleVRF
  type HASH  TPraosStandardCrypto = SHA256
```

Before we can deploy on a testnet, we should adopt:

* [x] DSIGN = [Ed25519](https://github.com/input-output-hk/ouroboros-network/pull/1984)
* [ ] KES = a non-evolving KES
* [x] HASH = [Blake2b_256](https://github.com/input-output-hk/ouroboros-network/pull/1986)

We'll stick to `SimpleVRF` for the testnet. See #261 for mainnet.

**Comment by edsko** [comment]
(Note to self: `SimpleKES` is fine in theory, but leads to very large signatures.)
