### ISSUE TITLE
Test file locking with lazy release

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#1996]
In #1906, we added a timeout to file locking. We should test this more thoroughly, e.g., we don't wait longer than the timeout, etc.

While adding more tests to #1906, @edsko and I discovered that releasing a file lock is not synchronous on Linux after all. We plan to abstract over the file locking API and use a mock implementation with configurable lazy lock releasing in the tests.

**Comment by kderme** [comment]
Out of curiosity curious, how did you find it's not synchronous? Did you run some script or through simple tests?

**Comment by mrBliss** [comment]
A test in which we released and reacquired with a very small delay (< 10ms), failed.
