### ISSUE TITLE
Make the delayNextSlot less flaky

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#1997]
The `delayNextSlot` sometimes fails on CI, e.g., see https://hydra.iohk.io/build/2455323/nixlog/1. It fails because depends on timing, which might be influenced by a heavily loaded CI build machine.

We have many more pure tests that test the scheduling, but the test in question is a sanity check that it works for IO too.

Maybe we can pick the test parameters (e.g., a longer `SlotLength`?) in such a way that the test is "less sensitive to timing", if that makes sense.

**Comment by edsko** [comment]
This was using a random slot length between 1ms and 1000ms. No wonder it was flaky. Have reduced that range to 100ms and 1000ms. That should make the test considerably less flaky.
