### ISSUE TITLE
Question: If I am following the chain using ouroboros mini protocol: chain sync, what case do I receive RollBackward

### ISSUE THREAD

**Issue by ashisherc** [input-output-hk/ouroboros-network#1998]
I am writing a service to sync the chain using Ouroboros mini protocol Chain Synchronisation. I wanted to understand the scenario when can I receive RollBackward message. I am syncing the chain in realtime.

I am assuming when my node switches to another fork I receive a RollBackward and I need to undo my previous blocks?

Do I ever receive a RollBackward? I kept the node running for more than 24h, did not receive a RollBackward yet!

**Comment by coot** [comment]
@ashisherc you will indeed receive `RollBackward` when a fork happened.  You will not see them when you are syncing - it would violate consensus you'd see fork longer than `2160` blocks; when synced, in the current deployment, forks are rather rare events.

> I am assuming when my node switches to another fork I receive a RollBackward and I need to undo my previous blocks?

`RollBackward` instructs the peer to roll back blocks from the local copy of the upstream chain; whether one will need to rollback blocks from its own chain will depend.  A node might follow many upstream chains.

**Comment by ashisherc** [comment]
@coot maybe I am going in the wrong direction. Here's what I am trying to build.

I'm building a similar software as cardano-db-sync that integrates well with my application. I am syncing the blocks using the chain sync protocol and creating my own database. If I receive a RollBackward, that means I need to roll back all the db changes I have done until last max of 2160 blocks? is there any reference doc on how cardano-db-sync handles forks/RollBackwards?

If the RollBackward could be as long as 2160 blocks, does it mean exchanges should also wait for that long to confirm a transaction (which is not the case at this time)?

Please guide

**Comment by coot** [comment]
Sorry, I thought your question was about `node-to`node` protocol.  For client applications using `node-to-client` protocol the answer is simpler: you need to rollback blocks to the point specified by the `RollBackward` instruction.

>  is there any reference doc on how cardano-db-sync handles forks/RollBackwards?

I am not aware of such documentation. [here] (https://github.com/input-output-hk/cardano-db-sync/blob/master/cardano-db-sync/src/Cardano/DbSync.hs#L431) is the entry point of what `cardano-db-sync` `chain-sync` client does on rollbacks.

> If the RollBackward could be as long as 2160 blocks, does it mean exchanges should also wait for that long to confirm a transaction (which is not the case at this time)?

Such long rollbacks should be extremely rare.

**Comment by ashisherc** [comment]
@coot Thank you for replying. Even if such a long rollback is extremely rare, isn't it dangerous? I take it as it is practically not possible but theoretically possible!!!

**Comment by coot** [comment]
Exchanges must deal with rollbacks. If it happens, the ledger state rollbacks too, so an exchange needs to re-submit transactions that were removed during the rollback.

**Comment by ashisherc** [comment]
In case, a user has deposited ADA on an exchange, the user trades it with another cryptocurrency and goes away with it, and such a rollback happens.  I don't know if am talking useless, just came to my mind. it would create a mess.

Priyank(ambassador) mentions that such a rollback would happen in case of a network update only, that can be handled by freezing the activity at exchanges.

Thank you for replying :)
