### ISSUE TITLE
Shelley: initial UTxO

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#2004]
`protocolInfoShelley` still mentions a dummy `genesisUtxO`:
https://github.com/input-output-hk/ouroboros-network/blob/eec4a136bb51d882ab4cf4de552f1ce978459f56/ouroboros-consensus-shelley/src/Ouroboros/Consensus/Shelley/Node.hs#L251

We should define a proper initial UTxO.

**Comment by nc6** [comment]
I'm not sure where that TODO comes from - to be honest I think that initial UTxO is fine. The ledger rules don't really care about what that value is - it simply allows anything in the initial UTxO.

**Comment by mrBliss** [comment]
> I'm not sure where that TODO comes from - to be honest I think that initial UTxO is fine. The ledger rules don't really care about what that value is - it simply allows anything in the initial UTxO.

I suppose it's more about the string `"In the beginning"`. Do we want that in the release?

**Comment by nc6** [comment]
What random string would you rather have? :-D

**Comment by edsko** [comment]
I don't care very much about the string, but _is_ this the right initial UTxO? We want people to actually be able to interact with the testnet no? Doesn't that mean we need a carefully crafted initial UTxO so that we can hand out keys etc?

**Comment by nc6** [comment]
The string in here concerns the _input_ to the initial UTxO. It's completely arbitrary, and is never checked anywhere in the rules. The outputs to the initial UTxO are determined by `ShelleyGenesis` - in testing, we simply allocate all funds to the core node keys.

**Comment by edsko** [comment]
Ok, yes, I misunderstood. So, the string doesn't matter (the hash of the "virtual" genesis transaction). However, the _index_ does certainly matter: we cannot have a single `(txId, index)` map to multiple outputs. Indeed, this map will always be a singleton map. 

How come the tests work with this?

**Comment by edsko** [comment]
Moreover, that number _matters_. It should be part of `sgInitialFunds` (otherwise people would have to search the UTxO to find which one is theirs? I guess that's also fine.)

**Comment by nc6** [comment]
> However, the index does certainly matter: we cannot have a single (txId, index) map to multiple outputs. Indeed, this map will always be a singleton map.

I mean, the answer is basically that we _can_. Our rules are inductive. Anything in at the beginning is valid by definition. If we wanted to use the index to identify specific initial fundholders, we could, but it would just be for convenience.

(Maybe not _just_ for convenience. Whilst our rules are inductive, we do try to express some properties globally, and it's true that e.g. "no double spending" would be more straightforward if we used multiple indices)

So based on this last comment, it might be worth using multiple indices. Not high priority, though.

**Comment by edsko** [comment]
I still don't think this is quite right. You are producing a singleton map independent of the size of `sgInitialFunds`. That doesn't feel right to me.

**Comment by nc6** [comment]
Yep, obvious elephant now spotted. Will address that!

**Comment by mrBliss** [comment]
Fixed by #2038.
