### ISSUE TITLE
Shelley: choose the right initial nonce

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#2005]
Fix this TODO:
https://github.com/input-output-hk/ouroboros-network/blob/eec4a136bb51d882ab4cf4de552f1ce978459f56/ouroboros-consensus-shelley/src/Ouroboros/Consensus/Shelley/Node.hs#L209

**Comment by nc6** [comment]
I think the easiest thing to do for this is to seed the nonce with some randomness we can insert in `ShelleyGenesis`. Then people who know more about crypto can decide how much we care about that randomness.

**Comment by mrBliss** [comment]
Nonces in question: https://github.com/input-output-hk/ouroboros-network/pull/2147/files#diff-d2f1c2d3ca7a404a7f9608acbec24fabR275

**Comment by mrBliss** [comment]
@JaredCorduan With all these discussions about nonces, I don't know what the final decisions were :confused:. Let me go over the places in consensus where we currently pick a nonce so we can check whether we make the right choice.

### A fresh Shelley chain

When starting a Shelley chain from scratch, like in the F&F testnet, we call [`initialShelleyState`](https://github.com/input-output-hk/cardano-ledger-specs/blob/59f8c946b231d4d2c01f974ba4ddb76334a5eb7e/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Chain.hs#L128) in consensus with `SL.NeutralNonce` as the `initNonce` argument here: https://github.com/input-output-hk/ouroboros-network/blob/c1f65da121805cd3903915ab0ccad576554d3c68/ouroboros-consensus-shelley/src/Ouroboros/Consensus/Shelley/Node.hs#L175-L186

Looking at [`initialShelleyState`](https://github.com/input-output-hk/cardano-ledger-specs/blob/59f8c946b231d4d2c01f974ba4ddb76334a5eb7e/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Chain.hs#L167-L170), this means we use that `SL.NeutralNonce` argument for the following nonces: "Current epoch nonce", "Evolving nonce", and "Candidate nonce". The fourth and final nonce, "Prev epoch hash nonce", is hard-coded in `initialShelleyState` to be `NeutralNonce`.

*Is this correct?* The alternative is to create a nonce from the hash of the Shelley genesis config file and pass that to `initialShelleyState`.

### The Byron-to-Shelley hard fork

When transitioning from Byron to Shelley, we have to translate the Byron protocol state to the Shelley protocol state ([`PrtclState`](https://github.com/input-output-hk/cardano-ledger-specs/blob/d44714a5263053ff4affbe1d2760cbb774e2ff60/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Prtcl.hs#L67)). This happens here: https://github.com/input-output-hk/ouroboros-network/blob/c1f65da121805cd3903915ab0ccad576554d3c68/ouroboros-consensus-cardano/src/Ouroboros/Consensus/Cardano/CanHardFork.hs#L446-L460
At the moment, we use the `NeutralNonce` for all four nonces. 

*Is this correct?* The alternative is again to create a nonce from the hash of the Shelley genesis config file and use that for all four nonces, or just the first three (so not the "Prev epoch hash nonce"). Note that we don't have access to the last Byron hash as we don't track it in the `PBftState`. Access to the hash of the Shelley genesis config file is possible, as it is something static that we can store in our config data types.

**Comment by JaredCorduan** [comment]
Thank you for such a clear and organized question @mrBliss !

We can do the same thing for both a fresh Shelley chain and a chain from Byron. We should set "Current epoch nonce", "Evolving nonce", and "Candidate nonce" to the same value X, and the "Prev epoch hash nonce" to the `NeutralNonce`. I think we should set X to the hash of the Shelley genesis config file (I am confirming this with the cryptographers now, and will let you know).

For a bit of explanation:

At the start of an epoch, the "Current epoch nonce", "Evolving nonce", and "Candidate nonce" will always be the same value (equal to each other, not the same value between epochs :) ). The "Prev epoch hash nonce" does not matter at the start of the epoch, we just store this value so that when a new epoch begins we can use the hash of the last block in the previous epoch to create the next Current epoch nonce. In other words, the "Prev epoch hash nonce" will just be immediately overridden on the next block. So `NeutralNonce` is great.

**Comment by mrBliss** [comment]
> Thank you for such a clear and organized question @mrBliss !
> 
> We can do the same thing for both a fresh Shelley chain and a chain from Byron. We should set "Current epoch nonce", "Evolving nonce", and "Candidate nonce" to the same value X, and the "Prev epoch hash nonce" to the `NeutralNonce`. I think we should set X to the hash of the Shelley genesis config file (I am confirming this with the cryptographers now, and will let you know).

Thank you for the clear answer! I'll start implementing this now (I can backtrack if the cryptographers disagree).

> 
> For a bit of explanation:
> 
> At the start of an epoch, the "Current epoch nonce", "Evolving nonce", and "Candidate nonce" will always be the same value (equal to each other, not the same value between epochs :) ). The "Prev epoch hash nonce" does not matter at the start of the epoch, we just store this value so that when a new epoch begins we can use the hash of the last block in the previous epoch to create the next Current epoch nonce. In other words, the "Prev epoch hash nonce" will just be immediately overridden on the next block. So `NeutralNonce` is great.

I see. The last part I remembered. Crystal clear now :+1:

**Comment by nfrisby** [comment]
I'm not sure if this is already supported by the above discussion, but the tests should be able to twiddle the initial Shelley nonce independently for the sake of statistical testing and similar. So it'd be good to parameterize the initial nonce selection at least out to the interface that testing should use.

**Comment by mrBliss** [comment]
I'm still awaiting a decision on how to compute the genesis hash in https://github.com/input-output-hk/cardano-ledger-specs/pull/1558#issuecomment-645213133.

However, I can already parameterise the code (`ConsensusConfig` for `TPraos`) over the initial nonce (prep for #2235). After a decision about the computation of the genesis hash is made, it will then just be a matter of passing the right nonce to the `ConsensusConfig`.

**Comment by mrBliss** [comment]
Quoting from https://github.com/input-output-hk/cardano-ledger-specs/issues/1531#issuecomment-648751584:

> I had a discussion with @nc6 and we decided that it's best to just use the `Nonce` type directly for this, both in `cardano-ledger-specs` (to avoid confusion as `Genesis(Config)Hash` would not be related to the existing `GenesisHash` and genesis in any way) and in `ouroboros-consensus` (we just need a `Nonce` for entropy, we also don't care where it comes from). Only in `cardano-node`, where they have to provide that `Nonce` to consensus (via `ProtocolInfo`, is the choice made to use the hash of the Shelley genesis JSON file.
