### ISSUE TITLE
Chain DB

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#201]
We need a layer that sits on top of the immutable store and the volatile store, and presents a unified inferface. 

* It should move blocks from the volatile store to the immutable store whenever appropriate. There should be overlap between the two so that the chances of a _gap_ between the two DBs in case of a truncation (remember that we do no `fsync`s) of the immutable DB due to a disk error is minimized.

**Comment by edsko** [comment]
To be rebranded as the `ChainState`.

**Comment by edsko** [comment]
I horribly underestimated the time needed to implement this, but on the other hand, that's partly also because the Chain DB has been given much more autonomy. It has become quite a central part in the consensus layer.

**Comment by mrBliss** [comment]
See #617.
