### ISSUE TITLE
Volatile block storage

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#202]
The volatile store block storage is

* Append-only
* Garbage collected (API call "we don't need any blocks older than _x_", which would remove any files that are now entirely obsolete and keep the rest)
* In memory storage of an index (point -> file/offset) as well as an in-memory single value recording the most recent block in any file (for GC)
* Arbitrary but relatively large file size (should be configurable)
* Should be robust to IO errors:
  - Unclean shutdown (truncated files due to lack of `fsync`)
  - Corruption of random point in a file
  - IO exceptions during operation (i.e., disk full, hard -- unrecovrable -- IO failure)
* The abstract model in this case should simply be that the resulting "key/value map" is a subset of the original.

**Comment by edsko** [comment]
One slight complication here: blocks must be identified by "points" (a slot and a hash), but GC will probably just be in terms of a slot. @kderme , this means you might need to pass a `t -> Slot` argument to `GC`?

**Comment by kderme** [comment]
> One slight complication here: blocks must be identified by "points" (a slot and a hash), but GC will probably just be in terms of a slot. @kderme , this means you might need to pass a `t -> Slot` argument to `GC`?

Probably yes unless we use the HasSlot abstraction.

**Comment by edsko** [comment]
Don't think that will be necessary here.

**Comment by kderme** [comment]
I copy here what Duncan mentioned in slack: 
> for the volatile DB and specifically the point -> block info mapping, we're going to need some "fingerprint" to use in STM txs to see if it's changed, so we can do `retry` efficiently. We don't need to reveal concrete details so long as we can provide a fingerprint type with an Eq instance. My though for a concrete representation of that though would be the pair of the current size of the mapping and the earliest slot that the mapping covers. If it's append only except for bulk deletes then those two things should always change on every change right? And this would give a cheap to calculate and cheap to compare fingerprint.

**Comment by edsko** [comment]
Created separate ticket for the finger print: https://github.com/input-output-hk/ouroboros-network/issues/373
