### ISSUE TITLE
Make consensus tests work without `UnsafeUnbounded`

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#2029]
Right now the tests fail when this is not used, which means that they assume we can look ahead as far as we want.

**Comment by mrBliss** [comment]
@nfrisby What do you think is left to do before we can close this ticket?

**Comment by nfrisby** [comment]
PR #2066 will make this fundamentally possible. But what should be done for
eg `HasHardForkHistory ByronBlock`, which currently uses
`neverForksHardForkSummary`, which uses `EraUnbounded`?

**Comment by edsko** [comment]
That's fine, that instance is only relevant when using Byron as a standalone ledger. This remark in the long comment for `hardForkSummary` is relevant:

> Critically, the HFC implements 'hardForkSummary' directly and does not call 'hardForkSummary' in the underlying ledgers.
