### ISSUE TITLE
Unexpectedly many InitChainSelValidation messages

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#2035]
@erikd writes:

> when I start a new node in Shelley node in self node mode (it just talks to itself) I get 34 instances of this message:
```
[ada:cardano.node.ChainDB:Debug:5] [2020-05-03 00:16:53.99 UTC] InitChainSelValidation
```
> would be nice to get that looked at

Marking this as high priority just in case it's a bug in chain selection.

**Comment by mrBliss** [comment]
The current trace is pretty useless: https://github.com/input-output-hk/cardano-node/blob/2e0fce1e23fba324f89ed13166f468d8b9f9f4e2/cardano-config/src/Cardano/TracingOrphanInstances/Consensus.hs#L362
It should pattern match on the argument to `InitChainSelValidation` :roll_eyes:

**Comment by mrBliss** [comment]
Actual ticket: https://github.com/input-output-hk/cardano-node/issues/1123
