### ISSUE TITLE
Don't require full BlockConfig for codecs

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#2049]
At the moment, the protocol codecs require the full `BlockConfig`, which implies the full genesis. The assumption had been that this genesis value was available to all client code (since everyone must agree on it anyway), but it turns out that this is a hurdle both for the `cardano-api` and for the wallet. We should introduce a `CodecConfig` type class with just the minimum values required.

**Comment by mrBliss** [comment]
Closed by #2050.
