### ISSUE TITLE
Switch over to HardForkBlock '[ByronBlock, ShelleyBlock]

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#2062]
This is the final step in the integration of the hard fork combinator, and means that the code base (at least in principle) is ready for the hard fork.

This will introduce binary incompatibilities in the ledger DB, so the nodes will need to replay the ledger.

**Comment by edsko** [comment]
We should take advantage of this to cleanup `defaultEncodeAnnTip`.

**Comment by mrBliss** [comment]
There's nothing to do in consensus after #2147, we have the new `CardanoBlock`. @dcoutts is already working on adding support for `CardanoBlock` in `cardano-node`.
