### ISSUE TITLE
Serialisation for HardForkBlock '[ByronBlock, ShelleyBlock]

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#2073]
Crucially: needs to be binary compatible with current mainnet; so add envelope, which distinguishes all eras _other_ than Byron, but use low-level CBOR twiddling to distinguish envelope from Byron.

TODO: There is a comment somewhere explaining this in detail.

**Comment by edsko** [comment]
https://github.com/input-output-hk/ouroboros-network/pull/1175#issuecomment-558147194

**Comment by mrBliss** [comment]
Closed by #2147.
