### ISSUE TITLE
Introduce CardanoBlock 

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#2076]
Plan:

* [x] 1. Initially `CardanoBlock = ShelleyBlock` 
* [x] 2. `DegenFork ShelleyBlock` (depends on #2075)
* [x] 3. `HardForkBlock '[ByronBlock, ShelleyBlock]` (depends on #2074, #2078, verify that it can sync against mainnet).

We also need a `Protocol` constructor for `CardanoBlock`, and make sure the `cardano-node` can run with it.

**UPDATE:** replaced `ByronBlock` with `ShelleyBlock` in steps 1 and 2, see #2075 for why.

**Comment by mrBliss** [comment]
Addressed by #2147.
