### ISSUE TITLE
Consensus tests for HardForkBlock '[ByronBlock, ShelleyBlock]

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#2078]

**Comment by edsko** [comment]
This is the critical test of tests: set that we can actually transition. This will require the test infrastructure improvements that @nfrisby is currently working on, and we will need his help also in constructing the "oracle" so that we know in the test infrastructure exactly when the transition will take place.

@nfrisby , I guess this is what we really want to aim for for the current testing plans.

**Comment by edsko** [comment]
Possible simplification: if the slot length and epoch size is set to be equal between Byron and Shelley, test infrastructure improvements are not yet required. This might be a way to decouple the work.

**Comment by nfrisby** [comment]
> Possible simplification: if the slot length and epoch size is set to be equal between Byron and Shelley, test infrastructure improvements are not yet required. This might be a way to decouple the work.

I think #2066 includes most of the hard work. So decoupling only seems worthwhile if you don't like parts of that PR or if I'm overlooking the extent of the remaining details.

**Comment by edsko** [comment]
> I think #2066 includes most of the hard work. So decoupling only seems worthwhile if you don't like parts of that PR or if I'm overlooking the extent of the remaining details.

I've not had a chance to look at that yet. If the simplification is not necessary, so much the better! :)

**Comment by mrBliss** [comment]
Done in #2277.
