### ISSUE TITLE
Trace KES status for pool operators

### ISSUE THREAD

**Issue by erikd** [input-output-hk/ouroboros-network#2104]
Pool operators need an easy way to view KES data, specifically:
 ```
{
"current period": 3,
"inital period": 1,
"evolutions": 2
"remaining evolutions": 12
}
```
where those correspond to `kp_`, `c0_`, `t`, and `maxKESEvolutions - t`.

Duncan suggested that these way to get access to these would be via the tracing infrastructure and then feed that into EKG. I tried to figure out how this might be implemented but even after digging through code for ages I ~am no closer~ have no clue.

This is related to https://github.com/input-output-hk/cardano-node/issues/956

**Comment by edsko** [comment]
I guess the two places to look at `Ouroboros.Consensus.Shelley.Protocol` where key evolution is defined, and then the `nodeForgeBlock` handler for Shelley, which is the only function that gets access to the node state and gets to update it.

**Comment by mrBliss** [comment]
> Pool operators need an easy way to view KES data

Does this mean it will be a local CLI tool that communicates via a socket? Then I agree that maybe a tracer is the easiest way out.

From within a running node it would be easier: we could add a `StrictTVar m (NodeState blk)` to the `NodeKernel`. The `NodeState` for Shelley is https://github.com/input-output-hk/ouroboros-network/blob/c29fc19764732ef62712508c8bf58219d014c89b/ouroboros-consensus-shelley/src/Ouroboros/Consensus/Shelley/Protocol.hs#L137 and `HotKey` is defined as: https://github.com/input-output-hk/ouroboros-network/blob/e88f0ee194193f93e0e6c8bd2ae33f52bc3c7f0f/ouroboros-consensus-shelley/src/Ouroboros/Consensus/Shelley/Protocol/Crypto.hs#L71

**Comment by edsko** [comment]
> From within a running node it would be easier: we could add a StrictTVar m (NodeState blk) to the NodeKernel. The NodeState for Shelley is

Note a big fan of this to be honest, that's exposing the state a bit too directly for my liking.

**Comment by mrBliss** [comment]
> > From within a running node it would be easier: we could add a StrictTVar m (NodeState blk) to the NodeKernel. The NodeState for Shelley is
> 
> Not a big fan of this to be honest, that's exposing the state a bit too directly for my liking.

Oh yeah, agreed, it should expose at most `STM m (NodeState blk)`, not the `StrictTVar`.

**Comment by erikd** [comment]
I was thinking of maybe exposing a way of getting a snapshot of the state.

**Comment by dcoutts** [comment]
Seems to me that extending the `TraceForgeEvent` with relevant (public, not secret) protocol-specific info would be a reasonable approach. For Praos that protocol-specific state would include KES details.

**Comment by mrBliss** [comment]
Sketch of Duncan's suggestion:

* Introduce:
  ```haskell
  class HasForgeInfo blk where
    type ForgeInfo blk :: *
    -- Default to no info
    type ForgeInfo blk = ()
  ```
* Use the default instance for all blocks except for Shelley, which should include the required KES details.
* Make `HasForgeInfo` a super class of `RunNode` (or is there a better place to add the constraint?)
* Modify [`nodeForgeBlock`](https://github.com/input-output-hk/ouroboros-network/blob/d3c9c0d97a5979702cd13f10c3dd9a9edb6c71ab/ouroboros-consensus/src/Ouroboros/Consensus/Node/Run.hs#L61) to return `(blk, ForgeInfo blk)`.
* Propagate this change to [`produceBlock`](https://github.com/input-output-hk/ouroboros-network/blob/d3c9c0d97a5979702cd13f10c3dd9a9edb6c71ab/ouroboros-consensus/src/Ouroboros/Consensus/NodeKernel.hs#L129)
* Include this info in [`TraceForgedBlock`](https://github.com/input-output-hk/ouroboros-network/blob/eec4a136bb51d882ab4cf4de552f1ce978459f56/ouroboros-consensus/src/Ouroboros/Consensus/Node/Tracers.hs#L242). **This means the info is only traced when a block has been forged.** Is that enough?

**Comment by mrBliss** [comment]
> **This means the info is only traced when a block has been forged.** Is that enough?

As @edsk pointed out, this is also the *only* time we change the state. 

Before we implement the sketch above, I'd like to get confirmation that this is enough. cc: @erikd @dcoutts

**Comment by dcoutts** [comment]
@mrBliss on reflection I think the KES key should be evolved eagerly, not on-demand just before forging a block.

Reasons:
1. at forging time it's time sensitive, we should minimise the work we do before block forging
2. we should not remember old KES keys longer than necessary for security, and low-stake nodes will not produce blocks frequently
3. it's confusing for things like this where we want to trace the current KES key evolution number but the lazy update means that current number is out of sync with the wall clock time / slot number.

**Comment by edsko** [comment]
@mrBliss and I discussed this. I will take care of #2154 and this in one PR, there is not much point doing something in between, it won't save much time.
