### ISSUE TITLE
Links to dependencies broken in published Haddocks

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#2138]
All links to identifiers defined in dependencies are broken in the Haddocks published at https://input-output-hk.github.io/ouroboros-network/.

For example, try clicking on `Bool` in https://input-output-hk.github.io/ouroboros-network/cardano-binary/Cardano-Binary-ToCBOR.html

**Comment by coot** [comment]
An example link:
```
file:///__w/ouroboros-network/ouroboros-network/dist-newstyle/build/x86_64-linux/ghc-8.6.5/cardano-binary-1.5.0/noopt/doc/html/cardano-binary/src/Cardano.Binary.Annotated.html#Annotator
```
or the mentioned `Bool`
```
file:///opt/ghc/8.6.5/share/doc/ghc-8.6.5/html/libraries/base-4.12.0.0/Data-Bool.html#t:Bool
```

I think I know where they are coming from, but I am not sure how easy is to fix this.

**Comment by coot** [comment]
This will be fixed once we switch to [`cabal haddock-project`](https://github.com/haskell/cabal/pull/8162).
