### ISSUE TITLE
Incorporate decisions regarding floating point in Praos calculations

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#216]
See

https://github.com/input-output-hk/fm-ledger-rules/tree/master/dependencies/non-integer

**Comment by edsko** [comment]
Note on time estimate: this is assuming we don't have to do any floating point research and just need to _apply_ the existing research.

**Comment by edsko** [comment]
Similar remark as https://github.com/input-output-hk/ouroboros-network/issues/199#issuecomment-495527275 .

**Comment by edsko** [comment]
@nc6 do we need to keep this ticket open, or does #982 subsume it?

**Comment by edsko** [comment]
Only remaining concern: the computation of the leader threshold is done `-consensus` side and uses `Double`, but the _verification_ is done `-specs` side and will use "proper" non-floating point. This means that we could produce a block we will ourselves reject, or we might miss an opportunity to produce blocks; both scenarios are not critical, and anyway should happen very rarely since this will only happen due to floating point errors. Would still be good to address though, obviously, so assigning medium priority.

Better yet would be to move this logic to`-specs` side also so that this is no longer a `-consensus` concern.

**Comment by edsko** [comment]
See https://jira.iohk.io/browse/CAD-885 for adding this logic to `-specs`.

**Comment by mrBliss** [comment]
> Only remaining concern: the computation of the leader threshold is done `-consensus` side and uses `Double`, but the _verification_ is done `-specs` side and will use "proper" non-floating point. This means that we could produce a block we will ourselves reject, or we might miss an opportunity to produce blocks; both scenarios are not critical, and anyway should happen very rarely since this will only happen due to floating point errors. Would still be good to address though, obviously, so assigning medium priority.
> 
> Better yet would be to move this logic to`-specs` side also so that this is no longer a `-consensus` concern.

This [function](https://github.com/input-output-hk/cardano-ledger-specs/blob/4d16234a92c468eaef1ea8cf2c83e332f545df3b/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/BlockChain.hs#L629) now lives in `-specs`, so we can close this.
