### ISSUE TITLE
`maxDelay` is incorrectly scaled  - should be 10^6 times smaller 

### ISSUE THREAD

**Issue by njd42** [input-output-hk/ouroboros-network#2179]
I think that `maxDelay`  (https://github.com/input-output-hk/ouroboros-network/blob/be867b42cb75e3c1a837bdc3647f27021f7c8169/io-sim-classes/src/Control/Monad/Class/MonadTimer.hs#L130) is dimensioned incorrectly.

Isn't `fromIntegral $ maxBound :: Int` as a `DiffTime` that number of seconds - but the time units in IO are microseconds - this is a 10^6 too large!?

This would cause issues on 32bit machines - things would see negative delays, wake up early etc....

**Comment by njd42** [comment]
Actually, the more I look at this, the more I think that the 32bit Int case is not handled correctly in `newTimeout` - the same 32 bit issue exists in the `GHC.registerTimeout` interface as well

**Comment by mrBliss** [comment]
I think you're right, it should be:

```haskell
maxDelay = fromIntegral (maxBound :: Int) `div` 1_000_000
```
Thanks for catching this!
cc: @coot @kderme

**Comment by coot** [comment]
@njd42 you're right, `maxDelay` needs to be scaled as @mrBliss suggests.

**Comment by mrBliss** [comment]
Suggestion from @edsko: let's define an inverse of `diffTimeToMicrosecondsAsInt` and use that to compute the `maxDelay`. Also, a type signature on `go` and/or `maxDelay` might make things clearer.

**Comment by njd42** [comment]
BTW - this is not the only issue with use of 32 bit time in that module, I’ll talk with @coot later to highlight the other issues.

**Comment by coot** [comment]
> Also, a type signature on go and/or maxDelay might make things clearer.

Indeed, I had the same thought.  

We cannot use `div` since `DiffTime` is not integral so we should use `/` instead.  Having a test which confirms that the inverse does what we think it does would be good too.

**Comment by coot** [comment]
Fixed in #2181, other 32-bit related issues are tracked in #2184
