### ISSUE TITLE
Question-Help: I am trying to write a nodejs encoder for network CDDL specs for mini protocol

### ISSUE THREAD

**Issue by ashisherc** [input-output-hk/ouroboros-network#2180]
Hi Team,

I want to write an encoder and decoder for CDDL specs of mini protocols in Nodejs. I want to start with a simple pin pong protocol but unable to understand the format to encode the msg in. I have followed below Haskell source code but not able to figure out the format as I am not aware of Haskell.

I had a look at below Haskell code but no luck, https://github.com/input-output-hk/ouroboros-network/tree/master/ouroboros-network/src/Ouroboros/Network/Protocol/ChainSync

I am using this Nodejs package for encoding cbor, https://github.com/hildjj/node-cbor

I tried to encode below messages but cardano-node socket connections times out.
```
{
pingPongMessage: 0
}

"pingPongMessage 0"
```
------- More info --------

I am successfully able to make socket connection to cardano-node, the cardano-node timeout after sometime when I send any of the msg above. I am sending any of the above message after the connection, I am not sure if I need to send any other message before initiating a protocol.

I appreciate your response!

**Comment by ashisherc** [comment]
@coot can you help with this one?

**Comment by coot** [comment]
We don't use `PingPong` in `node-to-node` protocols (nor in `node-to-client`), but that's a good start for getting familiar with `ouroboros-network` :).  `PingPong` cbor codec is [here](https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-network-framework/test/Network/TypedProtocol/PingPong/Codec/CBOR.hs#L35) and it has something like this:

```
  encodeMsg (ClientAgency TokIdle) MsgPing = CBOR.encodeWord 0
  encodeMsg (ServerAgency TokBusy) MsgPong = CBOR.encodeWord 1
  encodeMsg (ClientAgency TokIdle) MsgDone = CBOR.encodeWord 2
```

You'd be interested in  `CBOR.encodeWord 0`, etc.  The node library must have a similar primitive to encode a `Word`.

Note that the codecs in `ouroboros-network` do not know all the details, e.g. we are [polymorphic]( https://en.wikipedia.org/wiki/Polymorphism_(computer_science)) (Haskell has parametric polymorphism) over blocks, headers or transactions which exact form is defined above us.

We will soon make the documentation public so it will be much easier for you to find all the details. I can send you a pdf by email (drop me an email to `marcin.szamotulski@iohk.io`, and I'll send it to you). 

> I am successfully able to make socket connection to cardano-node, the cardano-node timeout after sometime when I send any of the msg above. I am sending any of the above message after the connection, I am not sure if I need to send any other message before initiating a protocol

We first run `Handshake` protocol, then we start a multiplexer which has it's encapsulation. For node-to-node we multiplex three protocols: `chain-sync`, `block-fetch` and `chain-sync`.

**Comment by ashisherc** [comment]
Thank you for the response @coot, I have dropped you an email.
I will check with the node package for the word encoding and there are few things still unclear for me, but I will go through the document you are sharing and try to understand it further.

**Comment by ashisherc** [comment]
Hi @coot I could implement the encapsulation and able to handshake as well as use chain-sync ntc protocol.

I got into another issue regarding the size of the encapsulated packets. After receiving a rollBackward state, I did a requestNext to get a new block and I am receiving multiple messages on the socket, around 8-11 with varying packet size.

I can understand the size limit of the payload in the packet to 65535 bytes, hence I might be receiving multiple packets. I was trying to understand how to be aware of the last packet to be received so that I can combine all of them and decode the rollForward message.

Exploring the received packets, I am unable to put together a way to figure it out, I noticed first 2 packets had timestamp, mode, protocol id and payload length in it. With the payload length of only 12288, same with both the packets. And there are other 8-9 packets randomly without the header.

I also explored the source code at https://github.com/input-output-hk/ouroboros-network/blob/master/network-mux/src/Network/Mux/Bearer/Socket.hs

Which has Mx.sduSize = 12288 and sduTimeout, I am not sure if this is anything related to what I am trying to understand.

Can you please guide me in a proper direction?
