### ISSUE TITLE
Move Byron to Shelley translation functions to cardano-ledger-specs

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#2253]
Some of the translation functions in the [`Ouroboros.Consensus.Cardano.CanHardFork`](https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-consensus-cardano/src/Ouroboros/Consensus/Cardano/CanHardFork.hs) module belong in `cardano-ledger-specs`.

In particular: `translateUTxOByronToShelley` and parts of `translateLedgerStateByronToShelley`. Note that we can't use `initialShelleyState`, as that's for a `ChainState` (which roughly maps to the product of our `LedgerState` and `ConsensusState`) for which we don't have enough information. We only need to produce a `NewEpochState`.

These functions at least require careful review by the ledger-specs team.

**EDIT:** it would be good to have some properties about this translation. For example, for the UTxO, we can check whether any balance in the Byron UTxO matches the balance in the Shelley UTxO.

**Comment by mrBliss** [comment]
High priority applies to the reviewing of these functions by the ledger-specs team, not necessarily to the moving.

**Comment by edsko** [comment]
I think there is at least one bug in the translation. At the point of the translation, the Byron state might have some changes lined up to be applied at the next epoch boundary. It will never get a chance to apply those (because doing so could result in a Byron state that would have its major protocol version set to `2`, which is an invalid Byron state -- that should have been a Shelley state). This means that the translation function should take care of applying any of these pending updates, whichever ones are still relevant. _Crucially_, it should _at least_ apply the changes to the protocol state, otherwise the _Shelley_ ledger with end up with a protocol version of 1, which is equally invalid (alternatively, the translation could hardcode that version to 2).

**Comment by nc6** [comment]
Leave some comments here as I write:
```
translateLedgerStateByronToShelley
  :: forall sc. Crypto sc
  => LedgerConfig (ShelleyBlock sc)
  -> EpochNo
```

Which `EpochNo` is this? We do various things when we move to a new Shelley epoch - will they be triggered here?

**Comment by nc6** [comment]
```
    -- | NOTE: we ignore the Byron delegation map because the genesis and
    -- delegation verification keys are hashed using a different hashing
    -- scheme, Blake2b_224, whereas Shelley uses Blake2b_256. This means we
    -- can't simply convert them, as Byron nowhere stores the original
    -- verification keys.
    --
```

This is no longer true - Shelley also uses blake2b_224. But were these double hashed? This probably doesn't matter too much to leave it as it is.

**Comment by nc6** [comment]
Line 453: use `pparams`

**Comment by nc6** [comment]
> I think there is at least one bug in the translation. At the point of the translation, the Byron state might have some changes lined up to be applied at the next epoch boundary. It will never get a chance to apply those (because doing so could result in a Byron state that would have its major protocol version set to `2`, which is an invalid Byron state -- that should have been a Shelley state). This means that the translation function should take care of applying any of these pending updates, whichever ones are still relevant. _Crucially_, it should _at least_ apply the changes to the protocol state, otherwise the _Shelley_ ledger with end up with a protocol version of 1, which is equally invalid (alternatively, the translation could hardcode that version to 2).

We don't think this should be an issue, since we take the protocol params from the Shelley config. We could have a check that the versoin in the config corresponds to that expected by Byron.

**Comment by JaredCorduan** [comment]
note that the byron protocol version is a triple, but the shelley protocol version is a pair.

**Comment by nc6** [comment]
Jared and I just went over this together and, modulo the above comments, think it looks good.

**Comment by mrBliss** [comment]
> Leave some comments here as I write:
> 
> ```
> translateLedgerStateByronToShelley
>   :: forall sc. Crypto sc
>   => LedgerConfig (ShelleyBlock sc)
>   -> EpochNo
> ```
> 
> Which `EpochNo` is this? We do various things when we move to a new Shelley epoch - will they be triggered here?

This is the exact epoch at which Shelley starts. So I didn't think anything should be triggered on the Shelley side, or am I mistaken?


> ```
>     -- | NOTE: we ignore the Byron delegation map because the genesis and
>     -- delegation verification keys are hashed using a different hashing
>     -- scheme, Blake2b_224, whereas Shelley uses Blake2b_256. This means we
>     -- can't simply convert them, as Byron nowhere stores the original
>     -- verification keys.
>     --
> ```
> 
> This is no longer true - Shelley also uses blake2b_224. But were these double hashed? This probably doesn't matter too much to leave it as it is.

I see. But if we wanted to use the Byron ones, what about the [`genDelegVrfHash`](https://github.com/input-output-hk/cardano-ledger-specs/blob/515b73783ada98a7ede4b6b67ef39f0959a89571/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/Keys.hs#L271
)?

> Line 453: use `pparams`

Ah, yes, thanks.

> Jared and I just went over this together and, modulo the above comments, think it looks good.

Much appreciated!

**Comment by edsko** [comment]
> This is the exact epoch at which Shelley starts. So I didn't think anything should be triggered on the Shelley side, or am I mistaken?

The only thing that should have been scheduled Byron side is the delegation state, but that we can't make use of anyway, right? Is there anything else? There can't be anything scheduled Shelley side, because Shelley hasn't begun yet?

**Comment by mrBliss** [comment]
Bumping down to medium priority as the review has been done, now they only have to move to `cardan-ledger-specs`.

We'd still like answers for the following questions:

> > > [..]
> > This is no longer true - Shelley also uses blake2b_224. But were these double hashed? This probably doesn't matter too much to leave it as it is.
> 
> I see. But if we wanted to use the Byron ones, what about the [`genDelegVrfHash`](https://github.com/input-output-hk/cardano-ledger-specs/blob/515b73783ada98a7ede4b6b67ef39f0959a89571/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/Keys.hs#L271)?
> 

> > This is the exact epoch at which Shelley starts. So I didn't think anything should be triggered on the Shelley side, or am I mistaken?
> 
> The only thing that should have been scheduled Byron side is the delegation state, but that we can't make use of anyway, right? Is there anything else? There can't be anything scheduled Shelley side, because Shelley hasn't begun yet?
