### ISSUE TITLE
Connect CardanoBlock node to current mainnet

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#2256]
We should test the following: start a (cardano-)node running `CardanoBlock` from a non-empty database created by a node running `ByronBlock` and let it connect to other nodes running Byron to see whether it really is compatible.

We expect compatibility among two axes:
1. It must be able to read the blocks from disk. As the ledger database is *not* compatible, it will read *all* blocks from disk.
2. Network compatibility: it should be compatible with V1 of the NodeToNode protocol and V1/V2 of the NodeToClient protocol.

**Comment by edsko** [comment]
First point was addressed in #2385.
