### ISSUE TITLE
EpochInfo: Use ledger to figure out epoch lengths

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#226]
@nc6 says: The protocol version -> epoch length mapping at the moment is still being treated as a protocol parameter in the spec. https://github.com/input-output-hk/cardano-chain/issues/294 (bad title) pertains to changing this.

**Comment by edsko** [comment]
Removing the dependency of the chain DB on this, and moving this to the Praos milestone: epoch lengths won't vary until Shelley.

**Comment by edsko** [comment]
We already have an independent abstraction in place that records epoch lengths (`EpochInfo`).

**Comment by edsko** [comment]
As of #935, we now ask the ledger for the epoch size. We should however consider if the value of `k`, and/or the value of epoch size, will change over the hard fork. If so, we might have to think through the ramifications of that.

**Comment by edsko** [comment]
We need to confirm whether or not the epoch length can change (whether it's a votable parameter). If not, this ticket can be closed as it is subsumed by #1205; if however it can change over the course of Shelley, we need to really derive the epoch length from the ledger as opposed to from the node config.

@nc6 , @dcoutts , @JaredCorduan , any of you know?

**Comment by edsko** [comment]
Note that if this becomes a votable parameter this has consequences for some parts of consensus (for example, the imm DB). Not impossible to solve, but we'd have to rely on the fact that these votable parameters only become effective once they are stable on the chain (`> k`), otherwise things might get quite painful.

**Comment by mrBliss** [comment]
@dcoutts confirmed that the epoch length will be fixed per protocol
