### ISSUE TITLE
Remove MuxPeerRaw

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#2285]
Remove:

* [ ] `MuxPeerRaw`
* [ ] any direct usage of `runPeer` and `runPipelinedPeer` (in `ouroboros-consensus`)
* [ ] any direct usage of `runPeerWithLimits` and `runPiplinedPeerWithLimits` (in `ouroboros-consensus`)

This should allow us to hide `Channel` from `ouroboros-consensus`.

**Comment by mrBliss** [comment]
> This should allow us to hide `Channel` from `ouroboros-consensus`.

We use `Channel` explicitly in our consensus tests that simulate multiple nodes:
https://github.com/input-output-hk/ouroboros-network/blob/4fa690a1fbd7fee5bca8d57e1df7ee2345146289/ouroboros-consensus/ouroboros-consensus-test-infra/src/Test/ThreadNet/Network.hs#L1067
We will still be able to do this, right?

**Comment by coot** [comment]
You should move all  `App` types to use a [MuxPeer](https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-network-framework/src/Ouroboros/Network/Mux.hs#L96) or [MuxPeerPipelined](https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-network-framework/src/Ouroboros/Network/Mux.hs#L102) constructors.  It would work for tests, the question is if it is possible to use `MuxPeer` & `MuxPeerPipelined` in `Apps`?

**Comment by nfrisby** [comment]
I removed the consensus label. If this Issue gets reconsidered, please let us know what you'd need from us. cc @coot

**Comment by coot** [comment]
This issue should be closed.  We actually went in the opposite direction.

A large refactoring of the network API was done in #4462.
