### ISSUE TITLE
Protocol testing: test what happens when nodes join the network much later

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#231]
Again, a very important test because this is the one that will exercise the genesis chain selection rule.

**Comment by nfrisby** [comment]
Test comment.

**Comment by nfrisby** [comment]
(This comment needs to be here for me to be the assignee.)

**Comment by mrBliss** [comment]
@nfrisby You can ignore the "genesis chain selection rule" for now.

A possible approach is to replace the `NumCoreNodes` argument that these tests take with a more complicated type (still as simple as possible and easy to shrink!), that defines at which time (just the slot, see `onSlot`) each node joins the network (this can be the time the node starts up or the time the network connection between the node and the others is made). The next step is to set up the nodes and connections based on this type. Eventually, we can extend this type to account for network partitions and other "problems".

**Comment by nfrisby** [comment]
Just an update for the record: the draft PR #773 found a race condition and a bug in `newIterator`. Thomas addressed those with #810 and #812. I'm following up his work with a proper PR for this Issue.
