### ISSUE TITLE
Use `HeaderFields` in `Anchor`

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#2330]

**Comment by edsko** [comment]
We'd have to make the fields strict.

**Comment by edsko** [comment]
We should do either do https://github.com/input-output-hk/ouroboros-network/issues/2331 first or decide that we won't do it, as this would then affect what it in the anchor.

**Comment by mrBliss** [comment]
We are not going to do this, as `HeaderFields` is a lazy view on a header and `Anchor` is stored as state and should be strict.
