### ISSUE TITLE
Test Praos/genesis with explicit leader schedules

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#234]
In order to test whether things still work when we have no leaders in a slot, or more than one, we should have a way to specify the leader schedule explicitly. We already have a protocol combinator that makes this possible, so this has been done to some degree.

**Comment by edsko** [comment]
@nfrisby Do you think we can close this? Is there anything we should add here?

**Comment by nfrisby** [comment]
@edsko I think it's already done, yes. I think other Issues will involve refinements of the existing `LeaderSchedule` generator, but that shouldn't stop us from closing this one.

**Comment by edsko** [comment]
Perfect :)
