### ISSUE TITLE
Securely forget the signing key

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#2367]
https://github.com/input-output-hk/cardano-base/pull/140/ added `forgetSignKeyKES`, which we should now call in [`evolve`](https://github.com/input-output-hk/ouroboros-network/blob/6eedc521ba661030ea3204d38fd7f0f16c669d32/ouroboros-consensus-shelley/src/Ouroboros/Consensus/Shelley/Protocol/Crypto/HotKey.hs#L96-L98).

**Comment by edsko** [comment]
Plan:

1. stateful API to the key
2. should be localized to individual ledgers
3. block production should have that stateful key object in its closure
   (protocolInfo in .Cardano becomes monadic)
4. which means checkIsLeader needs access to it too
   (i.e., BlockProduction needs a leader check function, that will then 
   call to the pure one in the class with the info -- see 7)
5. at the moment, we _construct_ BlockProduction object (stateful) from
   ConsensusProtocol/CanForge
6. Instead, _require_ BlockProduction object as part of ProtocolInfo
   (sensible: if you are a leader, give a BlockProduction)
   [can this fix Thomas's problem? -- yes]
   -- CanForge as a class goes.
7. The (abstract) protocol checkIsLeader takes a ChainIndepStateInfo (name?);
   it will be the responsibility of the BlockProduction object to call it
   -- stick with the name ChainIndepState? (state derived from the private key
   is still state)
8. No more ForgeState/updateChainIndepState
9. Stateful KES wrapper offers 'sign' but no 'getPrivateKey'

```
OptNP BlockProduction xs -> BLockProduction (HardForkBlock)

data KESAPI m = KESAPI {
      evolve  :: Period .. -> m ()
    , getInfo :: KESInfo
    , sign    :: .. -> m Signature -- Signature in NF!
    }

newKESAPI :: m (KESAPI m)

type instance ChainIndepStateInfo (TPraos c) = KESInfo

data ProtocolInfo m b = ProtocolInfo {
        pInfoConfig      :: TopLevelConfig b
      , pInfoInitLedger  :: ExtLedgerState b -- ^ At genesis
      , pInfoLeaderCreds :: Maybe ( CanBeLeader (BlockProtocol b)
                                  , m (BlockProduction m)  -- monadic
                                  )
      }
```

**Comment by edsko** [comment]
Reducing to medium priority because we _could_ release without it, and improve this in a future update (without breaking any kind of compatibility). It would still be really good to have it included though, so leaving it assigned to the current milestone.

**Comment by mrBliss** [comment]
Done in #2418
