### ISSUE TITLE
Generalise Isomorphic to more than one era

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#2368]
Motivating examples: `Test.Consensus.Cardano.Examples` and `Test.Consensus.Cardano.Generators`.

**Comment by edsko** [comment]
Could we perhaps use this to lift the restrictions on `QueryAnyTime` / `QueryHradFork`?

**Comment by edsko** [comment]
Can then maybe also simplify `Test.Consensus.Cardano.ByronCompatibility`, and instead of giving instances per type, just give one instancefor the newtype wrapper `ByronToCardano` (and one instance in the other direction).
