### ISSUE TITLE
Remove `EpochSlot` and `RelativeSlot` from Immutable DB interface

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#241]
In the original design for the immutable DB, the DB was not aware of epoch sizes; since it did want to store blocks per epoch, its interface was in terms of `EpochSlot`s: a pair of an epoch and a relative slot index within the epoch. In later iterations however it turned out that the DB _did_ need to know the sizes of epochs. The current design is therefore a bit of a historical accident: the API is still in terms of `EpochSlot`s, even though the DB could do the translation from a `Slot` to an `EpochSlot` entirely internally.

This ticket is about changing that: the API will just be in terms of `Slot`s. This makes it more uniform also with the volatile store (which doesn't need to know anything about epochs), and it makes the decision to store files per epoch an internal detail.

**Comment by dcoutts** [comment]
Just in terms of slots, with the large files not being aligned to epoch boundaries is a good simplification.

I'd suggest picking a size that makes sense for the expected size of data, and avoid picking the current epoch length (21600) so as to avoid confusing people reading the code.

Note that the size we pick here has to work for both Ouroboros Classic and Praos, which have a 10x difference in slot occupancy. On the other hand we expect the average block size to grow in future.

**Comment by mrBliss** [comment]
Completed in #341.
