### ISSUE TITLE
Update network abstraction for header/body split

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#243]
In `Ouroboros.Consensus.Node` we define an abstraction over the network layer. That abstraction must be updated to reflect the header/body split. A full implementation of this would require us to also be able to implement validation for headers only (#244), but if we simply assume all headers are valid, we can skip that and implement the rest of the API here, and then tackle validation separately.

**Comment by mrBliss** [comment]
Fixed by #401.
