### ISSUE TITLE
Don't use so much Bash in nightly BuildKite slow ThreadNet tests script

### ISSUE THREAD

**Issue by nfrisby** [input-output-hk/ouroboros-network#2436]
I ended up with more Bash than originally anticipated in `./buildkite/slow-ThreadNet-tests.sh` in PR #2398 for Issue #2393. This Issue is to revisit that file, especially to consider rewriting it to a safer language.

I don't think this is urgent. In light of the script's role, we'll probably not suffer much as-is, until it comes time to significantly change its functionality. And that'll likely be the right time to attempt this Issue.

**Comment by dnadales** [comment]
We don't use BuildKite anymore, and that script is gone.
