### ISSUE TITLE
Header validation without corresponding bodies

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#244]
At the moment we are validating entire blocks at a time by simply applying them to the ledger state. Once we only have headers, we can no longer do that. This means that we'll need additional support from the ledger: it will need to be able to support validation "in the future".

**Comment by edsko** [comment]
Allowing more time here to define precisely what we need from the ledger layer to support block validation "in the future".

**Comment by mrBliss** [comment]
In #401, we added `HeaderState`and `advanceHeader` to validate headers, see a25c388e. Currently, we only have a mock implementation that doesn't actually validate the headers. We still need a real implementation.

**Comment by edsko** [comment]
We have the right abstractions in place. We don't yet test this in our property tests (created a separate ticket for that at #553). After we merge https://github.com/input-output-hk/ouroboros-network/pull/531 and close #191, we can close this as a separate ticket (provided that we verified that the demo playground still works after the integration, with the real ledger).

**Comment by edsko** [comment]
Verified that this works as expected in the demo.
