### ISSUE TITLE
Actually use on-disk storage

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#245]
After the various on-disk components have been implemented, we should change the consensus layer abstractions to actually _use_ them. 

While this _technically_ does not depend on the header/body split, that change is sufficiently large that there is no much point implementing this until that is done.

**Comment by edsko** [comment]
Allowing a lot time for this ticket, since it has consequences across the entire consensus layer.

**Comment by mrBliss** [comment]
Since the merge of #401, the on-disk components are used by the consensus layer, but only the mock implementations.

I'll keep this ticket open until the real implementations (the real `ChainDB`) are used by the consensus layer.

**Comment by edsko** [comment]
There isn't much to do in this ticket. As @mrBliss points out, it's a matter of swapping out the mock Chain DB for the real done; the external API is the same. So this is mostly a matter of testing that everything still works as expected.

**Comment by mrBliss** [comment]
See https://github.com/input-output-hk/ouroboros-network/pull/744 and https://github.com/input-output-hk/cardano-node/pull/52.
