### ISSUE TITLE
a place to see updated protocol cddl specs

### ISSUE THREAD

**Issue by ashisherc** [input-output-hk/ouroboros-network#2467]
The chain sync protocol find intersect is updated I guess which is not allowing me to find an intersect on 1.17.0 MC3. I wanted to have a look at the up to date chain sync protocol cddl specs.

**Comment by coot** [comment]
There was no change in the protocol, maybe the wallet guys changed the implementation of their `chain-sync` server.

**Comment by ashisherc** [comment]
It is because of the hard fork combinator, closing this issue as it is not related to the chain sync protocol but the ledger spec.
