### ISSUE TITLE
cryptonite v 0.25 uses libb2 with avx issue

### ISSUE THREAD

**Issue by bkohlhauff** [input-output-hk/ouroboros-network#2476]
There is an issue running cardano-node on CPUs without AVX support due to an underlying [bug](https://github.com/BLAKE2/libb2/commit/60ea749837362c226e8501718f505ab138e5c19d) in the blake2/libb2  library which is used by cryptonite and appears to have been fixed with the updated libb2 in [cryptonite v0.26 ](https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-consensus-byron/ouroboros-consensus-byron.cabal) can the project be updated to use 0.26 or newer of the cryptonite library?

**Comment by mrBliss** [comment]
It seems everything compiles with cryptonite 0.26 and 0.27 as well, so we can relax the constraint to `cryptonite >= 0.25 && <0.28`. (To compile with 0.27, #2445 is needed.)

**Comment by bkohlhauff** [comment]
Thanks for looking into this!
