### ISSUE TITLE
Keep older ledger snapshots

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#2479]
It is likely that we'll break the compatibility of the ledger snapshots of Shelley. This will require replaying the whole chain from genesis, including the entire Byron era.

If we were to keep older snapshots around, e.g., one every 50 epochs, then we could limit the required replay whenever we break the Shelley snapshots.

This will require a change in the snapshot policy, because we currently delete older snapshots. We'll have to remember not to delete some of them.

---

**UPDATE:** https://github.com/input-output-hk/ouroboros-network/pull/2733 already implements part of this issue: name snapshots after their slot number, allow named snapshots that won't be deleted, etc.

This issue is now only about making the snapshot policy more flexible.

It should also be possible to manually specify via the CLI of which slots to take snapshots. This means that we should also make snapshots during ledger replay.

**Comment by mrBliss** [comment]
Ideas:

* Instead of numbering snapshots, use the corresponding slot number as the name. That makes it much clearer of what it is a snapshot. Note that EBBs have the same slot number as the block after it. I think that's fine, as long as we just use the slot number as a name and never rely on it being the right slot number.

* Allow suffixing the snapshot with a name, in which case it will never be deleted (and excluded from the on-disk snapshot limit). For example `4492799.last_ByronBlock`. This would come in handy for node operators when the Shelley ledger format changes, it would avoid a replay from genesis. It would also be useful for testing/benchmarking/profiling.

**Comment by mrBliss** [comment]
More ideas:

* Allow for a linear number of snapshots in the length of the chain, e.g., one every `x` epochs`.

* Make a snapshot at the transition.

**Comment by mrBliss** [comment]
Relevant code:

* https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-consensus/src/Ouroboros/Consensus/Storage/LedgerDB/DiskPolicy.hs
* https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-consensus/src/Ouroboros/Consensus/Storage/LedgerDB/OnDisk.hs

**Comment by kderme** [comment]
I was wondering if we can tell the real slot of a disk snapshot in a fast way (preferably without having to parse the whole snapshot). I think this can be done, since we store a `ChainSummary` and not just a ledgerState, so by tweaking the CBOR parsers we could tell the slot by reading only a few bytes.

I think this will be useful since we want to know the slot of at least the most recent of the "old" snapshots. Another idea is when the background thread trims an old snapshot we can raname them from `slot` to `slot_old`. In order to decide if we want to keep it, we must be able to tell its real slot.

> Allow suffixing the snapshot with a name, in which case it will never be deleted

@mrBliss You mean add the suffix to an existing snapshot or create a new snapshot with the suffix?

**Comment by mrBliss** [comment]
> I was wondering if we can tell the real slot of a disk snapshot in a fast way (preferably without having to parse the whole snapshot). I think this can be done, since we store a `ChainSummary` and not just a ledgerState, so by tweaking the CBOR parsers we could tell the slot by reading only a few bytes.
> 
> I think this will be useful since we want to know the slot of at least the most recent of the "old" snapshots.

I don't think this is necessary. Currently, we number snapshots sequentially. We try them in descending order based on their names. I propose to use the slot of the snapshot as its name. That means they're still numbered sequentially and we can still try them in descending order.

This will work fine when there's a mix of old (non-slot) and new (slot) snapshots, we'll just try the newer ones first as the slot number are definitely bigger than the old non-slot numbers.

If the user changed the name of a snapshot manually, that's stupid and their problem. We'll just try them in a different order and might pick an older one, requiring more replay, while we could have used a newer one.

This means that when looking at snapshots and reading them, we don't care about their name and whether the slot number in the name matches the snapshot's real slot number. We only care about the ordering. So we don't have to extract "just the slot number" from a snapshot.

> Another idea is when the background thread trims an old snapshot we can raname them from `slot` to `slot_old`. In order to decide if we want to keep it, we must be able to tell its real slot.
>
> > Allow suffixing the snapshot with a name, in which case it will never be deleted
> 
> @mrBliss You mean add the suffix to an existing snapshot or create a new snapshot with the suffix?

I mean two things: (1) the user can manually add a suffix, e.g., `4492799.last_ByronBlock`, either by copying that snapshot to the folder `ledger` or renaming a snapshot in `ledger`. When we extend the policy to keep permanent snapshots, the LedgerDB will add that suffix.

BTW, the suffix is ignored when looking at the snapshots to read. It *is* taken into account when trimming them.

I suggest we start with the ideas in my first comment and then think about extending the policy.

**Comment by kderme** [comment]
An idea as an optional policy is to create a suffixed snapshot at a specified slot, ie the last slot before an epoch boundary. This could be very useful for debugging/benchmarking.
