### ISSUE TITLE
Keep `ChainState` bounded in size

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#248]
@brunjlar writes: "Growing without bound in memory. I'm keeping all BlockInfo's from the beginning of time. Instead, one only has to go back a fixed number of epochs."

**Comment by nc6** [comment]
Note that this pertains to the mock Praos implementation, not the Praos implementation based upon the Shelley ledger specs.

**Comment by edsko** [comment]
We can leave the mock implementation along, having the infinite buffer kind of as a spec. Closing.
