### ISSUE TITLE
initialChainSelection takes too long

### ISSUE THREAD

**Issue by kderme** [input-output-hk/ouroboros-network#2494]
Using the db-validator tool, I ran two experiments on part of the chain post hard-fork. In both cases the Imm db tip was 
```At (Block {blockPointSlot = SlotNo {unSlotNo = 4493500}, blockPointHash = 1236d7a62ed84e0c5bedcc8a47545f3f24026f7a144a51c12f60aa75490ee6b5})```

and the ledger snapshot was very close.

In the first the vol db is empty, while in the second there are 3 files (size in bytes):
6803992  blocks-4492.dat
3963152  blocks-4493.dat
  726766   blocks-4494.dat

The output with `time` in the first case was:
```
DB tip: At (Block {blockPointSlot = SlotNo {unSlotNo = 4493500}, blockPointHash = 1236d7a62ed84e0c5bedcc8a47545f3f24026f7a144a51c12f60aa75490ee6b5})

96.14user 2.76system 1:39.34elapsed 99%CPU (0avgtext+0avgdata 920356maxresident)k
9380336inputs+161576outputs (0major+461170minor)pagefaults 0swaps
```

while in the second
```
DB tip: At (Block {blockPointSlot = SlotNo {unSlotNo = 4536700}, blockPointHash = 1edc563f6d0d0b11174730e16050b8d82a6816813a70a3677d6cd2eec276a99f})

321.71user 3.83system 5:27.20elapsed 99%CPU (0avgtext+0avgdata 1420308maxresident)k
9608608inputs+96outputs (0major+588266minor)pagefaults 0swaps

```

Note 5:27.20 vs  1:39.34 with the majority of additional time spent on `initialChainSelection`.

**Comment by kderme** [comment]
Running the same from `cardano-node` I see the following logs:
```
[kostas-u:cardano.node.ChainDB:Info:5] [2020-08-03 12:40:33.92 UTC] Opened lgr db
[kostas-u:cardano.node.ChainDB:Info:5] [2020-08-03 12:42:38.73 UTC] Opened db with immutable tip at (Point 4493500, "1236d7a62ed84e0c5bedcc8a47545f3f24026f7a144a51c12f60aa75490ee6b5") and tip (Point 4536700, "1edc563f6d0d0b11174730e16050b8d82a6816813a70a3677d6cd2eec276a99f")
```

Note ~2 mins gap after the `Opened lgr db` log. (the time seems longer on the db-validator but maybe this is because of different ghc/rts flags).

Just before the hard fork the time is much smaller:
```
[kostas-u:cardano.node.ChainDB:Info:5] [2020-08-03 13:38:32.00 UTC] Opened lgr db
[kostas-u:cardano.node.ChainDB:Info:5] [2020-08-03 13:38:32.97 UTC] Opened db with immutable tip at (Point 4488438, "fe723a2e159f55fbc7b41e1892659ccf6775ee9ac42185749edf8b8023ce6cbd") and tip (Point 4490598, "5f6be24a2f9d0fccb240ac717748eae61f4ba72d862af1d0b6dcb742f7507771")
```

So we have
1s     for 2160 slots before the fork
125s for 43200 after

Big differences are of course expected but maybe there is room for optimizations.

**Comment by kderme** [comment]
This is probably the result of applyBlock being slow. It would be interesting to see what are the improvements after optimizations there.

**Comment by mrBliss** [comment]
Indeed, Edsko and I noticed this too.

While our profiling results indicated that a lot of time was spent in `fn_3 (indiv)`, which doesn't make much sense given [its definition](http://hackage.haskell.org/package/sop-core-0.5.0.0/docs/Data-SOP.html#v:fn_3), we also believe it is due to ledger validation.

After adding some `INLINE`s to `fn_3` and other functions, we got:
```
COST CENTRE                      MODULE                                               SRC                                                                   %time %alloc

tickThenApply                    Ouroboros.Consensus.Ledger.Abstract                  src/Ouroboros/Consensus/Ledger/Abstract.hs:(88,1)-(90,60)              70.6   68.7
compute                          Control.Iterate.SetAlgebraInternal                   src/Control/Iterate/SetAlgebraInternal.hs:(976,1)-(1076,33)            14.2   17.3
liftSTS                          Control.State.Transition.Extended                    src/Control/State/Transition/Extended.hs:259:1-30                       6.0    4.0
provideBoth                      Ouroboros.Consensus.HardFork.Combinator.Util.InPairs src/Ouroboros/Consensus/HardFork/Combinator/Util/InPairs.hs:102:7-17    1.8    0.5
parseCanonicalJSON               Text.JSON.Canonical.Parse                            Text/JSON/Canonical/Parse.hs:(118,1)-(119,37)                           0.3    1.0
fromCompactTxId                  Cardano.Chain.UTxO.Compact                           src/Cardano/Chain/UTxO/Compact.hs:(175,1)-(176,62)                      0.2    2.0
fromCompactRedeemVerificationKey Cardano.Crypto.Signing.Redeem.Compact                src/Cardano/Crypto/Signing/Redeem/Compact.hs:(77,1)-(82,46)             0.1    1.4
```

There's not much consensus can do about it, it's a concern for the ledger, and they're already more than aware of [this](https://github.com/input-output-hk/cardano-ledger-specs/issues/1750). Closing.
