### ISSUE TITLE
Run tests with real real blocks

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#250]
Even after we test with the abstract blocks that the executable spec uses (#238), we should also test with the real real blocks that we expect will be used in the actual code. There are a number of ways we could do this:

* Write a generator for real real blocks. 
* Alternatively, we could use the generator for abstract/real blocks, and then use a translation abstract/real -> real real, but since the generator for abstract/real blocks takes an abstract state as input, we'd need a way to update the abstract state from a concrete state, or translate the realreal state into the abstract/real state. 
* Use the generator for abstract/real blocks, but generate all blocks up front. 

The final option is not too appealing: it requires a bird's-eye view of the system which doesn't really fit very nicely into the consensus layer (we started with that but moved away from it pretty quickly).

**Comment by edsko** [comment]
Allowing time here since the right approach is not yet clear.

**Comment by mrBliss** [comment]
See #855
