### ISSUE TITLE
Export constructors of TraceKeepAliveClient

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#2516]

**Comment by coot** [comment]
@karknu do we need to export `TraceKeepAliveClient` constructors? If this is only used to for measurements rather than logging then thay can stay internal.

**Comment by karknu** [comment]
I don't know, I think you created this issue due to some "structured logging".

**Comment by coot** [comment]
Is it worth do turn this into a logger?

**Comment by karknu** [comment]
It is a tracer, and we definitely need one.

**Comment by karknu** [comment]
Implemented in #2618
