### ISSUE TITLE
Volatile DB: Extend q-s-m tests to test reopening

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#252]

**Comment by kderme** [comment]
When db closes, the Internal State remains completely empty, so reOpen needs to parse all blocks from scratch and create in-memory indexes. pr https://github.com/input-output-hk/ouroboros-network/pull/163 introduced this functionality already.  Also q-s-m tests already use reOpening.

**Comment by edsko** [comment]
So we can close this?

**Comment by kderme** [comment]
I think yes

**Comment by edsko** [comment]
Ok, added a comment to #273 that we shouldn't forget about the close-corrupt-open case.
