### ISSUE TITLE
On chain root peers 

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#2535]
The peer governor needs to sample peers from the pools registered on the chain. We would like to sample them according to stake distribution.  

The governor has a method for getting root peers (using `IO`) which we can construct provided a list of `DomainAddress ~ (DNS, PortNumber)`.   Giving us something like `m [DomainAddress]` should work just fine.

The governor asks for root peers with an exponential backoff in case of failures, ensuring that it is not done too often.

**Comment by mrBliss** [comment]
The consensus-side of this has been done in https://github.com/input-output-hk/ouroboros-network/pull/2536, removing the `consensus` label now.

**Comment by karknu** [comment]
This is done.
