### ISSUE TITLE
Outbound Governor CI test failures

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#2552]
* [x] https://hydra.iohk.io/build/3933045/nixlog/6 (not repdocusible anymore)
* [x] https://hydra.iohk.io/build/3933046/nixlog/1 (it's the same test & quickcheck replay seed as above)
* [x] https://hydra.iohk.io/build/5210638/nixlog/27 (there are no errors in this log)

Discovered in #2539.

**Comment by bolt12** [comment]
I can't reproduce this in latest `master`

**Comment by coot** [comment]
closing, since it's not reproducible any more.
