### ISSUE TITLE
Debug VRFLeaderValueTooBig in nightly RealTPraos tests

### ISSUE THREAD

**Issue by nfrisby** [input-output-hk/ouroboros-network#2558]
As I began investigating #2557, I noticed that the recent `master` (1b0a57ce0) is frequently failing with:

```
MiniProtocolFatalException
  { mpfeType = ChainSyncClientException
  , mpfeExn = HeaderError
      (At (Block {blockPointSlot = SlotNo 317, blockPointHash = ...}))
           (HeaderProtocolError (ChainTransitionError [OverlayFailure (VRFLeaderValueTooBig (OutputVRF {getOutputVRFBytes = ...})
               (0 % 1)
               (ActiveSlotCoeff {unActiveSlotVal = UnsafeUnitInterval (1 % 2), unActiveSlotLog = -6931471805599453094172321354910343
...
```

I ~think~ anticipate that this is a long-standing problem that was masked by a bug in the test infrastructure until PR #2548 removed it. Summary: we were catching-and-restarting on any CS client error instead of failing fatally as above because our logic for distinguishing CS client exceptions was too coarse. PR 2548 changed it so that we only restart when the CS client returns cleanly, not via exception: now all exceptions are fatal. Hence we see this one.

**Comment by mrBliss** [comment]
`VRFLeaderValueTooBig` is not a good sign :cold_sweat:. The 1.18.1 release of node was pulled because of it.

**Comment by nfrisby** [comment]
I think Issue 2559 mostly supplants this one. However, there are some loose ends for this one to track. Principally: how much (relative) attention should we allocate to stake pools ending up with 0 relative stake?

I asked the #ouroboros-prototyping Slack here: https://input-output-rnd.slack.com/archives/GCW2S19CM/p1598820929004300

In particular, I anticipate that 0 stake is relevant to Issue #2557 --- either 0 stake is uninteresting or we should refine the test infra to properly handle it.

**Comment by nfrisby** [comment]
Closing in favor of #2568.
