### ISSUE TITLE
Governor can get stuck trying to forget peers.

### ISSUE THREAD

**Issue by karknu** [input-output-hk/ouroboros-network#2569]
The problem is caused by the way that number of known peers is tracked.
`north-america.relays-new.cardano-mainnet.iohk.io` is not counted at one peer, it is counted as one known peer per ip address (which is 8 ). The governor is configured to know about 5 peers by default, so it is constantly trying to forget peers.

**Comment by coot** [comment]
I saw this behaviour again today.

**Comment by coot** [comment]
This is fixed; the reason for that bug was that the policy returned an empty list, while it is supposed to pick at least one peer.
