### ISSUE TITLE
Workaround the crucial tx + full mempool + blocked forge scenario

### ISSUE THREAD

**Issue by nfrisby** [input-output-hk/ouroboros-network#2581]
This error was first seen in https://buildkite.com/input-output-hk/ouroboros-network-nightly/builds/220#6223fd68-d16b-4dc4-b4ad-3f652711e36a -- it's the `insufficient growth` error in RealTPraos. (The other is Issue 2506 again, whose fix is currently under review.)

PR #2543 changed the timing of the ledger access, which made block forging "faster", which meant that a node's crucial tx for a slot it leads would not necessarily be included in the block it forged. So PR 2543 also introduce explicit synchronization so that the node won't forge until the crucial transaction had entered the mempool.

This new failure is due to the mempool becoming full, so the `addTxs` for the crucial transaction blocks for multiple slots, and that in turn blocks the forge. This adds a "message delay" that the sensitive ThreadNet properties currently identify as an unexpected slow down in the chain growth (eg it sees that node 1 lead slot 446, but the corresponding new block didn't arrive until slot 460.)

This Issue is Done once we prevent this scenario from causing test failures.

**Comment by nfrisby** [comment]
Commit e1fda312c193c843d7b05a4deeb3d41618edd6f8 with `RealTPraos`:

The crucial transaction is the parameter protocol update arising from `setupD /= setupD2`.

```
repro :: TestSetup
repro = TestSetup
   { setupD = DecentralizationParam (2 / 5)
   , setupD2 = DecentralizationParam (1 / 5)
   , setupInitialNonce = Nonce (fromString "1f07d66d23b47096914bf4d5597f751611f8ed7bd9026743b38b345949f3787b")
   , setupK = SecurityParam 10
   , setupTestConfig = TestConfig
     { initSeed = Seed 5064858139403606719
     , nodeTopology = NodeTopology (Map.fromList [(CoreNodeId 0,Set.fromList []),(CoreNodeId 1,Set.fromList [CoreNodeId 0]),(CoreNodeId 2,Set.fromList [CoreNodeId 1]),(CoreNodeId 3,Set.fromList [CoreNodeId 0,CoreNodeId 1,CoreNodeId 2]),(CoreNodeId 4,Set.fromList [CoreNodeId 0,CoreNodeId 1,CoreNodeId 3])])
     , numCoreNodes = NumCoreNodes 5
     , numSlots = NumSlots 481
     }
   , setupVersion = (NodeToNodeV_1,Shelley.ShelleyNodeToNodeVersion1)
   }
```

**Comment by mrBliss** [comment]
A few thoughts:
* `addTxs` will block when the Mempool is full, but there is also [`tryAddTxs`](https://github.com/input-output-hk/ouroboros-network/blob/d81d370008727ac9811bbc4fc70ea0cbcde7cd28/ouroboros-consensus/src/Ouroboros/Consensus/Mempool/API.hs#L120-L123) which *does not* block. Using this would prevent blocking when adding the crucial transactions, but the result would be that the crucial transaction didn't make it into the Mempool. Or do we know that the Mempool already contains the crucial transaction in question?
* Not really a fix, but something that will also be beneficial for performance: when I last profiled the RealTPraos ThreadNet tests, `genTx` wall *the* hotspot. Maybe we can lower the number of transactions to generate? This is not a proper fix, of course, because the Mempool might still get full.

**Comment by nfrisby** [comment]
Yeah, `tryAddTxs` would unblock us. But the main semantics of the _crucial transaction_ abstraction suggests we shouldn't move on until they've been added or rejected.

We use crucial transactions for a few things:

  - RealPBFT: update the deleg cert when rekeying a node. This happens in whatever slot the node is scheduled to rekey. The mempool might be full by then.

  - RealPBFT: add the protocol version update proposal in the first epoch. The mempool probably is not full yet.

  - RealTPraos: we use them to update the `d` parameter in the first epoch. The mempool is probably not full yet.

  - Cardano: we use them to initiate the hard fork in the first epoch. The mempool is probably not full yet.

The above sentences about whether the mempool is full or not are considering the _first_ time the crucial transaction arises. However, the wrinkle is that once a crucial transaction is specified, the node attempts to add it to the mempool on _every_ subsequent slot. This was necessary because it's possible for the mempool to get flushed into an ultimately invalid block, which means the _crucial_ transaction (eg a Byron redeleg cert) might not end up on the chain. Therefore the node just continually adds it crucial txs for the rest of the test. If it's already in the mempool/on the chain, it should be rejected as a duplicate/stale (for Byron) or invalid (for Shelley, since its input has already been consumed). But apparently (see the failure that lead to this ticket eg) this _rejection_ is blocked if the mempool is full.

This is all to say that I think we could avoid this issue by enriching the test infrastructure to explicitly detect when a crucial transaction makes it onto the immutable chain and then drop that transaction from the set of crucial-transactions-that-need-to-be-constantly-added-to-the-mempool. But that sounds difficult/expensive to implement and maintain.

**Comment by mrBliss** [comment]
This reminds me of https://jira.iohk.io/browse/ADP-412, i.e., the ability to ask the Mempool whether a transaction is valid or not without *adding* it to the Mempool (ignore the "explain clearly why it's invalid" part, that's for the ledger). Do you think implementing that (which we will have to do anyway and will be simple), would be enough?

**Comment by nfrisby** [comment]
This nightly https://buildkite.com/input-output-hk/ouroboros-network-nightly/builds/223#d2dae7ac-3c98-47a4-9a2c-b4b88a148ac6 also failed with `insufficient growth`. It has the transaction, and it fails after hundreds of slots, so I suspect it is the same issue. (Moreover, I'm not seeing how the reported leader schedule would otherwise explain the error.)

> Do you think implementing that (which we will have to do anyway and will be simple), would be enough?

@mrBliss, it seems like a step in the right direction. I think the ideal behavior is that the node should stop trying to add the transaction at every slot onset once it knows it will _never_ be valid again. For example, IIUC, that's true if the transaction is already on the immutable chain. And I think that should work for these RealTPraos errors we're seeing.

But I'm not certain that all crucial transactions (eg redelegation certificates in RealPBFT/Byron tests) can assume their validity wrt to the mutable current chain begins as "valid" and only transitions once, to "invalid" --- I believe it may waver back and forth or at least start as "invalid". I'll have to allocate some time to confirm that, but that's my recollection.

**Comment by nfrisby** [comment]
Also https://buildkite.com/input-output-hk/ouroboros-network-nightly/builds/235#f5b3c2be-0468-4594-b290-14476fc366e6 I think.
