### ISSUE TITLE
Avoid repeated expensive tick of the ledger during block production

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#2590]
Some times ticking the ledger during block production takes more than one slot length (= 1s), e.g., when computing the [reward update](https://github.com/input-output-hk/cardano-ledger-specs/blob/dda669e7d935b019e1ee5ae7237bd9d4954ebd50/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/LedgerState.hs#L916). This can cause us to miss our scheduled slot because we never check leadership for the slots in which we were still doing the leadership check of the first slot. Because this expensive "tick" must be repeated until we adopt the next block, we can miss more and more slots.

To solve this, we should *cache the ticked ledger* in the block production thread. The next leadership check, we can just tick the cached ticked ledger. This works because ticking a ledger from slot `X` to slot `X + 1` and then ticking that ledger to slot `X + 2` is the same ticking the ledger from slot `X` to slot `X + 2`. This means that we only do the expensive tick one, the subsequent ticks are cheap again, as they don't have to recompute the reward update, it's already in the ticked ledger. When we adopt a block and the current ledger changes, the cached ticked ledger cannot be used and we must tick the new current ledger instead.

**Comment by mrBliss** [comment]
Spanner in the works: we'll need a way to tick an already ticked ledger to another slot (> the previous one). We currently have no way to do this because we cannot go from a ticked ledger to an unticked one, except by applying a block/transaction.

I'm not sure whether we want to reintroduce a `Ticked l -> l` method. Alternatively, we add a new method to the `IsLedger` class (in addition to `applyChainTick`), something like `retick :: LedgerCfg l -> SlotNo -> Ticked l -> Ticked l`.

**Comment by mrBliss** [comment]
I think we can do the same thing in the Mempool.

**Comment by edsko** [comment]
Actually, the mempool _already_ doesn't tick repeatedly, as it keeps the (ticked) ledger state after the transactions around.

**Comment by edsko** [comment]
Idea: use the ticked ledger state from the mempool to do the leadership check (by ticking it "further" to the current slot). This would avoid a "fresh tick" in all cases _except_ when we _are_ actually a leader (since when we construct a block, we need a fresh ledger state that doesn't have any txs applied yet). This should significantly reduce the number of times we need to tick.

**Comment by edsko** [comment]
(This would depend two properties: the ledger view and the chain dep state are not unaffected by applying transactions.)

**Comment by mrBliss** [comment]
We found a simpler fix in #2642.

The concept of incremental ticking could nonetheless be useful in the future to avoid repeating the same expensive tick in contexts other than block production, e.g., Mempool or chain selection (the latter would be rather complicated, though).
