### ISSUE TITLE
Make the Mempool pure

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#2591]
We designed the Mempool with a monadic API, but it has now become clear that the Mempool could just be a pure value stored in a `TVar`. This will simplify its implementation and will make it easier to test.

**Comment by nfrisby** [comment]
We're going to wait on this one until we have a better picture regarding the new mempool behaviors regarding "two phase  validation" for Alonzo transactions; we anticipate probable conflicts (though mostly syntactic).
