### ISSUE TITLE
Support lightweight delegation certificates

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#262]
Lightweight delegation certificates  (aka "operational keys" or some such?) record

* Public KES key
* Starting day of the certificate (keys are evolved once per day, and have a validaity of 90 days)
* Signature (produced using an offline private key)

We must support this from two directions:

* When _verifying_ blocks we need to be take these certificates into account
* When _producing_  blocks we need to construct these certificates. Note that the private KES key must be provided externally, since the private master key is kept offline.

See the delegation specification at https://github.com/input-output-hk/fm-ledger-rules/tree/master/docs/delegation_design_spec

**Comment by edsko** [comment]
Similar comment as https://github.com/input-output-hk/ouroboros-network/issues/199#issuecomment-495527275 here.

**Comment by edsko** [comment]
@nc6 do we need to keep this ticket open, or does #982 subsume it?

**Comment by mrBliss** [comment]
Talk to Matthias Benkort about the Haskell implementation of KES and PRF.

**Comment by mrBliss** [comment]
Done in #1695. We still need to check them during chain selection, see #1877.
