### ISSUE TITLE
Rethink division of work between consensus layer and ledger layer

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#263]
At the moment, the division of work is a bit ad-hoc and moreover not uniform across Permissive BFT and Praos:

* For Permissive BFT the consensus validation is specified in the chain spec, and the implementation in the consensus layer merely calls the executable spec.
* For Praos the protocol validation is implemented entirely in the consensus layer and the specification does not mention it at all.

/cc @nc6

**Comment by edsko** [comment]
Closing this; responsibilities are now clear for PermBFT. For Praos the exact details can be figured out, but it will follow the same structure. @nc6 may have a bit more to say here.

**Comment by nc6** [comment]
Now both permissive BFT and Praos are defined in the consensus layer. The specifications for Byron and Shelley eras do define the _chain extension_ rules for PBFT and Praos respectively, but not chain selection.

The executable specs for Byron and Shelley may additionally implement the chain extension rules for PBFT and Praos for testing purposes, but this is not high priority (and we would need to work out how to do equivalence testing)
