### ISSUE TITLE
Chain Sync Client: Handle rollback due to disk corruption

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#264]
On startup we need to sync the chain and ledger of the node with its peers; similarly, when the chain gets truncated for some reason (for instance, #242), we need to resync to catch up again.

**Comment by edsko** [comment]
I don't know that there is much to do in the chain DB _itself_ here; it doesn't really understand much about syncing. When we boot up the node, we will figure out where we are and that will be the new tip; when we discover some disk corruption, we'll roll back, readers will be updated, and that will be that.

That said, leaving this ticket open because this _does_ affect some other parts of the system. In particular, if we rollback due to disk failure, the `ChainSyncClient` must make sure that it will start downloading older blocks. Related: #465.

**Comment by mrBliss** [comment]
The current plan is to simply shut down the whole node when disk corruption is encountered. So no explicit rollback is needed for the Chain Sync Client.
