### ISSUE TITLE
Implement mempool

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#265]
The basic interface between the mempool and the network layer is the network
layer informing the consensus layer "here are some transactions that other
nodes forwarded to us, which ones of these are you interested in?". The 
transactions that the consensus layer deems interesting it should add to its
mempool, and the network layer will hold on to those to forward to other
nodes (in other words, the network layer will maintain its own "forwarding 
pool" as separate from the mempool).

The consensus layer should do some basic validation of these transactions, so
that we don't unnecessarily forward invalid transactions. However, the cost
of this validation should be low; in particular, it is _not_ a goal to have the
mempool internally consistent at all times. 

It is however not entirely clear what we _should_ enforce:

1. If we don't enforce anything (apart from maybe signatures etc), we might
   be subject to DoS attacks. 
2. We could enforce that transactions must be valid wrt to the node's current
   UTxO. This is a relatively cheap check, _but_ it rules out dependent 
   transactions. This might be too much of a limitation.
3. We could require that the mempool is _as a set_ consistent wrt to the node's
   UTxO (full consistency). This is expensive, however.

Transactions marked as "not-valid-before" a certain slot add an additional 
complication here; they simply _cannot_ be validated (apart from signatures),
and so it's not clear how we can protect against DoS attacks for those.

When producing a block, the node needs to look at the mempool and decide which
transactions to include. This can be supported by the ledger layer, but here
again we have two options:

* Split the mempool into the set of transactions we can include, the set of
  transactions that are /definitely/ invalid, and the set of transactions that
  are not yet valid but may become valid later.
* Split the mempool into the set of transactions that we can include and 
  everything else.

Note that it is hard to make a distinction between an invalid transaction 
(that uses an input that has already been used) and one that is not _yet_ valid
(uses an input that is the output of a transaction that we have not yet seen):
in both cases we see a transaction with an input that is not available in the
UTxO.

When we apply a block (one that we produced ourselves, or one that we get
from another node), transactions in the mempool with inputs that are used in
the block are now definitely invalid and can be purged. Other purging depends
on what kind of invariant we choose for the mempool.

No matter what kind of invariant we choose, _pruning_ the mempool (after 
producing or applying a block) should ideally be cheaper than checking validity
of incoming transactions, since some validation should already have been done.

Special care must be taken with scripts, once they are supported; part of the
script can be validated without running the script, but for a full validation
the script must be run. This is of course an expensive operation. These details
however can be worked out when support for scripts gets added.

**Comment by edsko** [comment]
After discussing this with @kantp and @dcoutts , we have come to the following tentative conclusions:

* The mempool becomes a _ordered list_ of transactions, rather than a set.
* The mempool will have its own ledger state `S_m`, as distinct from the ledger state maintained by the consensus layer `S_c`. When the mempool is empty, `S_m = S_c`, but whenever a transaction is added to the mempool, `S_m` is updated with that transaction. _When this fails, the transaction is rejected as invalid_. This means we need a ledger layer operation
```haskell
updateForTx :: Tx -> LedgerState -> LedgerState
```
* This keeps checking incoming transactions for validity relatively cheap, at the cost of accepting/rejecting a transaction becoming non-deterministic and subject to network behaviour.
* When we apply a block, we walk over the list of transactions in the mempool _in order_, starting with the now updated `S_c'`, updating the ledger state as we go, evicting any transactions that have become invalid. 
* In principle we could amortize this (there is no need to evict transactions after every block that is applied) but at the cost of more code complexity and a more difficult to state invariant; we will not currently do this.
* However, since all of these transactions have already been validated once, there should be no need to re-check everything; for example, signature checks can be omitted. We therefore need a second operation from the ledger layer
```
haskell
updateForPreviouslyValidatedTx :: Tx -> LedgerState -> LedgerState
```
which would be able to skip certain checks.
* When the node _produces_ a block, we need to walk over the list once more to figure out which transactions are still valid. The only reason currently that this is necessary is that transactions can have a `not-valid-after` field set, and the deadline might have passed by the time we get to produce the block.

In the first release scripts will not be supported, but when they do, this causes some additional complications, that will also require some additional functionality from the ledger layer. For now we don't need to worry about this overly, but they include:

* To make scripts entirely deterministic they can have a `not-valid-before` field also. This field should be ignored when adding the transaction to the mempool, but taken into account when producing a block.
* Full validation of a script involves _running_ the script to check if the inputs cover the gas required by the script. Like the `not-valid-before` check, this should only be done when producing the block, because this is a possibly expensive check. Note that the script will be included whether or not the check succeeds: if the check is okay, everything is fine, but if the check fails, the transaction is nonetheless included in the blockchain as a failed script and the gas input is consumed regardless.

**Comment by nc6** [comment]
Are transactions the only thing that can live in the mempool? What about update proposals or delegations? We should aim to be consistent across these.

We may well reject a transaction as invalid that could subsequently become valid. What do we do with these, if they are evicted once seen as invalid?

**Comment by nc6** [comment]
One option is that the ledger layer can easily expose the _reason_ why things fail, and this could be classified into the categories you suggest above - "invalid apparent", "invalid presumptive", "valid"...

**Comment by edsko** [comment]
> We may well reject a transaction as invalid that could subsequently become valid. What do we do with these, if they are evicted once seen as invalid?

Right, so these are just rejected, this is very much a consequence of the above policy. Such transactions must be resubmitted by whoever submitted them. 

> Are transactions the only thing that can live in the mempool? What about update proposals or delegations? We should aim to be consistent across these.

I've been wondering about this too. I've been loosely thinking of all of these as transactions. Not sure. @dcoutts ?

**Comment by kantp** [comment]
Delegation certificates will be submitted as parts of transactions, so they are automatically covered by this. I _think_ the same should be true for update proposals as well, but I am less certain there.

**Comment by dcoutts** [comment]
I think we can consider all of these things in the same way. Transactions, update proposals, votes, and in the byron era also delegation certs.

And yes, we cannot allow things that look invalid now but might become valid later. That opens us up to DoS attacks.

**Comment by dcoutts** [comment]
> Delegation certificates will be submitted as parts of transactions, so they are automatically covered by this.
That's true for Shelley, not for Byron.

> I think the same should be true for update proposals as well, but I am less certain there.
Those are still separate, not part of Txs. (same for votes on proposals)

**Comment by edsko** [comment]
@nc6 what exactly is the ledger API here? Is there some sort of "transaction like thingy" concept? A datatype that we can consider the mempool to contain? Do we need to write our own wrapper, and call specific ledger functions?

**Comment by nc6** [comment]
I think we may well want to create such a thing. At the moment there are just individual transitions for the various components. Though the recent discussion on delegation certificates may render that one moot.

**Comment by edsko** [comment]
WIP PR at #534 .

**Comment by edsko** [comment]
This is done. We can close this after we test that it works with the new ledger integration, provided we test the demo.
