### ISSUE TITLE
Write chainSyncServer that uses on-disk storage

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#266]
The current `chainSyncServer`/`ChainProducerState` assume everything lives in memory. This would need to be updated when we store stuff on-disk. 

It's possible that this can piggy-back on the work that @avieth is doing on the proxy.

**Comment by mrBliss** [comment]
Fixed by #401, in particular 5038f9867750d3d5883c9001e3e2c411b644aada.
