### ISSUE TITLE
Ongoing: integrate features implemented elsewhere into standalone node

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#267]
This goes for advances in the network layer, ledger layer, consensus protocol layer, node shell, etc.

**Comment by edsko** [comment]
No time estimate: this will be an ongoing task updating the demo with features developed elsewhere.

**Comment by mrBliss** [comment]
This effort is centralised in the [cardano-node](https://github.com/input-output-hk/cardano-node/) repository.
