### ISSUE TITLE
Support trace event emission from within STM in `io-sim`

### ISSUE THREAD

**Issue by nfrisby** [input-output-hk/ouroboros-network#2725]
This feature can aid in debugging when a transaction is triggering `retry` more or less often than expected.

Right now, only `Debug.Trace.trace` etc can be used. But if `io-sim` provided an interface to allow `MonadSay` and/or similar within an `STM m` computation, then the ultimate `Trace` could contain both the emitted message and also the surrounding events (eg which `TVar`s changed to incur the latest evaluation of the transaction).

EG I recall times where I needed to print the "fingerprint" portion of a transaction in order to determine why it was not finishing as often as I had expected. I think this would have helped with that.

The class instances for `STM IO` could be either no-ops or `TypeError`s.

`String` is the minimum viable argument, but `Dynamic` might also make sense (cf `Say` and `Output` from `io-sim:SimA`).

**Comment by nfrisby** [comment]
@mrBliss and I discussed the motivation for this on PR #2387.

I came up with three motivators for `traceSTM :: Dynamic -> io-sim:STM`.

   * single-event-stream. I want to limit the number of factors that influence the order of events I see when eg debugging. With `saySTM` and `traceSTM`, the order will be determined by the `io-sim` scheduler (in turn: the program's internal synchronizing etc) and nothing else.
   
  * post-processable. I may want to post-process the event stream instead of viewing the full events. For example, I could ask "how many times had this transaction called `retry` before the timeout fired?" Or a `QuickCheck.counterexample` could report the state within an STM transaction (ie which of several `STM.check` calls is it blocked on, or even what is the latest value it had read from some `TVar`, etc).
 
  * even-despite-exceptions. I may want to include the result of post-processing in a `QuickCheck.counterexample` call for a failure that was triggered by an exception. (EG Maybe I'm debugging what appears to be a divergent loop and I introduce a `timeout` exception in order to reveal some state within the loop).

**Comment by mrBliss** [comment]
As @nfrisby said: this is not about making it possible to trace from `STM m`, but only to trace from the IO simulator's `STM` monad (see the three motivators). In particular, the goal is *not* to make it possible to trace from the real `STM` monad.

When you find yourself needing to trace from within a real (non-test) `STM` transaction, there are (at least) two alternatives:

1. Let the transaction return the trace message(s), which can then be traced after the transaction succeeded by a regular tracer.
2. Let the transaction return a monadic computation that does the regular tracing, which can then be executed after the transaction succeeded. Using `join` in `join $ atomically $ .. traceWith ..` is a well-known trick in combination with STM.

If you're debugging something in an STM transaction, you could consider *temporarily* using `Debug.Trace.traceM`.

**Comment by coot** [comment]
We also have now `MonadTraceSTM` which allows to track committed values of `TVar`'s, see #3609.
