### ISSUE TITLE
Volatile DB: Check against simulated errors 

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#273]

**Comment by kderme** [comment]
@edsko What I need to check for this is whether after a simulated error, the state of the db remains consistent?

**Comment by edsko** [comment]
In terms of the model (key-value mapping): the model after the corruption should be a subset of the model before.

**Comment by edsko** [comment]
This should include the case where some data gets corrupted after DB closing, so that we recover from this in a suitable way during reopening.

**Comment by kderme** [comment]
A pr for a part of this issue is ready. The other part is blocked due to some refactoring in the simulated errors SimErrorFS, so I park this issue for now.
