### ISSUE TITLE
Implement PermBFT in terms of "real" implementation

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#274]
The first integration (#168) is in terms of the executable spec, which is not intended for production use.

**Comment by edsko** [comment]
Note on time estimate: allowing a bit of time here despite the previous integration, since the "real" implementation uses a different software stack as the executable spec.

**Comment by nc6** [comment]
https://github.com/input-output-hk/ouroboros-network/pull/409

**Comment by edsko** [comment]
Closing this as done; PR will be merged soon. Chain selection must still be done, but we have a separate ticket for that (#422).
