### ISSUE TITLE
Correctly deal with partial reads and writes

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#277]
Libc's `read` and `write`, used for the `IO` implementation of `HasFS` are not guaranteed to read/write all the requested bytes:

> The return value is the number of bytes actually written. This may be size, but can always be smaller. Your program should always call write in a loop, iterating until all the data is written. 

See the [discussion on HN](https://news.ycombinator.com/item?id=19119991).

Just like we simulate errors at the `HasFS` layer, we should simulate partial reads and writes, to verify whether we handle those correctly in the immutable DB.

**Comment by edsko** [comment]
Consensus seems to be:

* We rename `hGet` from the type class to `hGetAtMost`, to avoid incorrect usage. Some existing uses of `hGet` would be just fine (for instance, the one in `readIncremental` where we just ask for `defaultChunkSize`).
* We introduce a function `hGetExactly` in `FS.API` (not as part of the class), which loops to read an exact number of bytes. If it reaches EOF before it reaches this, it will throw an `UnexpectedEndOfFile` exception (it would know that this happened when `hGetAtMost` would return an empty bytestring).

**Comment by dcoutts** [comment]
> We rename hGet from the type class to hGetAtMost, to avoid incorrect usage.

I agree, but lets call it `hGetSome` to match what's already there in `System.IO` and the IO functions in `Data.ByteString`.

**Comment by kderme** [comment]
Mental note that I will need to change hGet to hGetExactly at the Parser of VoaltileDB. I will also need to handle eof exceptions (or hSeek to avoid eof exceptions) at this stage, or some corruption tests will fail.

**Comment by kderme** [comment]
> We introduce a function hGetExactly in FS.API (not as part of the class)
I understand we want to define `hGetExactly` in terms of `hGetSome` (old hGet). `hGetSome` returns a strict ByteString, so `hGetExactly` should have to concat these ByteStrings (with some performance penalty), or use `fromChunks`, which would however return a lazy ByteString. Not sure what's the best approach here.

**Comment by mrBliss** [comment]
> > We introduce a function hGetExactly in FS.API (not as part of the class)
> 
> I understand we want to define `hGetExactly` in terms of `hGetSome` (old hGet). `hGetSome` returns a strict ByteString, so `hGetExactly` should have to concat these ByteStrings (with some performance penalty), or use `fromChunks`, which would however return a lazy ByteString. Not sure what's the best approach here.

`fromChunks` sounds good to me, especially given that we have #384 open.

P.S. when you rename `hGet` to `hGetSome`, please do it in a separate commit (pet peeve of mine :slightly_smiling_face:)

**Comment by kderme** [comment]
I added another function hGetLenient, which tries to read all bytes in a loop, but does not throw an exception if it finds eof prematurely. I found this function useful in some cases.

**Comment by edsko** [comment]
Related: #502.

**Comment by edsko** [comment]
Closed in #551.
