### ISSUE TITLE
P2P governor might demote local peers

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#2790]
It could happen that the _p2p-governor_ will demote local peers. _p2p-governor_ should  guarantee that it keeps local peers in _hot_ state, and when they disappear (due to reconfiguration etc), it retries to connect to them as soon as they are back online.

**Comment by bolt12** [comment]
What is the state of this issue? I believe that the second part is what happens

**Comment by karknu** [comment]
Duncan has fixed this issue.
