### ISSUE TITLE
Take  snapshots of certain slots

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#2826]
To help the ledger team debug issues, they'd like the ability to create a snapshot of the ledger state at a certain slot number.
#2479 is about extending the disk policy of the LedgerDB to allow taking snapshots of certain slots.

## Definition of Done:
* consensu layer exposes a new lower level flag allowing node operator to explicitly specify slot number for which ledger state's snapshot should be stored on disk
* modify `defaultDiskPolicy` so that it uses the above mentioned flag such that upon calling `onDiskShouldTakeSnapshot`, if the slot number meets the one provided via node operator, the snapshot is taken
* open up a branch on `cardano-node` where the new flag is integrated in the node

## Further improvements

Some other notes/remarks that might be included in this ticket on in follow-ups. After delivering this functionality we will most likely consult with ledger state team to clarify the next steps (if any). #KISS

Besides that, some more changes will be needed:

* As briefly mentioned in #2479. The slots might be older than the slot at the tip of the chain after opening, so the policy will never see that slot number and will never be able to take the snapshot. The user could manually delete blocks and resync them to work around this, but that's ugly. The proper solution is to add the ability to take snapshots during ledger replay.
* Even with the above implemented, we still wouldn't be able to make snapshots of slots before the "immutable slot" (the slot at the tip of the last snapshot). We could try to be smart and replay from an older snapshot or from genesis, but that's a bit more complicated. We could also give a warning and suggest the user to delete their on-disk snapshots, triggering a replay from genesis. This functionality should only really used by developers anyway.
* The snapshots consensus writes to disk are of `ExtLedgerState`, which wraps the ledger state as defined by the ledger team. It would probably be convenient for them if we could also write snapshots in the ledger format so that they can easily decode them. For Shelley, that ledger format would be `NewEpochState` (= our `LedgerState (ShelleyBlock era)`), but it might also be possible to transform the `ExtLedgerState` to the ledger's top-level `ChainState` format. Maybe the choice of format (consensus vs ledger) could be a flag?
* It would probably be easiest for the ledger team if they could use the node for this (so they can sync the necessary blocks at the same time), not the consensus-only `db-analyser` tool (which would be a natural place for us to add it). This means the node would take some extra CLI parameters that would have to be passed to consensus.

**Comment by EncodePanda** [comment]
This is unlocked by https://github.com/input-output-hk/ouroboros-network/issues/2479.

**Comment by EncodePanda** [comment]
In his closing review (https://github.com/input-output-hk/ouroboros-network/pull/2928#pullrequestreview-589918998) @nfrisby mentioned a branch to integrate changes to `cardano-node`. This could become part of this PR.

**Comment by EncodePanda** [comment]
We are closing this ticket for a new one that emerged from it https://github.com/input-output-hk/ouroboros-network/issues/2949
