### ISSUE TITLE
Test the hard fork from Allegra to Mary

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#2846]
Run the ThreadNet tests for a net forking from Allegra to Mary. This can just be a copy-paste of [`Test.ThreadNet.ShelleyAllegra`](https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-consensus-cardano-test/test/Test/ThreadNet/ShelleyAllegra.hs). But ideally, the common code is generalised so it can be used by both (as there will follow many more hard forks, this would not be premature abstraction!). Alternatively, `ShelleyAllegra` is replaced with `AllegraMary`?

Ideally, we'd use the rewritten ThreadNet tests for this :slightly_smiling_face:

**Comment by mrBliss** [comment]
@nfrisby It's also important to check the Mary ledger state for thunks, e.g., by including the following in your `cabal.project.local` and running the Mary ThreadNet tests:
```
package io-sim-classes
  flags: -checktvarinvariant
```

**Comment by nfrisby** [comment]
I ran this new test four times without the flag (~35s) and four times with the flag (~750s). No errors 🙌.
