### ISSUE TITLE
[CAD-1720] Integrate Alonzo ledger

### ISSUE THREAD

**Issue by nfrisby** [input-output-hk/ouroboros-network#2871]
This Issue is to integrate the Alonzo ledger Shelley-based era into the Consensus layer.

The document added by PR #2847 should be an extremely useful guide about how to proceed. Just like Allegra and Mary, Alonzo is -- from the Consensus Layer's perspective -- a minor revision of Shelley. So it should follow the same pattern established by Allegra and Mary. That document walks through the necessary steps.

**Comment by EncodePanda** [comment]
There is right now a branch where a bunch of appropriate changes were made https://github.com/input-output-hk/ouroboros-network/tree/EncodePanda/CAD-1720-intergrate-alonzo. We now wait for cardano-ledger-alonzo to provide missing bits.
