### ISSUE TITLE
Incorrect Pipelining Descisions for Chainsync Client

### ISSUE THREAD

**Issue by karknu** [input-output-hk/ouroboros-network#2919]
Regarding `pipelineDecisionMax`, `pipelineDecisionMin`, `pipelineDecisionLowHighMark` . 

The decision for when to do `Request` and when to do `Pipelining` when there are `Zero` outstanding blocks is incorrect. The functions listed above only does a `Request` when there are `Zero` outstanding requests and the server is one block ahead of the client. The correct behavior is that a `Request` should be issued if both client and server have the same tip, that is they are both waiting for the next block to be forged.

**Comment by nfrisby** [comment]
Does your PR #2917 fully resolve this?

**Comment by karknu** [comment]
It does, but I intend to fix it in a separate PR.

**Comment by nfrisby** [comment]
OK, got it. Thanks for clarifying.

**Comment by karknu** [comment]
Fixed
