### ISSUE TITLE
Emit a unique Mempool tracer event for duplicate txs

### ISSUE THREAD

**Issue by nfrisby** [input-output-hk/ouroboros-network#2933]
Node and Consensus chatted about input-output-hk/cardano-node#2350 on Slack. This Issue captures our first thought about how to assist.

The SPOs are seeing high CPU usage until they disable mempool tracing. The leading suspect is that we're seeing duplicate rejection events when we fetch the same tx from multiple peers. See that `cardano-node` ticket for more info.

The node's TxSub logic -- in particular contrast to BlockFetch -- makes no attempt to fetch a tx from only one peer. In other words, the various TxSub server threads running on a node only first synchronize by adding their fetched txs to the node's single mempool. In general, only the first of the per-peer TxSub server thread to do so will be able to add each tx.

So we expect these duplicate rejections given our design (favoring the simplicity of not prematurely synchronizing the TxSub server threads), and have not seen them causing negligible CPU/network overhead eg. This is supported by the SPOs seeing less utilization by merely disabling the mempool tracers.

This Issue is therefore to emit a distinct event for duplicate transactions, separate from txs that are rejected for more interesting reasons. This will allow the node team to easily avoid the apparent expense of these duplicate tx rejection ids without losing all the mempool tracing logs.

**Comment by gufmar** [comment]
the following graph shows `cncli ping` miniprotocol latency to 3 neighbour nodes over time. (2 VMs and one RockPi)

each peer is measured every 10 second
each such datapoint has an average and max value, calculated from 4 captures every 2 seconds

on the right side, you see when I turned one peer's traceMemPool on
the upper red line shows the measured max value, the lower red line the average milliseconds for one complete miniprotocol session.

The peer had 23 outgoing and 17 incoming streams during this capture

<img width="1206" alt="2021-03-30_13h12_29" src="https://user-images.githubusercontent.com/13198220/112980129-c4837b00-9159-11eb-9669-993e9d24c264.png">

and here's the CPU usage for the same time range

<img width="1199" alt="2021-03-30_13h13_30" src="https://user-images.githubusercontent.com/13198220/112980165-d533f100-9159-11eb-9027-c9708df1289a.png">


The VM has configured 16 vCPU cores on a virtualization host with Dual Xeon 32 CPU cores and almost no other load. 

This are the used trace settings

```
  "TraceBlockFetchClient": false,
  "TraceBlockFetchDecisions": false,
  "TraceBlockFetchProtocol": false,
  "TraceBlockFetchProtocolSerialised": false,
  "TraceBlockFetchServer": false,
  "TraceChainDb": true,
  "TraceChainSyncBlockServer": false,
  "TraceChainSyncClient": false,
  "TraceChainSyncHeaderServer": false,
  "TraceChainSyncProtocol": false,
  "TraceDNSResolver": true,
  "TraceDNSSubscription": true,
  "TraceErrorPolicy": true,
  "TraceForge": true,
  "TraceHandshake": false,
  "TraceIpSubscription": true,
  "TraceLocalChainSyncProtocol": false,
  "TraceLocalErrorPolicy": true,
  "TraceLocalHandshake": false,
  "TraceLocalTxSubmissionProtocol": false,
  "TraceLocalTxSubmissionServer": false,
  "TraceMempool": true,
  "TraceMux": false,
  "TraceTxInbound": false,
  "TraceTxOutbound": false,
  "TraceTxSubmissionProtocol": false,
  "TracingVerbosity": "NormalVerbosity",
  "TurnOnLogMetrics": true,
  ```
  
  only `TraceMempool` changed

**Comment by gufmar** [comment]
this is how latency looks like when traceMempool is disabled on all displayed peers

![image](https://user-images.githubusercontent.com/13198220/112980674-728f2500-915a-11eb-99f7-e712fbc6758a.png)

**Comment by deepfire** [comment]
@gufmar, I highly recommend trying `1.26.1`.

**Comment by gufmar** [comment]
here's how it looks on 1.26.1 

- the whole x-range is on the new version
- red arrows marks restart with traceMempool true
- the 3 peaks before the restart was caused by a cli query ledger-dump

![image](https://user-images.githubusercontent.com/13198220/113046170-02a38d80-91a0-11eb-9b2b-5a1c0544f5bc.png)

so almost zero difference now. 
CPU is slightly increased but nothing critical
good job!

**Comment by chimaeraa** [comment]
i did test something and it's not good.
make wrong tx in Utxeo and sign it .
then put it in endless loop  and send it to network .
you can see after few sec you have overload in cpu  an connection usage .

**Comment by kaverne** [comment]
> 
> 
> @gufmar, I highly recommend trying `1.26.1`.

Is 1,26,1 considered production quality ?
Genuinely asking as it doesn't have any tag or meaningful flag/comment that we can go use it ?

**Comment by nfrisby** [comment]
@kaverne I see `1.26.1` listed here, but I don't know if that's only because I'm inside the GH organization eg. Do you see it? As I understand it, the `1.26.1` release is imminent. HTH.

https://github.com/input-output-hk/cardano-node/releases

**Comment by nfrisby** [comment]
The Ledger/Node Teams have already improved handling of the duplicate tx issues, without the idea suggested in this Issue. So I'm Closing this now.

It's possible that we will re-open it for other reasons later, eg just for the sake of clearer messages.

cc: @deepfire

**Comment by gufmar** [comment]
This is how release page looks for not insiders

![Screenshot_20210407-080300](https://user-images.githubusercontent.com/13198220/113818429-0aeb6200-9778-11eb-8835-37a825111e3e.jpg)

**Comment by kaverne** [comment]
@nfrisby @gufmar Yes I can see it mate it's all good.
The exact same way as @gufmar screenshot.

But as you can see the "Latest release" tag is on 1.25.1
So 1.26.1 is a release yes, but is it good to go for our production nodes or should be stick to 1.25.1 ?

**Comment by rphair** [comment]
> So 1.26.1 is a release yes, but is it good to go for our production nodes or should be stick to 1.25.1 ?

FYI https://github.com/papacarp/pooltool.io/issues/128

**Comment by kaverne** [comment]
ah ok yeah, that is what I was thinking, thanks @rphair 
So without being pedantic the latency fix would have to wait validation against an official release to be flagged as closed ?

**Comment by nfrisby** [comment]
@gufmar -- I think the releases page was updated since your message. Do you see the discussion of 1.26.1 there now?

**Comment by gufmar** [comment]
yes, all ok. good to see the release notes now all in one piece.
