### ISSUE TITLE
Add a "requested snapshotting interval" flag

### ISSUE THREAD

**Issue by EncodePanda** [input-output-hk/ouroboros-network#2949]
# Current situation

Current OnDisk policy for snapshots is following:

```
    onDiskShouldTakeSnapshot (Just timeSinceLast) blocksSinceLast _slotNo =
           timeSinceLast >= secondsToDiffTime (fromIntegral (k * 2))
        || (   blocksSinceLast >= 50_000
            && timeSinceLast > 6 * secondsToDiffTime 60)
    onDiskShouldTakeSnapshot Nothing blocksSinceLast _slotNo =
           blocksSinceLast >= k
```

In the usual case, a new snapshot is taken if either of the following hold:
1. It has been at least k*2 seconds (called snapshotting period) since the last snapshot was taken
2. The last snapshotted ledger state was 50k blocks ago and it5was taken at least 6 minutes ago

# Problem

Benchmarking team has little control over when (or how often) snapshots are taken.

# Solution

Add a new non-mandatory flag called "requested snapshotting interval" that will override the behaviour of `onDiskShouldTakeSnapshot` in the following way:

In the usual case, a new snapshot is taken if either of the following hold:
1. It has been at least `requested snapshotting interval` (in seconds) since the last snapshot was taken. If `requested snapshotting interval` is not set, then it defaults to `k * 2` seconds
2. The last snapshotted ledger state was 50k blocks ago and it was taken at least 6 minutes ago

# Stakeholders:
* benchmarking team (@deepfire)

# Definition of Done
* flag is exposed via consensus
* value from the flag (if set) modifies the behaviour of DiskPolicy such that k*2 is overridden and value from the flag is being used
* a branch on cardano-node is created that integrates the changes from cardano-consensus
  * one can start the node with the newly added flag and see it in action (snapshots are created with a given frequency)

**Comment by nfrisby** [comment]
LGTM.

@EncodePanda I edited the description; I think there was a typo in the logic. (You can use the GitHub UI to double-check my changes.)

One suggestion: the name "minimum snapshotting period" for a value X sounds like the interval between snapshots can be no smaller than X. But that's actually the opposite of what we're quasi-ensuring!5I suggest instead calling it "requested snapshotting interval" eg. And the semantics is that we make a best effort to ensure the interval between any two snapshots only exceeds that value as much as is necessary.

**Comment by EncodePanda** [comment]
@nfrisby I've renamed the flag to `requested snapshotting interval`
