### ISSUE TITLE
Configure stylish-haskell to format datatypes correctly

### ISSUE THREAD

**Issue by EncodePanda** [input-output-hk/ouroboros-network#2952]
Blocked by: https://github.com/input-output-hk/ouroboros-network/issues/2951

It seems that all rules in the style guide regarding datatype formatting can be governed by stylish-haskell (version > 0.12.x.x)

**Comment by EncodePanda** [comment]
As it turns out stylish (even in latest 0.12.2.2) still misses some critical components for us to use it. Mainly:

```
  #     equals - How to format equals sign between type constructor and data constructor.
  #     # Possible values:
  #     # - "same_line" -- leave "=" AND data constructor on the same line as the type constructor.
  #     # - "indent N" -- insert a new line and N spaces from the beginning of the next line.
```
We need to have ability to say "equals same line but NOT the data constructor

```   
  #     first field: How to format first field of each record constructor.
  #     # Possible values:
  #     # - "same_line" -- "{" and first field goes on the same line as the data constructor.
  #     # - "indent N" -- insert a new line and N spaces from the beginning of the data constructor
```
We need to say how we indent first field and other fields (because in our case this is different.

This means that this issue is blocked until necessary changes are done in stylish

**Comment by Jasagredo** [comment]
We for now don't plan on having an auto-format on datatypes, but might eventually reconsider. Closing for now.
