### ISSUE TITLE
Define GHC version in shell.nix and let haskell.nix reuse it

### ISSUE THREAD

**Issue by EncodePanda** [input-output-hk/ouroboros-network#2982]
See work done in https://github.com/input-output-hk/ouroboros-network/pull/2968/commits/a8834d8226de8d5e624032690872484c38ab1d32 and make it work :)

**Comment by nfrisby** [comment]
I don't have a lot of experience, but I think `default.nix` is the primary entrypoint and `shell.nix` is secondary. This suggests to me that the choice of GHC belongs in `default.nix`. What do you think @EncodePanda ?

**Comment by Jasagredo** [comment]
This issue can be closed as #3083 states that it should close this issue (but Github didn't do so).
