### ISSUE TITLE
Missing numactl in nix-shell build environment

### ISSUE THREAD

**Issue by bolt12** [input-output-hk/ouroboros-network#3033]
While trying to use Haskell-Language-Server on `ouroboros-network-framework`, for example,, I get a compilation error saying `ld could not find -lnuma`.  Although my machine supports numa, I found that the nix build environment does not have any reference to `numactl` so I added that somewhere in `shell.nix` ~~and didn't get that error anymore (I got a different one unrelated to numa 😛 edit: related to the fact my `/tmpfs` is getting full).~~ Apparently the error I was getting overtook the `lnuma` error so adding numactl didn't help...

~~I want to know if anyone finds the same problem and if adding `numactl` to the build environment indeed fixes this issue.~~

Does anyone know how to fix this?

**Comment by jonringer** [comment]
If the wrapped version of the compiler is available in that environment, just adding `numactl` to `buildInputs` should be sufficient.

**Comment by bolt12** [comment]
How do I check if the wrapped version of the compiler is available?

**Comment by EncodePanda** [comment]
Hi @bolt12 , let me just reiterate what I understood. you are trying to use HLS with ourboros-network but HLS was complaining. What did you do next? Because I'm having troubles reading your next steps and the outcome. Did you add `numactl` to `buildInputs` in `shell.nix`? If yes, what was the issue next. If no, please try it out :)

**Comment by bolt12** [comment]
Hi @EncodePanda thanks for trying to look into my issue!

I did added `numactl` to the `buildInputs` in `shell.nix` however the issue persisted:

```
(...)0-libffi-3.3/lib -lm -lrt -ldl -lffi -lnuma -lpthread
> error: /nix/store/10nmk0mlhy9nf3lfrq8q07k0510bgnnf-binutils-2.31.1/bin/ld: cannot find -lnuma
> collect2: error: ld returned 1 exit status
> 
> cabal: Failed to build cardano-crypto-class-2.0.0 (which is required by
> ouroboros-consensus-test-0.1.0.0).
>
```

I think adding `numactl` to the `buildInputs` is redundant since I get the `numactl` command in scope even if I do not add it to `shell.nix`.  My next steps were to try and find if someone else had the same issue as me but it does not seem like it. I am able to do `cabal build all` inside the `ouroboros-network` repo nix-shell tho

**Comment by EncodePanda** [comment]
You've most likely seen this but I'm. just gonna live it here just in case https://stackoverflow.com/questions/9066080/what-is-lnuma-and-what-program-uses-it-for-compilation/35028032

**Comment by bolt12** [comment]
Thanks for the pointer, I had indeed already seen that and even tried this: https://discourse.nixos.org/t/what-is-the-nix-way-to-specify-ld-library-path/6407 but with no success...

**Comment by EncodePanda** [comment]
@bolt12 there is a PR in the making https://github.com/input-output-hk/ouroboros-network/pull/3061 that will enable HLS on ourboros-consensus, FYI

**Comment by bolt12** [comment]
Awesome! Thanks!

**Comment by bolt12** [comment]
I got `haskell-language-server` to work by just opening from the top-level `ouroboros-network` folder. If I cd into other repo inside `ouroboros-network` and open a Haskell file with vim, it errors with missing `-lnuma`. Very weird, is there any reason for this?

**Comment by bolt12** [comment]
I'm going to close this issue since it has already been solved.
