### ISSUE TITLE
Make sure IO HasFS wrapper includes mount point in error messages

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#305]
This makes it easier for users to interpret these errors should they propagate up.

**Comment by mrBliss** [comment]
@kderme says that on Unix systems, the `FHandle` type used by `HasFS` operations on handles already causes the error messages to display the full path, including the mount point.

It would be better to do this in one place, e.g., `rethrowFsError`, and prepend the mount point to the `fsErrorPath` of `FsError`.

**Comment by edsko** [comment]
Effectively what this means is that operations on _files_ already display a good error messgae, but operations on directories might still only show relative paths, is that correct @kderme ?

**Comment by edsko** [comment]
We do probably want to fix this before releasing as it will make any bug reports probably easier to understand.

**Comment by mrBliss** [comment]
Addressed by #1529.
