### ISSUE TITLE
documentation for local state query protocol

### ISSUE THREAD

**Issue by ashisherc** [input-output-hk/ouroboros-network#3051]
please provide the documentation with CDDL of the local state query mini protocols

**Comment by coot** [comment]
The CDDL spec of local state query protocol is now provided.  The latest version of the technical report is available [here](https://hydra.iohk.io/job/Cardano/ouroboros-network/native.network-docs.x86_64-linux/latest/download/2).

**Comment by ashisherc** [comment]
Thank you very much @coot, where can we find the CDDL for the result and query for the local state query protocol?

**Comment by coot** [comment]
Let's chase the consensus or ledger team for that, the network code is polymorphic with regard to query and result.

@nfrisby do you have a CDDL spec for query / result in `LocalStateQuery` mini-protocol.

**Comment by nfrisby** [comment]
I don't see anything.

```
$ git grep -i -e cddl -- ouroboros-consensus*
$ git ls-files '*cddl*'
ouroboros-network/test-cddl/Main.hs
ouroboros-network/test-cddl/specs/block-fetch.cddl
ouroboros-network/test-cddl/specs/chain-sync.cddl
ouroboros-network/test-cddl/specs/common.cddl
ouroboros-network/test-cddl/specs/handshake-node-to-client.cddl
ouroboros-network/test-cddl/specs/handshake-node-to-node.cddl
ouroboros-network/test-cddl/specs/keep-alive.cddl
ouroboros-network/test-cddl/specs/local-state-query.cddl
ouroboros-network/test-cddl/specs/local-tx-submission.cddl
ouroboros-network/test-cddl/specs/tx-submission.cddl
ouroboros-network/test-cddl/specs/tx-submission2.cddl
```

Let me think it over. Thanks for pinging me.
