### ISSUE TITLE
Update ledger after transaction rewrite

### ISSUE THREAD

**Issue by EncodePanda** [input-output-hk/ouroboros-network#3067]
The https://github.com/input-output-hk/cardano-ledger-specs/pull/2225 was merged 4 days ago. We should update our ledger-spec dependency and then rebase alonzo branch (https://github.com/input-output-hk/ouroboros-network/pull/2932)

**Comment by Jasagredo** [comment]
Alonzo was merged eventually so this issue actually can be closed
