### ISSUE TITLE
Core/Edge split

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#308]
Nodes should be able to opt in or out to becoming leaders, skipping leader checks if they are not. Core nodes have a delegation certificate and a KES key, edge nodes do not. Currently, the current node abstraction assumes that it is a core node, but it may very well not be.

**Comment by edsko** [comment]
Related: #262.

**Comment by edsko** [comment]
This is not specific to BFT, it applies equally to Praos; recording it as part of PermBFT because we need to implement it for the PermBFT release (and then hopefully use it also for Praos).

**Comment by edsko** [comment]
@dcoutts mentions "Yes. Most nodes will not have an (operation key, operational cert) pair, and thus will never produce blocks.". So I guess I'll resolve this once we get to the full node integration -- if you provide a cert, you produce blocks; otherwise, you don't.

**Comment by edsko** [comment]
We should probably aim to remove `NodeId` entirely from the code base, or use it only for demo/tests.

**Comment by mrBliss** [comment]
Relevant: #634.

**Comment by edsko** [comment]
@nc6 tells me that the core/edge split is basically already done. This probably just leaves some cleanup now of the whole `NodeId` concept.

**Comment by mrBliss** [comment]
Remaining work moved to #1199.
