### ISSUE TITLE
Update ledger-spec dependency

### ISSUE THREAD

**Issue by EncodePanda** [input-output-hk/ouroboros-network#3096]
Lately ledger-spec brought back the `instance API.PraosCrypto c => API.ShelleyBasedEra (AlonzoEra c)`.
It's worth to now update our ledger-spec dependency so that the "Alonzo branch" (https://github.com/input-output-hk/ouroboros-network/pull/2932) can benefit from that (after rebase).

**Comment by nfrisby** [comment]
Closed by PR #3036
