### ISSUE TITLE
Public P2P Release Plan

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#3101]
This issue records issues that needs to be announced publicly before p2p
mainnet release.  Some of them should also be announced with public test-nets to
give SPOs more time to react.

- [x] pool certificate must be valid; in particular if an ip address is  registered as a dns name,
    the node will not have any downstream peers, and thus its blocks will not be distributed by
     the system.

**Comment by karknu** [comment]
The domain name in the pool cert should point to a relay that is directly connected to the operators BP. Notably `relays-new.cardano-mainnet.iohk.io` is not connected to non-iohk BPs.

**Comment by coot** [comment]
The reminder to update certificates was sent on discord.
