### ISSUE TITLE
Inadequate number of connections

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#3141]
As reported by Karl:

> The number of total connections and the number of outgoing connections isn’t correct.
> The node is configured to have 50 warm peers, and it has one client.
> lsof confirms the expected 51 connections.

<img width="717" alt="Screenshot 2021-05-12 at 07 39 18" src="https://user-images.githubusercontent.com/698209/118234683-fb0c1f80-b493-11eb-9045-26e5a9334e2a.png">

[slack thread](https://input-output-rnd.slack.com/archives/GFLJKNG3T/p1620798138258800)

**Comment by bolt12** [comment]
This might be due to the bug that @karknu found on `ConnectionManager` ([slack thread](https://input-output-rnd.slack.com/archives/GFLJKNG3T/p1621235816395600))

**Comment by karknu** [comment]
I suspect that this is a separate issue.

**Comment by bolt12** [comment]
I think they might be related, it boils down to a problem in the connection manager state since the counters calculation is pure

**Comment by bolt12** [comment]
@karknu this has happened again, right? Any new info you can provide?

**Comment by karknu** [comment]
It hasn't happened since I upgraded the devnet to `27d01fb0c15e2c092b3642fc7ec0303716739595` , it is possible that #3167 fixed the issue.

**Comment by karknu** [comment]
Fixed in #3167 .
