### ISSUE TITLE
Strides of `PeerSelectionCounters` in the log

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#3144]
I found this in a log.
```
[fozzie:cardano.node.PeerSelection:Info:92] [2021-05-14 08:26:52.01 UTC] PeerSelectionCounters {coldPeers = 11, warmPeers = 3, hotPeers = 2}
[fozzie:cardano.node.PeerSelection:Info:92] [2021-05-14 08:26:52.02 UTC] PeerSelectionCounters {coldPeers = 11, warmPeers = 3, hotPeers = 2}
[fozzie:cardano.node.PeerSelection:Info:92] [2021-05-14 08:26:52.07 UTC] PeerSelectionCounters {coldPeers = 11, warmPeers = 3, hotPeers = 2}
[fozzie:cardano.node.PeerSelection:Info:92] [2021-05-14 08:26:52.08 UTC] PeerSelectionCounters {coldPeers = 11, warmPeers = 3, hotPeers = 2}
[fozzie:cardano.node.PeerSelection:Info:92] [2021-05-14 08:26:52.08 UTC] PeerSelectionCounters {coldPeers = 11, warmPeers = 3, hotPeers = 2}
[fozzie:cardano.node.PeerSelection:Info:92] [2021-05-14 08:26:52.08 UTC] PeerSelectionCounters {coldPeers = 11, warmPeers = 3, hotPeers = 2}
[fozzie:cardano.node.PeerSelection:Info:92] [2021-05-14 08:26:52.08 UTC] PeerSelectionCounters {coldPeers = 11, warmPeers = 3, hotPeers = 2}
[fozzie:cardano.node.PeerSelection:Info:92] [2021-05-14 08:26:52.08 UTC] PeerSelectionCounters {coldPeers = 11, warmPeers = 3, hotPeers = 2}
[fozzie:cardano.node.PeerSelection:Info:92] [2021-05-14 08:26:52.08 UTC] PeerSelectionCounters {coldPeers = 11, warmPeers = 3, hotPeers = 2}
```

**Comment by bolt12** [comment]
These traces happen whenever the Peer Selection Governor performs a decision. Does the log also shows `TraceGovernorState` ? They should also appear along side side. Were you able to find more of these, it might be just an unlikely extra fast running trace

**Comment by bolt12** [comment]
@coot

**Comment by coot** [comment]
`TraceGovernorState` is off by default, but counters are not.  I was thinking that either we add cache the previous result and only log if it's different, or just ignore it.

**Comment by bolt12** [comment]
Good idea! I will implement that!

**Comment by coot** [comment]
Try to make small `Cache` component which allows to do that, so we could reuse it on the inbound side too.

**Comment by coot** [comment]
This could be defined as part of a `Tracer`, then we woulnd't clutter the code.

**Comment by bolt12** [comment]
Is this comment related to the PR? Are you suggesting to move the `traceWithCache` and `mapWithCache` functions to `Tracer` ? (Also the I am quite bad with names, those are not final)

**Comment by coot** [comment]
I haven't looked at your PR when I wrote the comment. I see so you have:
```
traceWithCache :: (Applicative m, Eq a) => Tracer m a -> Cache a -> a -> m ()
```
I was thinking about hiding all inside `Tracer`; this would require to store state inside of it though.

**Comment by coot** [comment]
Let's go with your solution; for hiding this inside `Tracer` it would be nice to use an `MVar` (or maybe even an `IORef`) rather than `TVar`, but `io-sim-classes` do not expose access to `MVar`s or `IORef`s.
