### ISSUE TITLE
Bring back `db-analyzer` after Alonzo integration in consensus.

### ISSUE THREAD

**Issue by Jasagredo** [input-output-hk/ouroboros-network#3179]
After #3178, the only remaining leftover related to the Alonzo era, is that the `db-analyser` cannot run; there's an undefined instead of the `AlonzoGenesis` config file parser

See [this line](https://github.com/input-output-hk/ouroboros-network/pull/3138/files?file-filters%5B%5D=.cabal&file-filters%5B%5D=.hs&file-filters%5B%5D=.json&file-filters%5B%5D=.project&file-filters%5B%5D=.yml#diff-6ca83d681aca3cfdb97e27fa366efbb3f08d3088296e9ef3c3a256cbe6441435R72)

This issue emerged after #3139.

**Comment by nfrisby** [comment]
Errr, maybe they are going with a split Alonzo file after all. See this open&active PR

https://github.com/input-output-hk/cardano-node/pull/2743

**Comment by Jasagredo** [comment]
I think this issue can be closed now that `db-analyser` is back. Reopen if not.
