### ISSUE TITLE
`TraceBlockFetchServerSendBlock` doc

### ISSUE THREAD

**Issue by karknu** [input-output-hk/ouroboros-network#3199]
The comment for `TraceBlockFetchServerSendBlock` should make it clear that we're tracing the start of, not the end of block sending.

**Comment by bolt12** [comment]
I do not find this comment, could you point me to it?

**Comment by karknu** [comment]
https://github.com/input-output-hk/ouroboros-network/blob/45780803aa15acf83cad1197d0c90ee27d71464a/ouroboros-consensus/src/Ouroboros/Consensus/MiniProtocol/BlockFetch/Server.hs#L134-L135

**Comment by bolt12** [comment]
So adding this line would be enough?

> -- This traces the start, not the end, of block sending.
