### ISSUE TITLE
network-spec: Inconsistent documentation and code

### ISSUE THREAD

**Issue by Yang123321** [input-output-hk/ouroboros-network#3201]
code: https://input-output-hk.github.io/ouroboros-network/typed-protocols-examples/src/Network.TypedProtocol.ReqResp.Type.html#ReqResp
document: https://hydra.iohk.io/build/6493793/download/2/network-spec.pdf

![image](https://user-images.githubusercontent.com/20609008/120948285-e7a94880-c70f-11eb-9952-1d0d2b00b11e.png)

**Comment by bolt12** [comment]
I'll try fixing this!
