### ISSUE TITLE
Don't punish local client for invalid scripts

### ISSUE THREAD

**Issue by nfrisby** [input-output-hk/ouroboros-network#3205]
If a remote peer sends us an Alonzo transaction with a failing script, we include that transaction on the chain despite its ~invalidity~ phase 2 validation failure -- it's explicitly marked on the chain as ~invalid~ phase 2 invalid so that can be properly handled (eg it doesn't necessary consume its declared input UTxOs). We're only including it on the chain so that the party that created it must pay the cost of its (failed) execution.

On the other hand, if a _local_ peer (ie the wallet) sends us such a transaction, it would be more friendly of us to simply reject the transaction and inform them that something has gone wrong between their assumed intentions and our dynamic checks.

This Issue is there to enrich the `Mempool` interface and the `LocalTxSubmission` mini protocol server definition as necessary so that we can be lenient with a "local" peer that's providing transactions. Recall that we assume the Node-to-Client protocols (such as `LocalTxSubmission`) are local and imply some trust/good will in both directions.

**Comment by tdiesler** [comment]
Related to: https://github.com/input-output-hk/cardano-node/issues/2942
