### ISSUE TITLE
Setup p2p and non-p2p chairman tests

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#3247]
In `cardano-node` `p2p-master` branch we need to have both p2p and non-p2p
functioning chairman tests.

**Comment by bolt12** [comment]
Tackled by https://github.com/input-output-hk/cardano-node/pull/2905

Byron - NonP2P (due to NodeToNodeVersion constraints)
ByronShelley - P2P
Shelley - NonP2P (due to NodeToNodeVersion constraints)
