### ISSUE TITLE
Test connection pruning in simulation

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#3253]
This reuiqres writing / adjusting generators which are used by
[`prop_multinode_Sim`](https://github.com/input-output-hk/ouroboros-network/blob/p2p-master/ouroboros-network-framework/test/Test/Ouroboros/Network/Server2.hs#L1553).
The test should ensure that prunning is tested using
[`cover`](https://hackage.haskell.org/package/QuickCheck-2.14.2/docs/Test-QuickCheck.html#v:coverTable)
and
[`checkCoverage`](https://hackage.haskell.org/package/QuickCheck-2.14.2/docs/Test-QuickCheck.html#v:checkCoverage).

**Comment by bolt12** [comment]
https://github.com/input-output-hk/ouroboros-network/pull/3309
