### ISSUE TITLE
multinode server2 simulation: introduce attenuation

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#3263]
Currently we don't use any attenuation in the simulation, however we should
introduce:

* a QuickCheck generator for `BearerInfo` (and `Script BearerInfo`);
* test its distribution;
* plug it into `prop_multinode_Sim` and possibly other simulations

**Comment by coot** [comment]
@bolt12 is this all addressed by #3281?

**Comment by bolt12** [comment]
Yes
