### ISSUE TITLE
Expand 'Simulation.Network.Socket' tests

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#3289]
Test various scenarios without running any protocols:

* [ ] connect to a listening socket
* [ ] connect to a listening socket which is not blocked on `accept` (the `connect` call should timeout)
* [ ] connect to a uninitialised socket
* [ ] simultaneous open (that's also tested in `Ouroboros.Network.Handshake.Test`, make a simplified version which does not use `Handshake`)
* [ ] test closing the socket.  The simulated socket is closed only when both sides
  close it (unlike TCP, which is using 4-way handshake, we use two 2-way
  handshakes to close the connection).
* [ ] anything else?

**Comment by bolt12** [comment]
Related to my work with #3309, I triggered a lot of async-exceptions related `Deadlock` and `NotReleasedResources` errors when requesting inbound/outbound connections with number of connections hard limit `= 0`. This would make connect timing out and when receiving an `AsyncCancelled` exceptions a lot of parts of the code would either ignore the exception (triggering a deadlock) or not correctly cleaning up the `NetworkState`. So in a way a test that checks whether we do not get this type of errors would be good to have as well.

**Comment by karknu** [comment]
* Accept failures, that is start a server let it block on `accept` . Verify correct behavior when an async exception is thrown, econnaborted, and other exception.
