### ISSUE TITLE
prop_multinode_Sim: in presence of accept IO errors

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#3315]
This should reproduce the https://github.com/input-output-hk/cardano-node/issue/3080 problem in simulation.

**Comment by karknu** [comment]
https://github.com/input-output-hk/ouroboros-network/issues/3289#issuecomment-911526428

**Comment by coot** [comment]
Closing as a duplicate.

**Comment by coot** [comment]
Let's use this issue to extend the `prop_multinode_Sim`, #3289 is just about testing  the network simulation environment.

**Comment by coot** [comment]
See #3384, and branch [coot/p2p-sim-server-error](https://github.com/input-output-hk/ouroboros-network/tree/coot/prop-pruning-failure)
