### ISSUE TITLE
prop_connection_manager_counters: late errors

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#3511]
When I worked on #3508, I found out that the `prop_connection_manager_counters`
could reveal errors after `10_000` tests.  The errors were fixed, but it is
still worring that one needed so many iterations to come up with a failing
script of just 4 or 5 steps.  On the other hand it shows that the shrinker did
a decent job.

**Comment by coot** [comment]
When I worked on #3508 this was one of the counterexamples I found:
```
prop :: Property
prop = prop_connection_manager_counters 0 (ArbDataFlow Duplex)
          (MultiNodeScript
            [ StartServer 0 (TestAddr {unTestAddr = TestAddress 54}) 0
            , OutboundConnection 0 (TestAddr {unTestAddr = TestAddress 54})
            , ShutdownClientServer 0.02 (TestAddr {unTestAddr = TestAddress 54})
            , StartClient 0 (TestAddr {unTestAddr = TestAddress 54})
            ])
```

**Comment by bolt12** [comment]
It doesn't seem this is still reproducible. Running multiple 10k tests to see if it triggers some sort of error.
