### ISSUE TITLE
Demoting non-hot peer assertion

### ISSUE THREAD

**Issue by karknu** [input-output-hk/ouroboros-network#3586]
cardano-node: Assertion failed
CallStack (from HasCallStack):
  assert, called at src/Ouroboros/Network/PeerSelection/Governor/Types.hs:405:5 in ouroboros-network-0.1.0.0-50a0e8b5b3073b11a5c3eb6b69bfa5d0e19a94e02b399c4c2c0793212741011c:Ouroboros.Network.PeerSelection.Governor.Types 
 
 
Assert line:
```   assert (Set.isSubsetOf inProgressDemoteHot   hotPeersSet) ```

**Comment by karknu** [comment]
Fixed in #3588

**Comment by coot** [comment]
btw, github only links pull requests if the issues are mentioned in the issue description not a comment.  Otherwise one needs to do that manually; but once that's done the project will close the issue once the PR is merged.
