### ISSUE TITLE
Unify the Tip of the ImmutableDB with the Tip of the LedgerDB

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#368]
There will be two `Tip` data types:

`Ouroboros.Storage.ImmutableDB.Types` (#364):
```haskell
data Tip
  = TipGenesis
    -- ^ The database is empty
  | TipEBB     Epoch
    -- ^ The last thing in the database is the EBB of this 'Epoch'.
  | TipBlock   Slot
    -- ^ The last thing in the database is the block at this 'Slot'.
  deriving (Eq, Show, Generic)
```

`Ouroboros.Storage.LedgerDB.InMemory` (#358):
```haskell
-- | Tip of the chain
data Tip r = Tip r | TipGen
  deriving (Show, Eq, Generic)
```

They should be unified. The `r` parameter of the latter can be instantiated with `Either Epoch Slot`. The constructors of the former can be turned in the pattern synonyms.

**Comment by edsko** [comment]
This was done in #391.
