### ISSUE TITLE
Integrate Babbage ledger

### ISSUE THREAD

**Issue by kk-hainq** [input-output-hk/ouroboros-network#3684]
With the latest works from `plutus` and `cardano-ledger` we could set up a (simulated) development environment for Plutus V2 & Babbage. That said, we still need https://github.com/input-output-hk/cardano-node/issues/3739 to do any significant testing out of the Plutus V2 scripts and transactions.

Given that `Cardano.Api.Eras` imports the `Standard` era types from `Ouroboros.Consensus.Shelley.Eras`, I suspect adding Babbage support here early would make sense. While https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-consensus/docs/AddingAnEra.md is quite clear already, things like the `applyShelleyBasedTx` implementation for Babbage is too involved for us to experiment alone. Hence this issue to ask for help from the ledger and consensus teams!

**Comment by Jasagredo** [comment]
I think this is no longer relevant? Babbage is already running on Mainnet @nfrisby
