### ISSUE TITLE
Volatile DB: Add fingerprint

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#373]
@dcoutts writes:

> for the volatile DB and specifically the point -> block info mapping, we're going to need some "fingerprint" to use in STM txs to see if it's changed, so we can do retry efficiently. We don't need to reveal concrete details so long as we can provide a fingerprint type with an Eq instance. My though for a concrete representation of that though would be the pair of the current size of the mapping and the earliest slot that the mapping covers. If it's append only except for bulk deletes then those two things should always change on every change right? And this would give a cheap to calculate and cheap to compare fingerprint.

**Comment by dcoutts** [comment]
I now think we do not need this. The block fetch does not need the block DB as part of it's "trigger" variables, only it's "non-trigger" variables. This means we don't need an efficient fingerprint. We do still need to get a `point -> block info` mapping as an STM query, but no fingerprint is needed.

**Comment by mrBliss** [comment]
> We do still need to get a `point -> block info` mapping as an STM query, but no fingerprint is needed.

What would `block info` be? And why is this needed?

**Comment by dcoutts** [comment]
The block fetch only requires

**Comment by mrBliss** [comment]
Oh, but we have this already (#435, #463):
```haskell
data VolatileDB blockId m = VolatileDB {
      ..
    , getIsMember :: HasCallStack => STM m (blockId -> Bool)
}
```

**Comment by mrBliss** [comment]
As the fingerprint is not needed anymore, I'm closing this.
