### ISSUE TITLE
Volatile DB: Audit memory footprint

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#378]
In particular, we have to make sure that there are no memory leaks. Use `Map.Strict`, strictly update the `TVar`s, etc.

**Comment by mrBliss** [comment]
Duncan suggested we use [`GHC.AssertNF`](http://hackage.haskell.org/package/ghc-heap-view-0.5.10/docs/GHC-AssertNF.html) for this.

I quote Duncan from Slack:
> some news there: that package is partially bit-rotted since it has to change every ghc release, but @erikd and team have noticed that the underlying functionality is now in ghc proper and will be maintained with each release. They're going to add the `AssertNF` wrapper over the top. So if you decide to tackle this one, talk to @erikd and I think @ luke to see where that code lives now, or where it will live soon.

**Comment by erikd** [comment]
https://github.com/input-output-hk/cardano-prelude/pull/47

**Comment by mrBliss** [comment]
Done in #1110 and #1114.
