### ISSUE TITLE
Chain DB: Audit memory footprint

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#380]
We need to do some heap profiling and audit the code to make sure we have no memory leaks.

**Comment by mrBliss** [comment]
See #378 and #379.

**Comment by dcoutts** [comment]
The ledger test suite now includes a test that uses GHC heap functions to check a value is in full normal form. The ledger test suite runs the full mainnet validation with this check being done once per epoch. We should do something similar for the consensus, though we probably want to also check with small test cases and check after every single step (e.g. chain db change, or chain sync client iteration).

**Comment by mrBliss** [comment]
See #853

**Comment by mrBliss** [comment]
Done in #1114.
