### ISSUE TITLE
Inspect use of `unsafe` functions in network packages

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#3835]

**Comment by mtullsen** [comment]
By history and convention, Haskell library functions have used the prefix 'unsafe' to indicate unsafe functions.  However, it is not always clear what is meant by 'unsafe'.  In what follows, we discriminate between up to four definitions for 'unsafe': 
- unsafe(1): Using this function could break the type-safety of the  language, i.e., break the memory model of the language, cause a crash and/or undefined behavior. E.g., operations we might do with a pointer; or e.g.,  `unsafePerformIO` mimicking unsafe "polymorphic references".
- unsafe(2): Using this function could break equational reasoning for the program.  E.g., `unsafePerformIO` causing indeterminate side-effects.
- unsafe(3).: Using this function could raise an unexpected runtime exception.  E.g., divide by zero, unmatched patterns, etc.
- unsafe(4).: Some user defined property or implicit property of the program might be broken.  E.g., the monad laws could be violated; e.g., `unsafeShiftL`; e.g., an intended module abstraction is being broken; e.g., some preconditions on user code may not hold and thus code could give "wrong" (that is unexpected) results.

Assuming the code is following the naming convention, we can grep for "unsafe" to find potentially suspicious code. Grepping gives just five general cases in the code:

**Comment by mtullsen** [comment]
A. Use of `unsafeNoThunks` (from the `nothunks` package): This function is possibly unsafe(2) as it can allow for code to observe the evaluation state of Haskell expressions.  But the uses here in
   ```
   ouroboros-network/src/Ouroboros/Network/PeerSelection/PeerMetric.hs
   ouroboros-network/src/Ouroboros/Network/TxSubmission/Inbound.hs
   ```
   all follow one of these two desirable patterns for avoiding space leaks:
   ```
    newTVarWithInvariant (\a -> show <$> unsafeNoThunks a) ...
    checkInvariant (show <$> unsafeNoThunks st) (f st) ...
   ```
   where we use functions from the `strict-checked-vars` package (from the `cardano-base` repo) to immediately throw exceptions when values are thunks.

**Comment by mtullsen** [comment]
B. The import of `Test.QuickCheck.Gen.Unsafe` "Unsafe combinators for the Gen monad" in
```
ouroboros-network-testing/src/Ouroboros/Network/Testing/QuickCheck.hs
```
This is only unsafe(4), and at worst allows the user to break the monad abstraction of `Gen`.

**Comment by mtullsen** [comment]
C. The use of `Socket.unsafeFdSocket` in `ouroboros-network-framework/src/Ouroboros/Network/Snocket.hs`
This could be unsafe(3).  This function is used by these two exported functions:
```
socketFileDescriptor
localSocketFileDescriptor
```
Note
- The first function is dead in the repo, as well as in the `cardano-node` and `ouroboros-consensus` repos.
- The second function is used, but currently is only used to create tracer datatypes. For all practical purposes this is safe (1-4); although there's no guarantee that some /very evil code/ won't take the `FileDescriptor` integer from the Trace datatype and use it to create an OS call!
- Although `ouroboros-network-framework/src/Ouroboros/Network/Snocket.hs` has this comment:
  ```
  -- | We use 'unsafeFdSocket' but 'FileDescriptor' constructor is not exposed.
  -- This forbids any usage of 'FileDescriptor' (at least in a straightforward
  -- way) using any low level functions which operate on file
  -- descriptors.
  ```
  The comment isn't true, 'FileDescriptor' is exported, to be used in test/simulation code!  We refactor the code to fix this unfortunate situation in this #4664

**Comment by mtullsen** [comment]
D. The use of `FT.unsafeFmap` in `ouroboros-network-api/src/Ouroboros/Network/AnchoredSeq.hs`
could possibly be unsafe(3) or unsafe(4).  A few notes here
- This use of `FT.unsafeFmap` is rather complicated and subtle.
- It appears that *if* this code was used incorrectly, the Priority Queue implementation would be incorrect---unsafe(4).
- However, the `FT.unsafeFmap` is only used (transitively) by
  ```
  bimapPreservingMeasure, mapPreservingMeasure
  ```
  which are both dead in this repo as well as in the `cardano-node` and `ouroboros-consensus` repos.
- Recommendations: add some QuickCheck properties here; add assertions.

**Comment by mtullsen** [comment]
E. `UnsafeNormalisedId` in `Simulation/Network/Snocket.hs` is a constructor for a local datatype.  This is only unsafe(4) as the datatype is intended to satisfy an invariant not enforced by the constructor (but is enforced by a `normalizeId` smart constructor; it could be helpful to rename this to "UnNormalizedId" to alleviate any doubts regarding safe(1,2,3).
