### ISSUE TITLE
Peer Sharing Implementation

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#3941]
# Objective

Develop peer sharing.  _Note that deployment of peer sharing has more dependencies that development._
Peer Sharing allows to scale the network beside on-chain registered relays.

[Implementation plan](https://github.com/input-output-hk/ouroboros-network/wiki/Gossip-Planning)

* [x] input-output-hk/ouroboros-network#3940
* [x] input-output-hk/ouroboros-network#3981

# Risks

The release will contain a flag, which can be used to make staged release if decided. The release will include a new mini-protocol, a new network protocol version and new functionality, which will have some impact on changes to the network components.

# Dependencies

*  input-output-hk/ouroboros-network#3886

# Deployment

This feature **can only be safely deployed** together with:

* input-output-hk/ouroboros-network#3886
* input-output-hk/ouroboros-network#4123

**Comment by coot** [comment]
[High level peer sharing](https://github.com/input-output-hk/ouroboros-network/wiki/Peer-Sharing-Planning) design is completed.

**Comment by bolt12** [comment]
[Low level peer sharing](https://github.com/input-output-hk/ouroboros-network/wiki/Peer-Sharing-Planning) design is completed
