### ISSUE TITLE
Anti-diff prototype

### ISSUE THREAD

**Issue by jorisdral** [input-output-hk/ouroboros-network#3946]
# Problematic performance for sequences of diffs

We replayed the mainnet chain from Genesis and reached Alonzo. During our performance tests we found out that 20% of the time is spent in the flushing operation. This can be brought down to 14% by flushing less frequently, but after a certain threshold decreasing the flushing frequency no longer decreases the time spent in this operation. This threshold was found to be flushing around 1K blocks.

The vast majority of the cost belongs to `Map.unionWith` which is used to implement the `<>` method for the `Semigroup` instance for `SeqUtxoDiff`, which in turn is called by the split operation of the fingertree data structure (which forces the computation of the intermediate measures of the fingertree via the `Semigroup` `SudMeasure` instance) which in turn is needed to flush.

Therefore we have to try to design an alternative approach to maintaining the sequence of differences (which is the data structure used when flushing to disk).

Maybe such an alternative is not feasible, or has other tradeoffs that are less acceptable than the slowdown that the current flush operation has. In this case we might need to optimize the existing implementation, and in the worst-case scenario we might need to accept the performance loss.

## Goals
- [x] (1) Elaborate a design and prototype to determine if this approach is feasible.
- [x] (2) If the approach is feasible, compare the performance of the prototype's "new" approach to the performance of the "legacy" implementation.

# (1) Prototyping the anti-diff approach

One approach to solving the problem described above is to keep track of a total/top-level cumulative diff, instead of caching cumulative diffs for sub-sequences of the diff sequence. If we can represent diffs as "negative" diffs, we could update this top-level cumulative diff by adding/subtracting diffs, instead of reconstructing the cumulative diff from precomposed subs-sequences of diffs. This should lead to a constant number of sum operations, instead of a logarithmic number of them.

In this approach:
* anti/inverse diffs are applied to either the left or right side of the total cumulative diff to allow for fast splits when rolling back or flushing to disk.
* new differences that arise from block applications are applied to the right side.

## Example

The example below illustrates the anti-diff approach. We consider a number of consensus-relevant operations on diff sequences and how these affect the top-level cumulative diff. These operations are: Push, flush and rollback. 

```
Individual diffs:  [1, 2, 3, 4]
Cached total diff: 1+2+3+4
```

### Adding/pushing diffs: add diffs to the right end of the diff sequence

```
[1, 2, 3, 4] -> [1, 2, 3, 4, 5]
1+2+3+4      -> 1+2+3+4+5
```

### Flushing diffs: split the diff sequence/take diffs on the left end of the diff sequence.

We have (at least) two options:
* We create fresh diffs on the left side, and we sum its inverse on the left of the right side.
```
[1, 2, 3, 4, 5] -> ([1], [2, 3, 4, 5])
1+2+3+4+5       -> (1,   (-1) + (1+2+3+4+5))
```
```
[1, 2, 3, 4, 5] -> ([1, 2], [3, 4, 5])
1+2+3+4+5       -> (1+2,    (-(1+2)) + (1+2+3+4+5))
```

* We sum the inverse on the (right of) the left side, and we sum the inverse on the (left of) the right side
```
[1, 2, 3, 4, 5] -> ([1],                     [2, 3, 4, 5])
1+2+3+4+5       -> ((1+2+3+4+5) - (2+3+4+5), (-1) + (1+2+3+4+5))
```
```
[1, 2, 3, 4, 5] -> ([1, 2],                  [3, 4, 5])
1+2+3+4+5       -> ((1+2+3+4+5) - (3+4+5), (-(1+2)) + (1+2+3+4+5))
```

We should use the first option: we expect the left side of the split to be the smaller than the right side. That is, the remaining diff sequence should be much larger than the part that we flush.

### Rolling back diffs: split the diff sequence/take diffs on the right end of the sequence

We have (at least) two options:
* We create a fresh top-level measure after rolling back.
```
[1, 2, 3, 4, 5] -> [1, 2, 3] -> [1, 2, 3]
1+2+3+4+5       -> {}        -> 1+2+3
```
* We sum the inverse on (the right of) the total cumulative diff. 
```
[1, 2, 3, 4, 5] -> [1, 2, 3]
1+2+3+4+5       -> (1+2+3+4+5) + (-(4+5))
```

We should use the second option: we expect the right side of the split to be smaller than the left side. That is, the remaining diff sequence should be much larger than the part that we roll back.

# (2) Comparing performance

Finally, we need a benchmark setup where we can sample the performance of the current "legacy" implementation, and the "new" anti-diff approach. 

The benchmark should measure the time of applying a sequence of the following operations to a diff sequence:
* Push (insert on the right).
* Flush (split the sequence at a given point/take on the right side).
* Rollback (split the sequence at a given point/take on the left side).
* Forward (apply the differences in the sequence up to the tip).

The benchmarks should present at least the results for this configuration:
* An equal number of forward and pushes.
* 1 flush per every 10 pushes.
* 1 rollback every 100 pushes

**Comment by jorisdral** [comment]
Some of follow-up issues I can think of:
* Integrate the anti-diff version of diff sequences in consensus.
* Benchmark consensus with the new diff sequences.
* Move the `anti-diff` package into `cardano-base` or a separate repository if it proves to be stable enough.
* Remove the "legacy" diff sequence implementation (**if** we decide to replace it).
* Move the `semigroupoid` package into a separate repository, or remove it altogether (we might not *really* need the type classes for groupoid-like structures, but the test utilities for testing type class laws are probably useful).

**Comment by Jasagredo** [comment]
Closed as the branch was merged.
