### ISSUE TITLE
Test the ledger interface used by the mempool

### ISSUE THREAD

**Issue by Jasagredo** [input-output-hk/ouroboros-network#3966]
We mock the LedgerInterface and in particular getLedgerStateForTxs. It seems we need to add tables to the mempool to exercise the part of the mempool logic that deals with them. Which options do we have?

Option 0: Mock the LedgerInterface with ledger tables. The problem with this is that we'd still need to test mempool implementation.

Option 1: use the actual ledger interface:

```
chainDBLedgerInterface ::
     ( IOLike m
     , LedgerSupportsMempool blk
     )
  => ChainDB m blk -> LedgerInterface m blk
```

The problem with this is that it requires an actual Chain DB! So this might require significant modifications to the mempool-test code.

First, we need to test the correctness of getLedgerStateForKeys, which is part of the ChainDB API. Why? Because getLedgerStateForTxs relies on this function.

Second, we could use chainDBLedgerInterface if we could find a way to generate arbitrary ChainDB's and add this to TestMempool.

**Comment by Jasagredo** [comment]
This is on hold because we might do a mempool rewrite instead

**Comment by dnadales** [comment]
This should be fixed by https://github.com/input-output-hk/ouroboros-network/issues/4044
