### ISSUE TITLE
Fix the no-thunk tests failures

### ISSUE THREAD

**Issue by yogeshsajanikar** [input-output-hk/ouroboros-network#4006]
With strict-stm `checktvarinvariant` flag turned on, there are tests which fail due to presence of the thunk. Review and fix the tests. In case, thunks are required, add the necessary exceptions as mentioned in https://well-typed.com/blog/2020/09/nothunks/ using _AllowThunksIn_

blocks #3001

**Comment by yogeshsajanikar** [comment]
The `Cardano.Ledger.Shelley.UTxO` wraps `Map (TxIn era) (TxOut era)`. The map is used in more than 40 files in `cardano-ledger`, and few locations in `ouroboros-network`. The thunk appears in `TxOut` which is generated at various places. While fix can be very small, it is taking time to change and check for strictness in all these places. 

Current approach is to replace `Map` by `SMap` (a wrapper around map) and to add checking code to capture the thunk leak where it was introduced.

**Comment by dnadales** [comment]
If the change affects the ledger we should give the team a head up. CC: @lehins

**Comment by lehins** [comment]
> Current approach is to replace Map by SMap (a wrapper around map) and to add checking code to capture the thunk leak where it was introduced.

@yogeshsajanikar I think the easier way to find the thunk would be to go through all imports `import qualified Data.Map as Map` in ouroboros-consensus where `UTxO` is being used and replace it with `import qualified Data.Map.Strict as Map`. We've switched to strict Map interface in ledger a while ago, so it is unlikely to be coming from ledger. See:
```
$ git grep "import qualified Data.Map "
...
```

**Comment by yogeshsajanikar** [comment]
@lehins Please have a look at https://github.com/input-output-hk/cardano-ledger/pull/3143. All the fixes are related to application of lazy functor <$>.

**Comment by lehins** [comment]
@yogeshsajanikar Yeah, I saw that. I did not even think about the Functor instance for Map. Very good find.

**Comment by yogeshsajanikar** [comment]
Waiting for cardano to push their changes.

**Comment by fraser-iohk** [comment]
An overly-strict `NoThunks (ShelleyGenesis c)` instance (in `cardano-ledger`) was causing our invariant checks to fail -- this has been fixed in https://github.com/input-output-hk/cardano-ledger/pull/3461 and will hopefully be in the next `cardano-ledger` release

**Comment by fraser-iohk** [comment]
This ticket is being moved back into Ready as I'll be working on the 8.2 release for the next couple of weeks

**Comment by fraser-iohk** [comment]
Blocked (possibly) on https://github.com/input-output-hk/cardano-ledger/issues/3598
