### ISSUE TITLE
Implement a microbenchmark to isolate eras overhead

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/ouroboros-network#4021]
We need to measure what is the overhead that eras might add to the node, and obtain meaningful profiling information.

A possible way to do this is to use `db-analyzer` with [this enhancement](https://github.com/input-output-hk/ouroboros-network/pull/4014) to measure the cost of:

- forecasting
- ticking the header state
- applying the header 
- ticking the header ledger 
- applying the block

using a hardfork block, and a single era block.

To this end, we could modify the [`process`](https://github.com/input-output-hk/ouroboros-network/pull/4014/files#diff-b4c5b012cf5df0a833aec1ea61e295acd8c52d8a10d09cb5f284b0de532eaa89R510) function so that it performs the measured computations twice: once include hardfork envelope blocks and once without the envelope. The HFC _envelope_ is indeed very thin, and could be discarded for each of those 5 measurements except when the crossing the era boundary -- but 1) that is rare so we could just not compare the with-HFC and without-HFC for such blocks and 2) we could do something roughly approximate (tick up to the era boundary and translate before "discarding" the envelope).

A pre-requisite for solving this issue is to finish https://github.com/input-output-hk/ouroboros-network/pull/4014

**Comment by deepfire** [comment]
According to https://github.com/input-output-hk/cardano-node/issues/4213#issuecomment-1240611179 `getHeaderFields` is high on the profile.

**Comment by dnadales** [comment]
@deepfire  @nfrisby, in light of the results observed in https://github.com/input-output-hk/ouroboros-network/pull/4014, it seems that Eras do not have any overhead. I wonder if we should close this one.
