### ISSUE TITLE
Gather benchmark data for the latest UTxO HD version

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/ouroboros-network#4040]
We need to rebase the UTxO HD feature branch to the latest working version of the node, and benchmark:

- Baseline syncing from scratch.
- UTxO HD synching from scratch.
- Baseline replaying the chain.
- UTxO HD replaying the chain.

We should also compile a document with up-to-date benchmark data. We need a single document we can use to discuss our performance measurements with other teams. This could be temporarily placed in `ouroboros-network`.

**Comment by dnadales** [comment]
@deepfire does the benchmarking team have tooling for running these benchmarks and plotting the results, similar to what @Jasagredo has:



![Image](https://user-images.githubusercontent.com/175315/196922563-d0d05095-0dfa-4da3-9ce8-cdf492df7111.png)

**Comment by Jasagredo** [comment]
We are going to perform the following runs:
- input-output-hk/cardano-node@consensus/feature/utxo-hd-baseline
- input-output-hk/cardano-node@consensus/feature/utxo-hd with `--lmdb-ledger-db-backend --lmdb-mapsize 16`
- input-output-hk/cardano-node@consensus/feature/utxo-hd with `--in-memory-ledger-db-backend`

We will measure 
- wallclock time
- memory consumption 
- graph the block number vs time. 
 
We will do:
- replay up to slot X (TBD)
- full sync up to slot X (TBD)

If we find it appropriate we will perform the same experiments again but on a memory constrained setup.

**Comment by Jasagredo** [comment]
Blocked by input-output-hk/ouroboros-network#3954. The backing store tests will probably alter the backing store behavior and therefore it is more sensible to wait until those are merged.

**Comment by Jasagredo** [comment]
Another important thing to measure which is related to #4071 is to measure querying the utxo by address in each implementation.

**Comment by Jasagredo** [comment]
# Replaying up to slot 75M

![replay](https://user-images.githubusercontent.com/9791461/211755738-e0ac0651-078a-493c-bafa-e88c0a516dea.png)

As expected the LMDB implementation doesn't reach 8GB of memory (RSS) but it takes 1,78x seconds to replay the chain.

**Comment by dnadales** [comment]
Could this be closed by https://github.com/input-output-hk/ouroboros-network/pull/4295

We might need to add Javier's plots.

**Comment by Jasagredo** [comment]
Yes. Probably it is worth adding the plots
