### ISSUE TITLE
Cardano eras transitions tests

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/ouroboros-network#4043]
- [x] Write tests for all the Cardano transitions. 
    - [x] Byron to Shelley
    - [x] Shelley to Allegra
    - [x] Allegra to Mary
    - [x] Mary to Alonzo 
    - [x] Alonzo to Babbage
- [x] Add to the `AddingAnEra.md` document instructions to add a new era translation test when adding a new era.

If we can generate arbitrary ledger states of each Cardano era we can write property tests. Otherwise, we'll have to resort to unit tests.

# Byron to Shelley 
Ensure that *all the UTxO* is transferred from in-memory Byron state (which has no tables) to the ledger tables of the Shelley state. The result must consist only of insertions (which are present in the resulting diffs).

# Shelley to Allegra
Ensure that the *avvm* addresses appear as deletions in the resulting diffs.

# All remaining transitions
Ensure that the resulting diff is empty, which means no modification to the ledger tables will be made from one era to the next.

**Comment by Jasagredo** [comment]
Should we close this issue as completed? @bartfrenk @dnadales

**Comment by dnadales** [comment]
Indeed.
