### ISSUE TITLE
Property-test the mempool with ledger tables

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/ouroboros-network#4044]
Write state machine tests (using either QC dynamic or QC state-machine) to exercise the mempool API, including concurrent access to it (checked using `prop_parallel` in QC state-machine). 

For UTxO HD, we need the mempool API to be defined and relatively stable before starting this task (see https://github.com/input-output-hk/ouroboros-network/issues/4035), however, we could start writing the tests for the baseline version.

To test the mempool we will need to use a test-block. At the moment there are different test blocks in the system. For simplicity we could create an additional test block. @Jasagredo worked on the unification of test blocks (see #3965) however the task involves an enormous amount of changes non-related to UTxO HD, therefore we currently prefer to create a new type of test block.

**Comment by Jasagredo** [comment]
Currently blocked by #4161

**Comment by Jasagredo** [comment]
This only needs cleanup and should be ready to review
