### ISSUE TITLE
Consensus sign off on component level tests

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/ouroboros-network#4045]
This issue enumerates the *component level* tests that need to pass to give the UTxO HD feature a green light for downstream integration.

- [x] #3998
- [x] #4043
- [x] #3954
- [x] #4044
- [x] #4270
- [x] #4271
- [x] ChainDB.getLedgerBackingStoreValueHandle. One fundamental property we want to check is that the backing store view remains invariant to operations in the legder. This test could be written using operations on the ledger DB, thus avoiding the need for adding tables to the test blocks used in the `ChainDB` tests (TODO create issue).
- [x] #4171 
- [x] #3950

**Comment by jorisdral** [comment]
The proposed `ChainDB.getLedgerBackingStoreValueHandle` test is subsumed by the model-based tests that are introduced in #3954. The model mocks value handle in such a way that they have a consistent view of the database state at the time the value handle is created. This view is invariant under operations to the backing store itself. If a `BackingStore` implementation were to create value handles that do not have this consistent view property, the tests will likely fail.
