### ISSUE TITLE
Validate prototype by drafting future steps for other tables

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/ouroboros-network#4074]
Until now we have only had the UTxO table on the UTxO-HD prototype. In the foreseeable future, we will add more tables to the implementation, possibly delegations. 

We should add some other table to the prototype to make sure that we will be able to do so in the future without major modifications to the prototype. The table might be trivial, but it should give us enough confidence that we will be able to support other types of tables that can capture the other large maps that exist in the ledger state.

# Possible approach 

A possible way to approach this is to use SOP in the `LedgerStateKind`:

```haskell
type MapKind = Type -> Type -> Type -> Type
type LedgerStateKind = NP MapKind '[UTxO :: Type, OtherMap] -> Type

data LedgerTables (LedgerState ByronBlock) mk = NoByronLedgerTables

newtype LedgerTables (LedgerState (ShelleyBlock proto era)) mk = ShelleyLedgerTables { 
  npTables :: ZipUncurry mk [ (SL.TxIn (EraCrypto era), Core.TxOut era)    -- k and v for UTxO
                            , (OtherKey era,            OtherValue era) ]  -- k and v for OtherMap
  }
```

In this way, functions that deal with tables would become `NP`s of functions. For example:

```haskell
mapLedgerTables :: NP (mk1 -.2-> mk2) KVs -> LedgerTables l mk1 -> LedgerTables l mk2
``` 

(`-.2->` is meant to be like `-.->` but applies to 2 types, key and value)

**Comment by Jasagredo** [comment]
The general plan ahead seems to be the following:

### Phase 1 - Extracting the common behavior of `TableStuff`

- Extracting `mapLedgerTables` etc from `TableStuff` because they are the same for ~every instance (and in particular they are isomorphic to unitary `NP`s, and byron is isomorphic to just `NP .. '[]`)

- Redefine all instances to depend on this new abstraction, perhaps this is even easier and `Ledger.Basics` can define a general instance. We would just need to require it when defining each ledger state.

### Phase 2 - Lifting the tables into SOP

- Make the tables an NP 

```haskell
type Zip :: [a] -> [b] -> [(a, b)]
type family Zip as bs where
  Zip (a : as) (b : bs) = '(a, b) : Zip as bs
  Zip _ _ = '[]

type ApplyPair :: (a -> b -> Type, (a, b)) -> Type
newtype ApplyPair fp = ApplyPair { getApplyPair :: Fst fp (Fst (Snd fp)) (Snd (Snd fp)) }

type ZippedNP :: [a -> b -> Type] -> [(a, b)] -> Type
newtype ZippedNP fs ps = ZippedNP (NP ApplyPair (Zip fs ps))

infixr 5 ::*

pattern (::*) :: f a b -> ZippedNP fs abs -> ZippedNP (f : fs) ('(a, b) : abs)
pattern fab ::* fabs <- ZippedNP (ApplyPair fab :* (ZippedNP -> fabs))
  where
    fab ::* (ZippedNP fabs) = ZippedNP (ApplyPair fab :* fabs)

pattern ZipNil :: ZippedNP '[] '[]
pattern ZipNil = ZippedNP Nil

{-# COMPLETE (::*), ZipNil #-}
```

- Each instance from Phase 1 can be then lifted into the instance for a unitary table, something along the lines of 

```haskell
-- defined for each ledger?
instance TableStuff ... '[x] where
  mapLedgerTables = ...
  ...
```

- The TableStuff class will have a type level list as its last argument with the list of tables
```haskell
class TableStuff ... xs where
  ...

-- defined in `Basics`?
instance All (TableStuff ...) xs => TableStuff ... xs where
  ...

```

where the general instance can be defined using some kind of injection using `Index`  (or some other Peano like type level natural), an NP would be "easily" mapped on one component using something like this:

```haskell
type family Replace (i :: Index xs y) y2 xs where
  Replace 'IZ x (y ': ys) = (x ': ys)
  Replace ('IS n) x (y ': ys) = y ': (Replace n x ys)

-- Maybe not singletons? Maybe proxys? Maybe Nat?, this is just a skeleton
foo :: forall r xs y (i :: Index xs y). SingI i => Sing i -> (f y -> f r) -> NP f xs -> NP f (Replace i r xs)
foo theSing f (x :* xs) = case theSing of
   SIZ -> mapLedgerTables f (UnitaryTables x) :* xs
   SIS n -> x :* foo n f xs

```

**Comment by Jasagredo** [comment]
Phase 1 implemented in #4234

**Comment by Jasagredo** [comment]
Despite this plan allowing for *extremely* expressive semantics, it was noted by @nfrisby that (1) the cost of maintaining this might be too much and (2) we don't really need "arbitrary lists of tables", we will only have to define a handful of tables at most.

So I'm leaving this in favor of the much simpler design:

- [x] Phase 1 - move `TableStuff` to `Ouroboros.Consensus.Ledger.Tables` (didn't need to be this PR but incidentally that is what it ended up like) #4234
- [ ] Add a second `MapKind` variable to the `LedgerStateKind` which controls the second ledger table. Functions now will have to be duplicated/a tag has to be given.

**Comment by Jasagredo** [comment]
On hold waiting for a meeting with the Ledger team which is bound to happen later this week or at most next week

**Comment by Jasagredo** [comment]
The meeting with the ledger took place, now the remaining step is to flesh out the outcomes on an MD document. In general it seems the UTxO-HD tables framework will also work for the remaining tables.

**Comment by Jasagredo** [comment]
The sketch was merged, so closing!
