### ISSUE TITLE
🌎 Better Open Source

### ISSUE THREAD

**Issue by vfrsilva** [input-output-hk/ouroboros-network#4105]
The overall goals are to:

- build a collaborative framework to greatly grow the adoption of Cardano amongst Blockchain community
- make it easier for 3rd party DeXs and DApp developers to share knowledge and lessen the barrier to entry using worked artefacts and knowledge captures
- Build a knowledge base of best practice within code bases that creates consistency across the business
- Provide increasing opportunities to collaborate across teams and flex resources across different teams
- Enhance quality of the repo stack to include how-to, decisions made, and recipes to build new applications on Cardano

We will initially aim to open up the node backlog, publish test results and make performance data generally accessible

**Comment by coot** [comment]
* We made a substantial progress documenting how to contribute to all the repositories related to `cardano-node`. See https://github.com/orgs/input-output-hk/projects/60/views/5.
* We also moved to [`CHaP`](https://github.com/input-output-hk/cardano-haskell-packages/) which makes it easier for the ecosystem to cooperate.
* We have an [open backlog](https://github.com/orgs/input-output-hk/projects/19/views/12).
