### ISSUE TITLE
Incorporate ideas from Byzantine Consensus under Fully Fluctuating Participation ?

### ISSUE THREAD

**Issue by L-as** [input-output-hk/ouroboros-network#4137]
Feel free to close this issue, just wanted to make sure its ideas have been seen by the Ouroboros team.
Link: https://eprint.iacr.org/2022/1448

**Comment by dnadales** [comment]
Thank you for the head up. This might be more suitable in a medium in which IOG scientists participate. I'm going to relay this to them.
