### ISSUE TITLE
Provide an hyperlinked map of consensus modules

### ISSUE THREAD

**Issue by abailly-iohk** [input-output-hk/ouroboros-network#4149]
## Context 

* graphmod allows to display the dependencies among Haskell modules as a graph
* We want to provide a useful "map" of the consensus code base, displaying key modules/components and their relationships
* A map should help to navigate hence provide links to important parts of the system

## Goal

* goal of this task is to use existing graphmod script to generate an hyperlinked map of consensus modules grouped by components

**Comment by abailly-iohk** [comment]
I have a slightly modified version of [graphmod](https://github.com/yav/graphmod) that's able to produce a module dependency graph with hyperlinks. That's only a first step but one we can enrich later. Where would it be best to put this? In the prolog of the haddocks for ouroboros-network? In a standalone `Ouroboros.Consensus.Doc` module?
Java has the concept of package-level documentation which one can put in the modules' directory structure to document some grouping of classes, I wish Haskell had something similar.

**Comment by abailly-iohk** [comment]
Alternative: How about using the `ouroboros-consensus/docs` directory as the basis for some technical site to be published? We did this for hydra: The haddocks are generated in the CI and published as a subdirectory of the docs which are then transformed as web pages.

**Comment by dnadales** [comment]
> Where would it be best to put this? In the prolog of the haddocks for ouroboros-network?

I'd say so. We want this map to be one of the first things the reader sees, don't we? 

> Alternative: How about using the ouroboros-consensus/docs directory as the basis for some technical site to be published?

Sure, a documentation page like the one from hydra makes a lot of sense.
