### ISSUE TITLE
Clarification on `Tip` in Chain-Sync Messages

### ISSUE THREAD

**Issue by jmhrpr** [input-output-hk/ouroboros-network#4190]
The server's current chain-tip is also passed to the client in a number of the Chain-Sync messages, such as MsgRollforward. I'm dealing with these messages with Pallas (Rust library implementing Ouroboros, N2N to IOG node) and it appears that the Tip is one block behind the real tip, or more precisely that when following the tip the received MsgRollforward(`next_block_header`, `tip`)  the `tip` is one block behind `next_block_header`. I would have thought that `tip` would be equal to `next_block_header` as it is the most recent block. I was just wondering what the logic is here or if this is a bug?

For example, this is a parsed MsgRollforward message where you can see the tip is one block behind the requested next block header:

```
rolling forward, header: (77912810,08a844eebeaaf88dc58ea4867d8da29689e5e11121e126180d6aa8f9ab2e292e,8063366), tip: Tip((77912779, 6c7f6ad4cba4c89960aed95c54086185161457d5c6de76de526cf1e6b54a3075), 8063365)
```

**Comment by jmhrpr** [comment]
Thanks! That makes sense. Some quick related questions:

1.) As the client, can we signal that we don't want pipelining to be used in the communication/we don't want to receive invalid blocks?
2.) Alternatively, as the node operator, can we configure the node to not use block diffusion pipelining?
3.) Is block diffusion pipelining only used on N2N chainsync or on N2C as well?

TIA!

**Comment by amesgen** [comment]
> 1.) As the client, can we signal that we don't want pipelining to be used in the communication/we don't want to receive invalid blocks?

No, that is currently not possible in N2N ChainSync, as there isn't really a reason to say "I don't want to adopt blocks as fast as possible.".

> 2.) Alternatively, as the node operator, can we configure the node to not use block diffusion pipelining?

Right now, we don't offer such a configuration option. Just like before, there isn't really a reason to say "I want my node to diffuse blocks less quickly than possble". But it would be trivial to add if someone would find a compelling use case.

> 3.) Is block diffusion pipelining only used on N2N chainsync or on N2C as well?

It is only used in N2N ChainSync, as it is an optimization for block diffusion, and N2C is not related to that.

> 4.) If the server sends a MsgRollforward for an invalid block, will it immediately send a MsgRollback when it finishes validating the block and realises it is invalid?

Exactly.

---

Hope this helps!

**Comment by jmhrpr** [comment]
Thanks for the quick response! Just for some context, TxPipe's community tools like [Oura](https://github.com/txpipe/oura) and [Scrolls](https://github.com/txpipe/scrolls) pull blocks from either a N2C source (local node) or N2N source, and then process them without validation (because being able to validate them would mean having full-node capabilities). This was fine before pipelining, because even though you don't validate the blocks you are receiving them from a trusted source which has validated them, but now with pipelining even an honest node can forward invalid blocks so that assumption is no longer true for N2N.

It's not the end of the world because using a N2C source is quicker, safer, and just generally more suitable anyway, but it was nice that N2N meant you didn't really need to run a node, you could just use IOG's relay for example. And if the client can't specify that they don't want to receive pipelined blocks over N2N then maybe they just wait a second after receiving it to see if they receive a MsgRollback because the block was deemed invalid by the server.
