### ISSUE TITLE
Use cardano-ledger-binary serialization

### ISSUE THREAD

**Issue by yogeshsajanikar** [input-output-hk/ouroboros-network#4240]
## Integrate using `cardano-ledger-binary`

Ledger has added support for _versioning_ in the binary serialization. The ledger code is using this library for serialization. Since consensus types are dependent upon ledger, it should be integrated into consensus. It's also a build-breaking change for consensus.

```haskell
newtype Encoding = Encoding (Version -> C.Encoding)
```
[Link](https://github.com/input-output-hk/cardano-ledger/blob/74fc976f7fdee064d1b6e6d1564ed7e533d364c2/libs/cardano-ledger-binary/src/Cardano/Ledger/Binary/Encoding/Encoder.hs#L119)

* `ToCBOR` and `FromCBOR` classes are added to support the above encoding. It is possible to add conditional serialization based on version. 
* This is a wrapper over `Cardano.Binary` and `Codec.CBOR` 

### Issues
+ The types such as `ChainValidationState` may not need versioning support. 
+ Codec `Serialise` class also should be ported to cardano-ledger-binary. This will simplify integration, and will also possibly help other users.

**Comment by lehins** [comment]
This ticket can be closed since we've already integrated versioned serialization in #4349
