### ISSUE TITLE
Refactor how modules are re-exported

### ISSUE THREAD

**Issue by Jasagredo** [input-output-hk/ouroboros-network#4254]
The insane amount of changes we have to do every time we refactor makes me wonder if we shouldn't have a module `Ouroboros.Consensus.Ledger` which re-exports the public things of `Ouroboros.Consensus.Ledger.*`.

_Originally posted by @dnadales in https://github.com/input-output-hk/ouroboros-network/pull/4234#discussion_r1054304512_

**Comment by dnadales** [comment]
Just for context, this isn't UTxO HD specific, is it?

**Comment by Jasagredo** [comment]
This in fact was ~solved by the LedgerDB and Mempool reworks. I'm going to close this
