### ISSUE TITLE
Volatile DB: Duplicate Blocks

### ISSUE THREAD

**Issue by kderme** [input-output-hk/ouroboros-network#430]
Edsko mentioned at slack:

@kderme we need to change the behaviour of teh volatile DB a little bit wrt to duplicate blocks
and concurrent access to the volatile DB
let's do that tomorrow
1. multiple concurrent calls to addBlock should work, but are permitted to result in duplicate blocks on disk (best effort to avoid this is sufficient -- check in the beginning if ti's already in the index, but don't try to hold a lock)

2. this means there is the possibility of two threads both writing the same block, which is okay -- means we need to allow for this during startup
3. document a guarantee that the index will have been updated after we return from addBlock

**Comment by edsko** [comment]
In an ideal world we'd also have a test for this, but I don't know how expensive it would be (in terms of manpower) to extend the qsm to do this. If too expensive, then a separate, simple tests with multiple threads writing blocks might suffice.

**Comment by mrBliss** [comment]
Currently, the VolatileDB doesn't support multiple concurrent writes. Its internal state is stored in a `TMVar` and whenever it is modified, e.g., when putting a block, we take the `TMVar` using `modifyState` and put it back after we're done modifying the state. This `TMVar` functions as a lock and serialises all writes to the VolatileDB.

So when two concurrent calls to `putBlock`for the same block happen, only one of them can obtain the lock and write the block. When this is done, the other call will notice that the block is already in the VolatileDB and will just return.

@edsko Are you suggesting we try to get rid of this locking behaviour?

**Comment by edsko** [comment]
Yes, this oversequentializes. Basically it should look like

```
blockAlreadyInDB <- checkInDB
unless blockALreadyInDB $ 
  writeBlockToDisk
  updateIndex
```

Of course this then leaves a race condition; the block might be on disk twice. But that's not a disaster and holding the lock whenever we write a block to disk reduces concurrency in the network layer too much.

**Comment by kderme** [comment]
`writeBlockToDisk` should also be protected by some write lock, so that we won't have two concurrent writers at the same file. At the unix implementation, open handles come with an MVar, 
```
data FHandle = FHandle FilePath (MVar (Maybe Fd))
  deriving Eq
```
however it would be unreliable to depend on this, since it is too low in the abstraction layer. I see 2 options:
- Create write locks in the volatile db.
- move the open handle MVars higher in the abstraction. This could also facilitate other issues, like https://github.com/input-output-hk/ouroboros-network/issues/285 (I think we would need to lock writes for windows also) and https://github.com/input-output-hk/ouroboros-network/issues/277 (partial reads and writes mean we may need to do multiple system calls. There is no need to lock and unlock for each one)

**Comment by edsko** [comment]
Hmmm but the whole idea is that we _do_ have concurrent writes. But I do take your point. Not actually too sure what @dcoutts had in mind here. Perhaps we should be writing to multiple files, rather than just the one..? Let's discuss this with @dcoutts .

**Comment by edsko** [comment]
Ok, discussed this again with @dcoutts and we can close this as WONTFIX for now. _If_ we change the network layer to _stream_ blocks to disk as they are being downloaded, we may wish to reconsider this. In that case it might be worthwhile reserving some space in the file for the block being downloaded (would mean that we'd need to know the size upfront, of course), and then write to that whilst other blocks are written concurrently also. But for now, we can close this.
