### ISSUE TITLE
Record flushing constant for UTxO-HD

### ISSUE THREAD

**Issue by jasagredo** [input-output-hk/ouroboros-network#4308]
We should record `100` somewhere as a constant in the `OnDisk` module, and let the actual `flush` function and this local definition refer to it. Otherwise the implementation and this analysis are likely to get out of sync if we change the flush frequency

_Originally posted by @jorisdral in https://github.com/input-output-hk/ouroboros-network/pull/4301#discussion_r1084169241_

**Comment by Jasagredo** [comment]
Closed in favor of #4402
