### ISSUE TITLE
Generate a better site for `ouroboros-consensus` (eg searchable, styled according to other IOG projects, etc).

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/ouroboros-network#4324]

**Comment by abailly-iohk** [comment]
Got docusaurus setup with docs and basic links setup. Still need to figure out what to put in the central hero unit...

![Screenshot 2023-02-07 at 10 17 39](https://user-images.githubusercontent.com/79840582/217202922-140de1e8-45d4-41a1-9a57-c1cd672983c1.png)

**Comment by dnadales** [comment]
Solved by https://github.com/input-output-hk/ouroboros-consensus/pull/6
