### ISSUE TITLE
Bump text to support 2.0

### ISSUE THREAD

**Issue by jonathangenlambda** [input-output-hk/ouroboros-network#4380]
We tried to bump our repos to use text-2.0 however ran into an issue with [ouroboros-consensus not supporting it](https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-consensus/ouroboros-consensus.cabal#L322)

**Comment by coot** [comment]
We already support `text-2.0`.

**Comment by coot** [comment]
But I am not sure if [`ouroboros-consensus`](https://github.com/input-output-hk/ouroboros-consensus) does support it.
