### ISSUE TITLE
Improving tracing for `BackingStore` implementations

### ISSUE THREAD

**Issue by jorisdral** [input-output-hk/ouroboros-network#4396]
As suggested in https://github.com/input-output-hk/ouroboros-network/pull/4366#discussion_r1109921883, we should stop using `nullTracer` for tracing `BackingStore` operations. As a side task, we should see whether we can improve the messages that are currently being traced.

**Comment by Jasagredo** [comment]
This was addressed partially in the LMDB PR. There are now traces for the memory backend, so maybe we can close this issue? @jorisdral
