### ISSUE TITLE
Turn CDDL test into automatic test in CI

### ISSUE THREAD

**Issue by dcoutts** [input-output-hk/ouroboros-network#442]
In PR #414 Marc added an exe for testing our binary formats against external CDDL specs.

A follow-up from this is to make it run automatically in CI by turning it into a cabal `test-suite` in the .cabal file. Will probably also want to check the volume of output to make sure it's appropriate for CI.

The test probably wants to be optional controled by a cabal flag, since it has a dependency on the external CBOR/CDDL tools.

**Comment by MarcFontaine** [comment]
merged as PR #491
