### ISSUE TITLE
Investigate if batching the query to the BStore in the mempool make a difference

### ISSUE THREAD

**Issue by jasagredo** [input-output-hk/ouroboros-network#4444]
We currently query the backing store for the keys and values of each transaction when adding them. Perhaps it would be worth batching those queries.

**Comment by dnadales** [comment]
FTR: this might conflict with https://github.com/input-output-hk/ouroboros-network/pull/4436

**Comment by jasagredo** [comment]
I think this could be closed as not applicable, now that we add one tx at a time
