### ISSUE TITLE
Chain DB: Protect against unintended file deletion

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#445]
All of the ImmDB, VolDB and LedgerDB will delete files that they try but fail to open. If the user somehow points the node to the wrong directory, and it happens to have a `volatile`, `immutable` or `ledger` subdirectory, we probably don't want to randomly start deleting files ("Cardano deleted all my files!" :-o ). It would be good to somehow protect against this (though not entirely sure how).

**Comment by mrBliss** [comment]
Notes:

* Look at what other DBs do

* We can add a special file with a magic number (network magic, a separate number for different test/mainnets) in the directory. If this special file is corrupt, we can't recover: this will result in a hard failure on start-up. We should do that for each of the three DBs. When that file is created the first time, the directory should be empty.

* Make sure the naming scheme of the files of the different DBs is specific: e.g., `(epoch|index)-%03d.dat` for the Immutable DB. The other two DBs currently use plain numbers for the files,  this should be fixed.

**Comment by mrBliss** [comment]
Feature added in #1123 and enabled in #1244.
