### ISSUE TITLE
Scale FS StateMachine tests with `--quickcheck-tests`

### ISSUE THREAD

**Issue by Jasagredo** [input-output-hk/ouroboros-network#4455]
Should this use scaling according to the tasty `--quickcheck-tests` option instead of a fixed number?

_Originally posted by @jorisdral in https://github.com/input-output-hk/ouroboros-network/pull/4363#discussion_r1120270700_

**Comment by jorisdral** [comment]
The tests were moved to https://github.com/input-output-hk/fs-sim when the `fs-sim` code was migrated to its own repository, so I think we can close this one?
