### ISSUE TITLE
Query - Keep connection open with cardano node after handshake

### ISSUE THREAD

**Issue by ashisherc** [input-output-hk/ouroboros-network#4510]
I want to talk Local Transaction Submission Mini protocol. I'm using the Local chain sync protocol and it works well, though when I tried using only the local transaction submission mini protocol, I am unable to keep the connection open after the handshake. 

Below Scenario works,

1. Do the handshake
2. Get an accepted response
3. After (2), quickly send chain sync find intersect msg, and then post no messages. The connection is kept open by the Cardano node, so I can send new msg whenever I want.

The below does not work,

1. Do the handshake
2. get an accepted response
3. I want to submit a tx but after a while, the Cardano node closes my connection in a few seconds

**Comment by coot** [comment]
What version of `cardano-node` are you using?  I thought that we fixed this in #3844.

**Comment by ashisherc** [comment]
1.35.5, node running in p2p mode. Works fine with non-p2p mode

**Comment by ashisherc** [comment]
@coot yep it's fixed in the latest node release. sorry for the confusion. Thanks!
