### ISSUE TITLE
Add a tool to truncate the ImmutableDB

### ISSUE THREAD

**Issue by amesgen** [input-output-hk/ouroboros-network#4512]
There are several use cases (benchmarking, disaster recovery, etc.) where one might want to truncate an existing ImmDB to a specific slot. The goal of this ticket is to implement this as a standalone tool, e.g. `db-truncate`, that lives next to `db-analyser` in `ouroboros-consensus-cardano-tools`.

By default, the immutable DB creates one chunk file every $10 \cdot k = 21600$ slots (where $k$ is the security parameter) (see [here](https://github.com/input-output-hk/ouroboros-network/blob/e4a222f8e0f5d55591cc14b062332a8a61e85724/ouroboros-consensus-shelley/src/Ouroboros/Consensus/Shelley/Node/Common.hs#L100-L108) for the code), so in order to truncate to a slot that is a multiple of this it suffices to simply delete all chunk files beneath this point.

To support intra-chunk truncation, we have to reach for the ImmDB API (see section 8.2 in the [report](https://input-output-hk.github.io/ouroboros-network/pdfs/report)), e.g. the internal [`deleteAfter`](https://input-output-hk.github.io/ouroboros-network/ouroboros-consensus/Ouroboros-Consensus-Storage-ImmutableDB-Impl.html#v:deleteAfter_).

**Comment by deepfire** [comment]
@amesgen, we'd like this to be implemented as library functionality -- so this can be called from `db-synthesizer`.

cc @mgmeier
