### ISSUE TITLE
Upgrade ouroboros-network to build with ghc-9.6

### ISSUE THREAD

**Issue by erikd** [input-output-hk/ouroboros-network#4536]
* [x] Make it build.
* [x] Add it ti CI.
* [x] Upload to CHaP

**Comment by coot** [comment]
btw, not too long ago I experimented with `ghc-9.6` and I was able to compile with just a few entries in `allow-newer` in `cabal.project.local` file.

**Comment by coot** [comment]
I think it was `cardano-binary:base`, `cardano-slotting:base`.

**Comment by coot** [comment]
It's already done :tada:

* https://github.com/input-output-hk/cardano-base/pull/392
* https://github.com/input-output-hk/cardano-prelude/pull/181

are new versions published to `CHaP`?

**Comment by erikd** [comment]
PR is https://github.com/input-output-hk/cardano-crypto/pull/87

**Comment by erikd** [comment]
More PR: https://github.com/input-output-hk/ouroboros-network/pull/4567

**Comment by erikd** [comment]
All that is still needed is a new version in CHaP.

**Comment by coot** [comment]
Now in `CHaP`: https://github.com/input-output-hk/cardano-haskell-packages/pull/300.
