### ISSUE TITLE
Inconsistencies between CDDL and protocol specification

### ISSUE THREAD

**Issue by michele-nuzzi** [input-output-hk/ouroboros-network#4578]
protocols specification: https://input-output-hk.github.io/ouroboros-network/pdfs/network-spec/network-spec.pdf

CDDL: https://github.com/input-output-hk/ouroboros-network/tree/master/ouroboros-network-protocols/test-cddl/specs

Example: TxSubmission2

`msgReplyTxs` is specified to return entire transactions; the CDDL spefies only tx ids (which doesn't make much sense if we need to resolve transactions ids)

also all hashes are specified to be `int` in the CDDL; where instead the protocol returns bytes (which makes more sense).

It would be great having the CDDL reflecting what the protocol expects.

**Comment by bolt12** [comment]
Thanks for raising this issue, but when I had a look myself, everything seemed to match the CDDL specs. But, hey, it's a complex topic, so maybe I've missed something.

Can you give me more specifics or point out exactly where in the docs you spotted these issues? That'd really help me to understand better what you're seeing.

**Comment by michele-nuzzi** [comment]
Sure, I'm playing with the cardano-node in nodejs; I have the following snippet.

all it does is
- connecting to the node using a TCP socket (node-to-node)
- add a bunch of listeners to see what is going on with the socket
- "negotiataes" version using handshake
- performs 2 requests for the ChainSync protocol

```ts
import { toHex } from "@harmoniclabs/uint8array-utils";
import { Socket, connect } from "net"
import { unwrapMultiplexerMessage, wrapMultiplexerMessage } from "./multiplexer/multiplexer";
import { MiniProtocol } from "./MiniProtocol";
import { N2NMessageProposeVersion } from "./protocols/handshake/n2n/N2NHandshakeMessage";
import { N2NHandshakeVersion } from "./protocols/handshake/n2n/N2NHandshakeVersion";
import { ChainSyncRequestNext } from "./protocols/chain-sync";

function connectAsync(): Promise<Socket>
{
    return new Promise( resolve => {
        let socket: Socket;
        socket = connect({ host: "127.0.0.1", port: 3000 }, () => (console.log("connected"), resolve(socket) ) );
    })
}

void async function test() {

    const socket = await connectAsync();

    socket.on("close", () => (console.log("close")));
    socket.on("error", (err) => console.log("received error: ", err ) );

    socket.on("data", chunk => {
        const { header, payload } = unwrapMultiplexerMessage( chunk );
        console.log( header );
        console.log( toHex( payload ) )
        // const message = N2CMessageRefuse.fromCbor( payload );
        // console.log( message );
    });

    await new Promise( res => setTimeout( res, 1_000 ) );

    send(
        socket,
        new N2NMessageProposeVersion(
            {
                versionTable: [
                    {
                        version: N2NHandshakeVersion.v10,
                        data: {
                            networkMagic: 1,
                            initiatorAndResponderDiffusionMode: false
                        } 
                    }
                ]
            }
        ).toCbor().toBuffer(),
        MiniProtocol.Handshake
    );

    await new Promise( res => setTimeout( res, 1_000 ) );

    send(
        socket,
        new ChainSyncRequestNext().toCbor().toBuffer(),
        MiniProtocol.ChainSync
    );

    await new Promise( res => setTimeout( res, 1_000 ) );

    send(
        socket,
        new ChainSyncRequestNext().toCbor().toBuffer(),
        MiniProtocol.ChainSync
    );

    await new Promise( res => setTimeout( res, 1_000 ) );
    socket.destroy();

}()

function send( socket: Socket, payload: Uint8Array, protocol: MiniProtocol, hasAgency = true )
{
    let all: Uint8Array
    const flushedAll = socket.write(
        all = wrapMultiplexerMessage(
            payload,
            {
                hasAgency,
                protocol
            }
        ),
        err => console.log( "error in write: ", err )
    );
    
    if( flushedAll ) {
        console.log( "wrote", toHex( all ) )
    }
}
```

running the snippet above results in something like the following
```
connected
wrote 745fa9ab000000078200a10a8201f4
error in write:  null
{
  transmissionTime: 2549853094,
  hasAgency: true,
  protocol: 0,
  payloadLength: 6
}
83010a8201f4
wrote 746ef59e000200028100
error in write:  null
{
  transmissionTime: 2550908602,
  hasAgency: true,
  protocol: 2,
  payloadLength: 49
}
83038082821a01c8a1fb5820ee7a76112efed16564636b355f76c7dcee338f4bc886f0af2964abe6b84bd3ad1a000f493e
wrote 747e3ce1000200028100
error in write:  null
{
  transmissionTime: 2551857050,
  hasAgency: true,
  protocol: 2,
  payloadLength: 135
}
830282008282001853d818584c85015820d4b8de7a11d929a323373cbab6c1a9bdc931beffff11db111cf9d57356ee19375820afc0da64183bf2664f3d4eec7238d524ba607faeeab24fc100eb861dba69971b8200810081a082821a01c8a1fb5820ee7a76112efed16564636b355f76c7dcee338f4bc886f0af2964abe6b84bd3ad1a000f493e
close
```
the first request (handshake n2n) results in a `N2NMessageAcceptVersion` message
```cbor
83       # array(3)
   01    # unsigned(1) // accept version
   0A    # unsigned(10) // version 10
   82    # array(2) // n2n version data
      01 # unsigned(1)
      F4 # primitive(20)
```

the second request results in a `chain-sync` [`msgRollBackwards`](https://github.com/input-output-hk/ouroboros-network/blob/f2b5e5ca3f8be66100ca9bbf64d83e46f3068ce1/ouroboros-network-protocols/test-cddl/specs/chain-sync.cddl#L14) message to the origin
```
83                                      # array(3)
   03                                   # unsigned(3) // roll backwards
   80                                   # array(0)       // point -> origin
   82                                   # array(2)       // tip
      82                                # array(2)       // point -> [ slotNo, int /* ??? */ ]
         1A 01C8A1FB                    # unsigned(29925883)
         58 20                          # bytes(32)   // this is not an int ???
            EE7A76112EFED16564636B355F76C7DCEE338F4BC886F0AF2964ABE6B84BD3AD # "\xEEzv\u0011.\xFE\xD1edck5_v\xC7\xDC\xEE3\x8FKȆ\xF0\xAF)d\xAB\xE6\xB8Kӭ"
      1A 000F493E                       # unsigned(1001790)
```

here is one of the inconsistencies with the CDDL;

when a point is not the origin (empty array) it is an array of length 2 having the slot number in the first position and an int in the second, at least [this is what the CDDL says](https://github.com/input-output-hk/ouroboros-network/blob/f2b5e5ca3f8be66100ca9bbf64d83e46f3068ce1/ouroboros-network-protocols/test-cddl/specs/common.cddl#L21)

but as reported above the element in the second position are bytes (more precisely a hash), so either the node si not respecting the CDDL or the CDDL is wrong here.

In general, everything that intuitively should be a hash (bytes) is reported to be an `int`.

regarding `msgReplyTxs` in the [`outoboros-network` specificatioin](https://input-output-hk.github.io/ouroboros-network/pdfs/network-spec/network-spec.pdf) at page 25, is specified to have as a parameter a list of transactions; [but a list of transaction ids is specified instead in the CDDL](https://github.com/input-output-hk/ouroboros-network/blob/f2b5e5ca3f8be66100ca9bbf64d83e46f3068ce1/ouroboros-network-protocols/test-cddl/specs/tx-submission2.cddl#L21)

In theory the purpose of `msgReplyTxs` should be to resolve given transaction ids, and as such the list of transactions specified in the specification should make more sense.

moreover, the specification for some protocols is incomplete; examples are the local state query protocol which doesn't specify the arguments for the various query (nor where to retrieve them) and the local tx monitor protocol which lacks the state machine documentation (making the expected use of the transitions unclear).

**Comment by coot** [comment]
You're right we ought to use `tx` instead of `txId`, this PR fixes it: https://github.com/input-output-hk/ouroboros-network/pull/4580.

We use `tx = int` & `txId = int` in our cddl, only because `cddl` needs concrete values, while `ouroboros-network` is polymorphic over `tx` and `txId`s (it will work with any kind of `tx` and `txId`s, what `Cardano` is using is a choice of ledger (different eras) & consensus (through hard fork combinator).

**Comment by michele-nuzzi** [comment]
Would it be possible to add comments explaining where to find the expected CDDL for a given era?

I know most of them are in the [`cardrdano-ledger` repository](https://github.com/input-output-hk/cardano-ledger/tree/master/eras) but even so is unclear where those should be used.

This would be particularly useful for the local state query protocol.

**Comment by coot** [comment]
> moreover, the specification for some protocols is incomplete; examples are the local state query protocol which doesn't specify the arguments for the various query (nor where to retrieve them) and the local tx monitor protocol which lacks the state machine documentation (making the expected use of the transitions unclear).

That's an unfortunate side effect of the split between consensus & network.  The protocol itself doesn't specify which queries are available (they depend on era) and are implemented at the consensus side.

> Would it be possible to add comments explaining where to find the expected CDDL for a given era?

Unfortunately there's no such place at the moment.  The consensus is not using CDDL at all, which complicates things. But it's a recurring issue, see input-output-hk/cardano-node#5139. We need to eventually solve this issues in a comprehensive way.

> I know most of them are in the [cardano-ledger repository](https://github.com/input-output-hk/cardano-ledger/tree/master/eras) but even so is unclear where those should be used.

The hard fork combinator combines structures from different eras, I think it's something like a list of two elements where first denotes the era number second one the data for that era, but I wouldn't bet on it.  You'll need to ask the consensus team to point you to the right place.

**Comment by michele-nuzzi** [comment]
> We use `tx = int` & `txId = int` in our cddl, only because `cddl` needs concrete values,

May I suggest an entry in the CDDL like the following for the seek of clarity?

```cddl
any = int
```

and then use `any` where needed; such as:
```cddl
txId = any
tx = any
```

**Comment by coot** [comment]
That's a good idea, we'll do that.

**Comment by coot** [comment]
I created an issue #4595 to use `any` (which is provided by [`cddl`](https://www.rfc-editor.org/rfc/rfc8610#appendix-D)) for all our mini-protocols, and also match it with an appropriate type on `Haskell` side.
