### ISSUE TITLE
Please increase the inactivity timeout on the local domain socket

### ISSUE THREAD

**Issue by erikd** [input-output-hk/ouroboros-network#4579]
`db-sync` and `wallet` are currently some of the main users of the local domain socket.

However, while connecting to `node` and syncing, `db-sync` often triggers the socket timeout (once every two of three epochs). When `db-sync` reconnects it has a bunch of time consuming house keeping before it reconnects to the `node`. The constant disconnect/reconnect cycle slows down syncing.

I am not sure what the current timeout is, but it should be increase by a factor of 4, or it should be made configurable. This should only affect the local domain connection, not connections to remote peers.

**Comment by coot** [comment]
I don't think we have any timeout left in the `node-to-client` protocol. Is the node running in P2P or NonP2P mode?  Could you post a piece of evidence why the node is closing the connection?

**Comment by erikd** [comment]
Oh, then I read the `node` error more carefully. Here it is:
```
[mainnet2:cardano.node.DnsSubscription:Error:11085] [2023-06-01 05:19:58.78 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Application Exception: 18.159.90.166:3001 ExceededTimeLimit (Ch
ainSync (Header (HardForkBlock (': * ByronBlock (': * (ShelleyBlock (TPraos StandardCrypto) (ShelleyEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AllegraEra StandardCryp
to)) (': * (ShelleyBlock (TPraos StandardCrypto) (MaryEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AlonzoEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto)
 (BabbageEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (ConwayEra StandardCrypto)) ('[] *)))))))))) (Tip HardForkBlock (': * ByronBlock (': * (ShelleyBlock (TPraos Standar
dCrypto) (ShelleyEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AllegraEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (MaryEra StandardCrypto)) (': * (S
helleyBlock (TPraos StandardCrypto) (AlonzoEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (BabbageEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (ConwayEra
 StandardCrypto)) ('[] *)))))))))) (ServerAgency TokNext TokMustReply)
[mainnet2:cardano.node.ErrorPolicy:Notice:197] [2023-06-01 05:19:58.81 UTC] IP 18.159.90.166:3001 ErrorPolicySuspendConsumer (Just (ApplicationExceptionTrace ExceededTimeLimit (ChainSync (H
eader (HardForkBlock (': * ByronBlock (': * (ShelleyBlock (TPraos StandardCrypto) (ShelleyEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AllegraEra StandardCrypto)) (': *
 (ShelleyBlock (TPraos StandardCrypto) (MaryEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AlonzoEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (BabbageE
ra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (ConwayEra StandardCrypto)) ('[] *)))))))))) (Tip HardForkBlock (': * ByronBlock (': * (ShelleyBlock (TPraos StandardCrypto) (
ShelleyEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AllegraEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (MaryEra StandardCrypto)) (': * (ShelleyBloc
k (TPraos StandardCrypto) (AlonzoEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (BabbageEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (ConwayEra StandardC
rypto)) ('[] *)))))))))) (ServerAgency TokNext TokMustReply))) 20s
```
So it seems that when the `node` loses a connection to a remote node, it also kills the local domain socket.

**Comment by erikd** [comment]
I also see this:
```
[mainnet2:cardano.node.LocalErrorPolicy:Error:209] [2023-06-01 05:47:34.21 UTC] IP LocalAddress
   "state-node-mainnet/node.socket@16" ErrorPolicyUnhandledApplicationException
   (MuxError MuxSDUWriteTimeout "Mux SDU Timeout")
```

**Comment by coot** [comment]
The first two log messages from your first comment seem to be about `node-to-node` protocol.

**Comment by erikd** [comment]
Yes, that was wrong. so I deleted it The most recent comment was definitely about local domain sockets.

**Comment by coot** [comment]
I needed to reload the page :grin:.

**Comment by erikd** [comment]
It makes sense that this is a write timeout (`MuxSDUWriteTimeout`) as the `node` would write some data to the socket and receive no response because `db-sync` is busy doing something else.

**Comment by coot** [comment]
We use `30s` timeout on sending each `MuxSDU` (which contains at max 12k bytes), it seems the `db-sync` is so busy it cannot keep up with reading the data.

**Comment by erikd** [comment]
Writing ledger state to disk can take up to 10 minutes, but we are thinking of making that asynchronous: https://github.com/input-output-hk/cardano-db-sync/issues/1426.

3o seconds is still a really short amount of time.

**Comment by coot** [comment]
It seems you are making a request to the node then write the snapshot, if you do it the other way around the node will not shut it down.

**Comment by kderme** [comment]
> We use 30s timeout on sending each MuxSDU (which contains at max 12k bytes), it seems the db-sync is so busy it cannot keep up with reading the data.

At which point is `MuxSDU` sent normally?

**Comment by coot** [comment]
Every time you send a mini-protocol message, it's serialised, the bytes are added to a buffer from which the egress side takes `12k` each time, adds its own header and sends over the socket.

**Comment by coot** [comment]
You can take advantage that all the mini-protocols are pull based: if db-sync will not make a demand it will not receive more data to process.

**Comment by erikd** [comment]
> It seems `db-sync` is making a request to the node then write the snapshot,

Sorry, this is not the case.

When it reads from the socket, `db-sync` puts the message in a `TBQueue` which then blocks further writes when the reader is busy.

**Comment by erikd** [comment]
This request may turn out to be un-necessary due to https://github.com/input-output-hk/cardano-db-sync/pull/1427 .

Will know for sure in about 24 hours.

**Comment by coot** [comment]
My last message still stands, with the pull based protocol `db-sync` is in control of the demand.

btw, I am fine with removing the timeout, but it's not the source of the problem.

**Comment by kderme** [comment]
Is this a timeout on the callback execution time? Or is the MuxSDU sent back before the callback is executed on the client side?
By callbacks I mean `recvMsgIntersectFound`, `recvMsgRollForward` etc, which I use with `runPipelinedPeer ... chainSyncClientPeerPipelined`

**Comment by erikd** [comment]
>  I am fine with removing the timeout, but it's not the source of the problem.

How is the `MuxSDUWriteTimeout` not the source of the problem?

**Comment by erikd** [comment]
On the `node` side I just saw:
```
[mainnet2:cardano.node.LocalErrorPolicy:Error:209] [2023-06-01 09:30:20.91 UTC] IP LocalAddress "state-node-mainnet/node.socket@23" ErrorPolicyUnhandledApplicationException (MuxError MuxSDU
WriteTimeout "Mux SDU Timeout")
[mainnet2:cardano.node.DnsSubscription:Error:14665] [2023-06-01 09:30:20.92 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Application Exception: 54.176.246.181:3001 ExceededTimeLimit (C
hainSync (Header (HardForkBlock (': * ByronBlock (': * (ShelleyBlock (TPraos StandardCrypto) (ShelleyEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AllegraEra StandardCry
pto)) (': * (ShelleyBlock (TPraos StandardCrypto) (MaryEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AlonzoEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto
) (BabbageEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (ConwayEra StandardCrypto)) ('[] *)))))))))) (Tip HardForkBlock (': * ByronBlock (': * (ShelleyBlock (TPraos Standa
rdCrypto) (ShelleyEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AllegraEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (MaryEra StandardCrypto)) (': * (
ShelleyBlock (TPraos StandardCrypto) (AlonzoEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (BabbageEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (ConwayEr
a StandardCrypto)) ('[] *)))))))))) (ServerAgency TokNext TokMustReply)
[mainnet2:cardano.node.ErrorPolicy:Notice:197] [2023-06-01 09:30:20.93 UTC] IP 54.176.246.181:3001 ErrorPolicySuspendConsumer (Just (ApplicationExceptionTrace ExceededTimeLimit (ChainSync (
Header (HardForkBlock (': * ByronBlock (': * (ShelleyBlock (TPraos StandardCrypto) (ShelleyEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AllegraEra StandardCrypto)) (': 
* (ShelleyBlock (TPraos StandardCrypto) (MaryEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AlonzoEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (Babbage
Era StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (ConwayEra StandardCrypto)) ('[] *)))))))))) (Tip HardForkBlock (': * ByronBlock (': * (ShelleyBlock (TPraos StandardCrypto) 
(ShelleyEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AllegraEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (MaryEra StandardCrypto)) (': * (ShelleyBlo
ck (TPraos StandardCrypto) (AlonzoEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (BabbageEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (ConwayEra Standard
Crypto)) ('[] *)))))))))) (ServerAgency TokNext TokMustReply))) 20s
```
which corresponded on the `db-sync` side to:
```
[db-sync-node:Error:80] [2023-06-01 09:30:28.53 UTC] runDBThread: AsyncCancelled
[db-sync-node:Error:72] [2023-06-01 09:30:28.61 UTC] ChainSyncWithBlocksPtcl: AsyncCancelled
[db-sync-node.Subscription:Error:68] [2023-06-01 09:30:28.62 UTC] Identity Application Exception: LocalAddress "../cardano-node/state-node-mainnet/node.socket" MuxError MuxBearerClosed "<socket: 21> closed when reading data, waiting on next header True"
[db-sync-node.ErrorPolicy:Warning:6] [2023-06-01 09:30:28.66 UTC] IP LocalAddress"../cardano-node/state-node-mainnet/node.socket" ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace (MuxError MuxBearerClosed "<socket: 21> closed when reading data, waiting on next header True"))) 20s 20s
```
Notice that the `db-sync` log message happens 8 seconds after the `node` message.

**Comment by coot** [comment]
As I understand the sequence is as follows:

* `db-sync` asks for more data
* `node` tries to send it
* `db-sync` is too busy to receive it
* `node` abandons the connection

if `db-sync` didn't request for data which it cannot handle, it wouldn't fail.  Moreover, if it properly took advantage of the `pull` based nature of the protocols it wouldn't do the initial request, because it would be blocked on doing something else.

**Comment by coot** [comment]
> Is this a timeout on the callback execution time? Or is the MuxSDU sent back before the callback is executed on the client side?

If I understand this case correctly, this is a timeout on sending `MuxSDU` data, which is triggered on the `node` side when `db-sync` is blocked on one of the `recv*` callbacks.

**Comment by erikd** [comment]
Yes, that is my current hypothesis.

**Comment by karknu** [comment]
The request for new data comes from https://github.com/input-output-hk/cardano-db-sync/blob/5c38f37312b378119d82debb2af74d1f6d864027/cardano-db-sync/src/Cardano/DbSync/Sync.hs#L429-L453 .

If the `actionQueue` doesn't have space for more replies, wait until it drains before issuing new requests.

**Comment by kderme** [comment]
db-sync defined more chainsync clients. For example in one of them it sleeps during a `recvMsgIntersectNotFound` callback https://github.com/input-output-hk/cardano-db-sync/blob/5c38f37312b378119d82debb2af74d1f6d864027/cardano-db-sync/src/Cardano/DbSync/Sync.hs#LL614C17-L614C17 waiting for the node to sync up to the requested point 

Is this bad usage? And if it is why? Is there a timeout on the execution time of these collbacks?

**Comment by erikd** [comment]
I repeat:

> this is not a clean blocking protocol.

Sure, we can detect when the `actionQueue` is full, and then do a `sleep` but for how long? 10 seconds? 10 minutes? IMO the timeout should be more lenient so `db-sync` does not have to sleep or loop with a sleep until it can issue a new command.

**Comment by karknu** [comment]
cardano-node is a realtime application, which means that it comes with some timeliness requirements.
To limit resource consumption incurred on cardano-node by clients they are expected to be able to read a MuxSDU within 30s.

Your usage of a TBQueue makes the needed pause in sending requests easy to implement without an explicit loop.

```
atomically $ do
  len <- lengthTBQueue actionQueue
  if len + outStandingRequest >= actionQueueLength
    then retry
    else return ()

**Comment by coot** [comment]
> Is this bad usage? And if it is why? Is there a timeout on the execution time of these collbacks?

This is perfectly fine.  You wait after you receiving data (no intersection found), and decided to wait before sending next request.

**Comment by kderme** [comment]
Cool then I don't see anything wrong in our implementation of the protocol. db-sync can only block during the mini-protocol callbacks, so I don't follow the `TBQueue` changes recommendation. However if you've find something wrong please elaborate.

So on the original question what could have caused the `MuxSDUWriteTimeout`? Could it be the result of a machine running low on resources, in memory IO buffers and using swap?

**Comment by coot** [comment]
> Cool then I don't see anything wrong in our implementation of the protocol.

`db-sync` is breaking the protocol by demanding more work that it can handle.  It's a failure of propagating backpressure correctly.

> So on the original question what could have caused the MuxSDUWriteTimeout? Could it be the result of a machine running low on resources, in memory IO buffers and using swap?

@karknu is right, you should not add more actions when you don't have capacity to deal with them.  Blocking on the queue seems like a good solution.  The node does the right thing to disconnect from `db-sync`.

**Comment by kderme** [comment]
>  Blocking on the queue seems like a good solution.

**Comment by kderme** [comment]
> Blocking on the queue seems like a good solution.

But db-sync already blocks on the queue size, this is blocking https://github.com/input-output-hk/cardano-db-sync/blob/master/cardano-db-sync/src/Cardano/DbSync/Sync.hs#LL469C20-L469C20. And as you said it's fine to block at this point.

**Comment by erikd** [comment]
> Your usage of a TBQueue makes the needed pause in sending requests easy to implement without an explicit loop.

This does not align with how I understand this is currently working.

As I understand it:

1) Requests data from the protocol.
2) Reads data from the protocol.
3) Writes data to `TBQueue`.
4) Loop back to 1)

If the `TBQueue` is full, the write blocks and not further requests are made until the write unblocks and completes.

**Comment by coot** [comment]
Looking at the link I came to the same conclusion, so I think you're right about it.

Maybe you should tune the size of the queue (make it smaller), so it blocks earlier than when the process is too busy to make progress on chain sync.

**Comment by coot** [comment]
The [`waitRollback`](https://github.com/input-output-hk/cardano-db-sync/blob/master/cardano-db-sync/src/Cardano/DbSync/DbAction.hs?plain=1#L38-L42) is suspecious.  It could write to the action queue and if that blocks some other thread on writing to the `TMVar` it could deadlock.

**Comment by karknu** [comment]
> If the `TBQueue` is full, the write blocks and no further requests are made until the write unblocks and completes.

You're running with pipelining setup so you can have 50 outstanding requests. Your application can get blocked processing one reply, but there are still 49 outstanding requests which expects to read promptly.

The code example I linked above does take the number of outstanding requests into account.

**Comment by coot** [comment]
Good point Karl.  Another solution would be to change the pipelining policy so its depth corresponds to available depth of the queue.

**Comment by erikd** [comment]
I have tried reducing the size of the `TBQueue` from `117` to `47` but that does not seem to have helped much. Still get numerous disconnects.

On the `node` side this still looks like:
```
[mainnet2:cardano.node.LocalErrorPolicy:Error:209] [2023-06-03 11:00:45.33 UTC] IP LocalAddress
  "state-node-mainnet/node.socket@131" ErrorPolicyUnhandledApplicationException
  (MuxError MuxSDUWriteTimeout "Mux SDU Timeout")
```

**Comment by coot** [comment]
Currently, `MkPipeliningDecision` is a pure computation so one cannot check depth of a `TBQueue` in it.  For that `db-sync` needs the following change from `ouroboros-network-protocols`: https://github.com/input-output-hk/ouroboros-network/pull/4582.

**Comment by erikd** [comment]
I have worked around this in `db-sync` by reducing the depth of the `TBQueue` to `47`. I have not seen the disconnect/reconnect issue return since then.
