### ISSUE TITLE
Improve CDDL specs by using any

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#4595]
CDDL has the notion of `any` which can be used to indicate that something is not specified.  We provided this for `Tx` and `TxId` in `tx-submission` mini-protocol in #4580.  It would be nide to extend this approach to other mini-protocols.

* [x] `chain-sync` #4638 
* [x] `block-fetch` #4638
* [x] `tx-submission` #4580
* [x] `local-tx-submission`
* [x] `local-state-query`
* [x] `local-tx-monitor` #4638
* [x] `node-to-client-handshake` (_a non polymorphic protocol_)
* [x] `node-to-node-handshake` (_a non polymorphic protocol_)
* [x] `peer-sharing` (_polymorphic over `peeraddr`, which is instantiated to `SockAddr`_)
* [x] `keep-alive` (_a non polymorphic protocol_)

**Comment by bolt12** [comment]
I took a look into this. And the rest of the protocols use `ouroboros-network-mock` and `ouroboros-network-api` mock types for `Point`, `Block`, etc.. types. I am not sure we want to stop using these since they belong to the testing ecosystem and mock the real thing
