### ISSUE TITLE
Usage of new `query` field in NodeTo{Client,Node}VersionData

### ISSUE THREAD

**Issue by KtorZ** [input-output-hk/ouroboros-network#4630]
Hello! 

[This commit](https://github.com/input-output-hk/ouroboros-network/commit/bd558520ac1a7c1842d0a747925fd95356599c62) introduces a new flag `query` on the `NodeTo{Client,Node}VersionData` object. 

What's its semantic? When should it be set to `True` (or `False`). 

Thanks.

**Comment by bolt12** [comment]
if `query` is enabled, when doing handshake the nodes will reply with a list of supported versions. You should set it to either `True` or `False` depending if you want that. Porbably you want it set to `False`.

It is useful for `cardano-ping` to have a [`--query`](https://github.com/input-output-hk/cardano-cli/pull/30/files) flag
