### ISSUE TITLE
Wrong Inbound Governor State Transitions

### ISSUE THREAD

**Issue by karknu** [input-output-hk/ouroboros-network#4667]
The transitions to and from Hot in the inbound governor is wrong. By requiring *all* hot protocols to have started peers that never fetches a block from the node will be classified as warm.

Current behaviour:
* the transition from warm to hot requires all hot protocols to have started.
* the transition from hot to warm requires any hot protocol to have terminated

I propose the opposite use of qualifiers, so:
* the transition from warm to hot requires any hot protocol to have started.
* the transition from hot to warm requires all hot protocols to have terminated

**Comment by coot** [comment]
Indeed, we should use `Any` for all promotions, and `All` for all demotions - this compose  well while a connection is going from `Hot` to `Cold`.
