### ISSUE TITLE
Block Fetch: derive the FetchClientPolicy from the BlockFetchConsensusInterface

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#468]
The `BlockFetchConsensusInterface` record is the interface that the consensus layer must implement in order to use the block fetch logic. Among the fields of the record are: `blockFetchSize`, `blockMatchesHeader`, and `addFetchedBlock`. These fields are currently not used.

The `blockFetchClient` requires a `FetchClientPolicy` that contains these exact three fields with the same types. These fields should be plumbed from the `BlockFetchConsensusInterface` to the `FetchClientPolicy`.

**Comment by dcoutts** [comment]
Fixed by #561
