### ISSUE TITLE
KeepAlive client

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#4689]
The keep alive client has two small issues:

1. it should record time when it sends the initial `MsgKeepAlive`, and compute the `rtt` when we receive the reply.
2. currently after first round trip with `MsgKeepAlive -> MsgKeepAliveResponse`, we immediately send the next `MsgKeepAlive` message without doing the delay. If we refactor the code to fix the first issue we will actually fix this one as well, if we eliminate [ref](https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-network/src/Ouroboros/Network/KeepAlive.hs#L94-L96).

**Comment by karknu** [comment]
Will look into this.
