### ISSUE TITLE
Volatile DB: Make parser error type variable

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#488]
The volatile DB currently requires the parser to return a specific error type (`ParserError`). This should be changed; it should be completely polymorphic in the error type. If internally it is useful to to deal with parsers returning `ParserError` instead, I'd suggest to parameterize the `DecodeFailed` constructor of `ParserError` with a type parameter `e`, and the internally translate from `Parser .. e ..` to `Parser .. (ParserError e) ..`; but it mightin fact be that this error type can go altogether; not entirely sure. However, it should be an internal detail to the volatile DB, if it stays.

**Comment by kderme** [comment]
@edsko I was thinking that instead of `Maybe e`, the parser could return sth like this
```data ParserMessage e = EverythingOk | Truncate | ThrowError e``` 
which informs the db what it should do. `e` would be wrapped as a `VolatileDBError` and rethrown.

**Comment by edsko** [comment]
Why do you need the distinction between `Truncate` and `ThrowErrow`?

**Comment by kderme** [comment]
when `Truncate` no error should be thrown. Just truncate the db and continue.

**Comment by edsko** [comment]
When would that ever happen?

**Comment by kderme** [comment]
If the parser fails to parse the whole file, but only up to a point. Isn't this possible?

**Comment by edsko** [comment]
Ah, sure, absolutely. But that's _already_ captured. After all, we return a bunch of successful results, _and_ an optional error. If that error is present, the file should be truncated after the successful results. If no error is present, then no.

**Comment by kderme** [comment]
If I simply get `Just e`, then the db does not know if it should truncate and continue or truncate and throw e.

**Comment by edsko** [comment]
It should _never_ throw `e`. It should truncate and move on.

**Comment by kderme** [comment]
Oh ok, then even a `Bool` would work right? Why I need to know e?

**Comment by edsko** [comment]
Yes, in principle just a `Bool` would work. The only reason for `e` would be to log a warning ("truncating file such and such because error such and such").

**Comment by edsko** [comment]
Closed in #492.
