### ISSUE TITLE
Improve logging in the mux layer

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#507]
We ought to have various level of debugging / diagnostic information in the multiplexing layer.  It should be easy to turn in on/off in tests.

**Comment by dcoutts** [comment]
We just need to insert the right `Tracer` points, and the levels & on/off stuff can be handled by the tracer providers. See the `BlockFetch` code for examples of tracing structured information.

**Comment by coot** [comment]
addressed in #1059
