### ISSUE TITLE
Cannot interrupt blocking network I/O ops on Windows

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#545]
This issue is for tracking our progress towards: https://gitlab.haskell.org/ghc/ghc/issues/14503#note_200103
On windows when compiled with `-threaded` flag, GHC deadlocks when killing a thread while a descriptor is opend.  This is important in `ouroboros-network`:
* we keep open TPC connections (thus we have multiple open file descriptors)
* we throw async exceptions to do thread management (via async interface)
With this bug we cannot close any thread while the application is running. 

This bug was fixed in the non `-threaded` case only, which is not an option for us: without it GHC blocks all the threads on FFI calls.

@karknu created a simple program to reproduce this issue: https://github.com/karknu/win-thread-deadlock and tested which GHC versions are affected:
## Results on 64bit Windows10.

| LTS   |  GHC   | Threaded | Status |
| -----:| -----: | -------- | -------|
|  6.35	| 7.10.3 | No       | Broken |
|  6.35	| 7.10.3 | Yes      | Broken |
|  9.21	|  8.0.2 | No       | Fixed  |
|  9.21	|  8.0.2 | Yes	    | Broken |
| 11.22	|  8.2.2 | No       | Fixed  |
| 11.22	|  8.2.2 | Yes      | Broken |
| 12.14	|  8.4.3 | No       | Fixed  |
| 12.14	|  8.4.3 | Yes      | Broken |
| 12.26 |  8.4.4 | No	    | Fixed  |
| 12.26 |  8.4.4 | Yes      | Broken |
| 13.11 |  8.6.3 | No       | Fixed  |
| 13.11 |  8.6.3 | Yes      | Broken |
| 13.19 |  8.6.4 | No       | Fixed  |
| 13.19 |  8.6.4 | Yes      | Broken |
| 13.22 |  8.6.5 | No       | Fixed  |
| 13.22 |  8.6.5 | Yes      | Broken |

**Comment by dcoutts** [comment]
I think I've identified why: https://gitlab.haskell.org/ghc/ghc/issues/14503#note_200103

**Comment by dcoutts** [comment]
Related tickets:
* https://gitlab.haskell.org/ghc/ghc/issues/5797
* https://gitlab.haskell.org/ghc/ghc/issues/7353

**Comment by coot** [comment]
PR #1186 & #1207 merged

**Comment by coot** [comment]
Closing as this has been addressed by developing `Win32-network` library.
