### ISSUE TITLE
Assign sensible protocol limits for NodeToNode and NodeToClient protocols

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#575]
Message size limits.

**Comment by dcoutts** [comment]
Related to #1395 but for size limits, rather than time limits.

**Comment by coot** [comment]
Closing as a duplicte of #1727

**Comment by coot** [comment]
Closed per-maturelly.

**Comment by dcoutts** [comment]
How does this differ from #1727 ?

**Comment by coot** [comment]
#1727 are per state limits using a driver; this issue is only for mux queue limits (done in pr #1740). Sorry this wasn't well phrased.

**Comment by coot** [comment]
Done in #1740
