### ISSUE TITLE
Chain Sync Client: reuse anachronistic ledger view?

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#581]
We currently ask for the anachronistic ledger view for every block we get. We should reconsider that. If that is indeed okay, then there is no need for the window at all, and so we can simplify the code. If that is not okay (bad performance) we should change the chain sync client.

**Comment by mrBliss** [comment]
While only minor (so after mainnet would be fine), from a design perspective it would be good to consider earlier.
