### ISSUE TITLE
Technical debt: introduce `Header` type family

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#589]
In many, many places throughout the consensus layer we have two type arguments: `blk` and `hdr`. However, these are not truly independent. Instead, we should have a type family mapping `blk` to `hdr`, which should then be used throughout the entire consensus layer (including storage layer).

**Comment by edsko** [comment]
Would supersede #588.

**Comment by edsko** [comment]
In an ideal world, we would then be able to move all the equality constraints (such as `BlockProtocol (BlockHeader b) ~ BLockProtocol b` to a single place instead of repeating them all over the place.

**Comment by edsko** [comment]
We should also rename `SupportedBlock` to `SupportedHeader` as part of this PR.

**Comment by mrBliss** [comment]
Fixed by #616.
