### ISSUE TITLE
Multiplexing, Versioning, Serialization and Framing Scheme

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#59]
__net_impl_multiplexing_serialization__
Design and implement the multiplexing, versioning, serialisation and framing scheme for running the mini-protocols on a single bearer channel, in simulation

This takes a set of mini-protocol implementations (client and server sides) and runs them all over a single byte level channel by multiplexing at an appropriate level (either message or message chunk). This necessitates some design for framing (the units of multiplexing), and serialisation for frames. It also requires a minimal design for any opening messages including protocol version negotiation.

**Comment by dcoutts** [comment]
Note that the current implementation strategy involves incorporating some of the TCP aspects early `net_impl_integrate_tcp`, not just all in simulation first and TCP later.
