### ISSUE TITLE
Extend definition of generalized transaction for Byron

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#592]
Currently the only thing supported is actual transactions.

Relies on https://github.com/input-output-hk/cardano-ledger/issues/514 .

**Comment by deepfire** [comment]
The update system needs _votes_ and _update proposals_ to also be representable.

**Comment by deepfire** [comment]
cc @ruhatch

**Comment by mrBliss** [comment]
If not done before testnet, definitely before mainnet.

**Comment by deepfire** [comment]
@mrBliss, I don't think we can affort not to have mempool-able update system stimuli in the testnet.

cc @dcoutts

**Comment by deepfire** [comment]
Related: https://github.com/input-output-hk/cardano-ledger/issues/514
