### ISSUE TITLE
Chain Sync Client: instantiate with header and BlockSize

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#593]
The Block Fetch logic wants to know the size of a block when we only have a header. If we instantiate the Chain Sync Client with the header *and* the `BlockSize`, we will have enough information.

Note that adding the block size to the header is not enough, as we still have to deal with blocks from the existing (real-world) chain.

**Comment by mrBliss** [comment]
Ideally present for system-level performance testing. Needed for mainnet, as it could be a security risk.

**Comment by mrBliss** [comment]
Fixing this means having to change the ChainSync protocol instantiation, breaking compatibility with already deployed nodes. So this should be done sooner rather than later (if it is not yet too late?).

If we don't fix it, the accounting for in flight bytes done by the BlockFetch client will be wrong, as we currently hardcode the size of each block to 2000.

@dcoutts Do you agree that we should do this ASAP? And is it still ok to make such breaking changes?

**Comment by mrBliss** [comment]
Duncan's response:
> I think we have to do one [compatibility break] for other reasons in the network code anyway. Lets review with the network team and try to do them at the same time, or use the versioning scheme.

**Comment by mrBliss** [comment]
Hmm, this is more invasive than I thought, as the ChainSyncServer will need to be able to return a header *and* the block size. The ImmutableDB will need to be modified to support this change. Even the implementation of the Reader has to be modified (other than simply forwarding the block size from the ImmutableDB): when returning the headers from the in-memory chain fragment (the last `k` blocks), we'll either need to keep their block sizes in memory too or retrieve them from the VolatileDB.

**Comment by kderme** [comment]
> we'll either need to keep their block sizes in memory too or retrieve them from the VolatileDB.

A new api call getBlockSize makes sense for this?

**Comment by mrBliss** [comment]
> > we'll either need to keep their block sizes in memory too or retrieve them from the VolatileDB.
> 
> A new api call getBlockSize makes sense for this?

See #1471 for a more general approach to this.
