### ISSUE TITLE
Mempool: Ensure getTxs does not update internal state

### ISSUE THREAD

**Issue by intricate** [input-output-hk/ouroboros-network#668]
From a discussion with @dcoutts:
>I'm now less convinced than I was before that Edsko's design for `getTxs` is ok. It does state updates on read as well as write. But I think this may make it too expensive to use in a blocking style for the tx protocol handlers.
I think we may need to have a design where `getTxs` is cheap as it only reads a `TVar`, and instead have an explicit update for bringing the mempool into sync with the chain db.
>As it is now also makes it quite awkward to trace the updates to the mempool since they happen on readers as well as writers.
Edsko's current design has the advantage that when you observe the mempool it is always consistent with the current chain db. My approach would lose that. But I don't think we need that level of consistency. 

The solution should ensure that `getTxs` no longer updates the `Mempool`'s `InternalState` and we should also introduce a function which specifically syncs up the `Mempool` with the `ChainDB`.

In addition to this, we should introduce a mechanism by which this new `Mempool` syncing function is called whenever there is a change to the `ChainDB`s tip point.

Finally, we should ensure that the `Mempool` is in-sync upon the call to [`getTxs` in `Ouroboros.Consensus.Node`](https://github.com/input-output-hk/ouroboros-network/blob/e196d4928d4bac038391871f58b6da63c64451df/ouroboros-consensus/src/Ouroboros/Consensus/Node.hs#L311).

**Comment by mrBliss** [comment]
I'm labelling it `staging` so that we can get clear tracing (see #669) when testing the node internally.

**Comment by intricate** [comment]
Resolved in PR #678
