### ISSUE TITLE
Document Wire Protocol

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#69]
__net_doc_wire_protocol__
Document the initial design of the versioning, serialisation, framing and multiplexing for the protocol

Also includes the documentation for each mini protocol, including state transitions, prose descriptions and message serialisation formats.

This will be an addition to the general network design document in the github repo.

The definition of done for this work package is document review and sign-off from a majority of the document authors.

**Comment by MarcFontaine** [comment]
The first part is finished.

> This will be an addition to the general network design document in the github repo.

It is unclear which documents are meant here.
The work can be found in ouroboros-network/doc/network.tex.

**Comment by coot** [comment]
That's perfect, thanks @MarcFontaine.

**Comment by coot** [comment]
So what's left is to do review the the documentation, right?
