### ISSUE TITLE
Mempool: Introduce and implement GenTxSize

### ISSUE THREAD

**Issue by intricate** [input-output-hk/ouroboros-network#700]
@dcoutts' first version of the transaction submission logic (implemented in PR #687) requires that `MempoolSnapshot`s can return transactions along with their size in bytes (post-serialization).

From [`Ouroboros.Network.TxSubmission.Outbound`](https://github.com/input-output-hk/ouroboros-network/commit/c8852eadeebcd73eff2ead5a4f974d4a9a9783ac#diff-56b78a274dbb2d56d0a5f9e6f6a0b1c0R65)
```
data MempoolSnapshot txid tx idx =
     MempoolSnapshot {
       mempoolTxIdsAfter :: idx -> [(txid, idx, TxSizeInBytes)],
       ...
     }
```

**Comment by mrBliss** [comment]
#686 depends on this.

**Comment by intricate** [comment]
#739 depends on this.
