### ISSUE TITLE
Demo playground not syncing correctly

### ISSUE THREAD

**Issue by nc6** [input-output-hk/ouroboros-network#705]
The demo-playground nodes are currently producing a single block repeatedly - that is, blocks seem to not being incorporated onto the chain.

This is visible even with a single node - blocks are produced, but each has no awareness of the previous block.

**Comment by mrBliss** [comment]
For me it only happens with `--real-pbft`, it works fine with all other protocols.

**Comment by mrBliss** [comment]
Aha, `Ouroboros.Consensus.Protocol.PBFT.applyChainState` is returning`PBftInvalidSignature "Verification failed"` for each block. *Dives deeper*

**Comment by dcoutts** [comment]
This also highlighted the issue that the logging here was reporting that we were creating the block, but it was doing it before that block had been actually incorporated into the chain so it was a false success message.

The `ChainDB.addBlock` does not report any result. Perhaps it should return the tip point once the block was added (and any resulting chain selection is complete). That way the tracing could report if adding the block was successful or not (and it not being successful would be a severe internal error that we should act on).

**Comment by mrBliss** [comment]
> This also highlighted the issue that the logging here was reporting that we were creating the block, but it was doing it before that block had been actually incorporated into the chain so it was a false success message.

Creating a block and adopting it are two separate things, so I don't see it as a false success message.

> The `ChainDB.addBlock` does not report any result. Perhaps it should return the tip point once the block was added (and any resulting chain selection is complete). That way the tracing could report if adding the block was successful or not (and it not being successful would be a severe internal error that we should act on).

This is indeed what should happen and  *does happen* in the real (as opposed to the mock) implementation of `ChainDB.addBlock`. I use the following type for that:
```haskell
-- | Trace type for the various events that occur when adding a block.
data TraceAddBlockEvent blk
  = AddedBlockToVolDB    (Point blk)
    -- ^ A block was added to the Volatile DB
  | TryAddToCurrentChain (Point blk)
    -- ^ The block fits onto the current chain, we'll try to use it to extend
    -- our chain.
  | TrySwitchToAFork     (Point blk) (NonEmpty (HeaderHash blk))
    -- ^ The block fits onto some fork, we'll try to switch to that fork (if
    -- it is preferable to our chain).
  | StoreButDontChange   (Point blk)
    -- ^ The block doesn't fit onto any other block, so we store it and ignore
    -- it.
  | SwitchedToChain
    { _prevChain :: AnchoredFragment (Header blk)
    , _newChain  :: AnchoredFragment (Header blk)
    }
    -- ^ We successfully installed a new chain.
  | ChainChangedInBg
    { _prevChain :: AnchoredFragment (Header blk)
    , _newChain  :: AnchoredFragment (Header blk)
    }
    -- ^ We have found a new chain, but the current chain has changed in the
    -- background such that our new chain is no longer preferable to the
    -- current chain.
  | AddBlockValidation (TraceValidationEvent blk)
    -- ^ An event traced during validating performed while adding a block.

data TraceValidationEvent blk
  = InvalidBlock
    { _validationErr :: ExtValidationError blk
    , _invalidPoint  :: Point blk
    }
    -- ^ A point was found to be invalid.
  | InvalidCandidate
    { _candidate     :: AnchoredFragment (Header blk)
    , _reasonInvalid :: ReasonInvalid
    }
    -- ^ A candidate chain was invalid.
  | ValidCandidate (AnchoredFragment (Header blk))
    -- ^ A candidate chain was valid.
```

**Comment by dcoutts** [comment]
> Creating a block and adopting it are two separate things, so I don't see it as a false success message.

**Comment by nc6** [comment]
Working notes: looks like the `SignTag` isn't the same between the two cases, probably due to the genesis key being wrong. Diving deeper...
