### ISSUE TITLE
Design clean mux shutdown for full-duplex connections

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#711]
During our meeting @karknu raised the following issue.

When running a full duplex connection there will be times when an initiator (or responder) will want to cleanly close one side of the connection.  Currently, when that happens the multiplexing layer will kill all multiplexing threads which kills both sides of the connection.

We need to design a mechanism which allows us to close one half of the mux without affecting the other side.  As noted by Neil (or Peter) if one side of the connection is corrupted (garbage in) then the other side should be close as well.

**Comment by karknu** [comment]
This is superseded by #1318.
