### ISSUE TITLE
Termination of chain sync protocol (client side)

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#712]
When `chain-sync` client is not interested in the other node's chain, the client throws `ChainSyncClientException.ForkTooDeep`.  Currently this shuts down whole node.

This exception should be handled, and shutdown down only one side of a full-duplex channel.
In this case we also need to change DNS subscription for that peer to avoid re-connecting to it to early.

This is related to #711.

**Comment by mrBliss** [comment]
It might depend on the precise exception (i.e., the constructor of `ChainSyncClientException`) whether we should be able to ever reconnect to the peer. For example, in case of adversarial behaviour, we should never reconnect. Other reasons to throw an exception might only be temporary, e.g., `ForkTooDeep`, which will not be a problem anymore when the peer catches up with our chain.

**Comment by avieth** [comment]
Why does it need to be an exception? Couldn't we have `ForkTooDeep` be a message in the protocol, ending in a terminal state?

**Comment by mrBliss** [comment]
@avieth That would work too for me, but I remember being told by Duncan to throw an exception instead. I didn't design the protocol, I just wrote an implementation :innocent:

**Comment by coot** [comment]
It would work in all states but the case where a client received `MsgAwaitReply`, in which case it is the `responder` / `server` who keeps the agency, the client has no opportunity of sending a terminating message.

**Comment by karknu** [comment]
How about adding  a time limit to `MustReply`, so that the server has to respond with `RollBackward`, `RollForward` or `NoData`. Where the latter would hand over agency to the client if no new data was available after X seconds. Failing to handover agency would be a protocol violation and the bearer can be torn down.

**Comment by coot** [comment]
@karknu I like your idea, @njd42 what's your opinion?

**Comment by njd42** [comment]
Requiring evidence of progress sounds like a good idea. 

What is the current state transitions - i.e. are we currently insisting on a "NoData" or is that a new state?

Setting a timer means that we need to consider its duration - given that this is relate to blocks that is going to need to be 10's (to 100's) of seconds?

**Comment by coot** [comment]
> What is the current state transitions - i.e. are we currently insisting on a "NoData" or is that a new state?

That would be a new state transition from `StNext StMustReply` to `StIdle` giving chance the client to take an action, and giving the chance to send `MsgDone`. No new state.

> Setting a timer means that we need to consider its duration - given that this is relate to blocks that is going to need to be 10's (to 100's) of seconds?

That's right it would be something in `10`s to `100`s, or maybe up to `60`s - e.g. three slots should be enough to give back control to the client. We could make it even less, but then it will stress the network, which already might be under load.

**Comment by njd42** [comment]
We are really using this as a keep alive indication I think that 100s is fine - we will have timed it out before this point (if we wanted to use it - some alternative being use/sought) and this is a backstop position to ensure that the bearer will be torn down.

**Comment by coot** [comment]
It would be useful to get a review of #578 (it's getting rusty, the PR number is pretty low, we are already in the >700 range :open_mouth: )

**Comment by njd42** [comment]
Is that a request to me marcin?

**Comment by coot** [comment]
No, I wanted to ask @avieth on slack, but I got interrupted ...

**Comment by coot** [comment]
Closing, it was decided throwing exceptions is the simplest approach.
