### ISSUE TITLE
Validator hard-wired for mainnet

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/ouroboros-network#714]
As far as `GenesisConfig` choice goes, the `validator` is currently unable to use anything but the mainnet genesis, because while one can specify a different genesis file, the hash it's going to be validated against will be picked from `mainnetConfiguration`:

https://github.com/input-output-hk/ouroboros-network/blob/f132a47c7d8711cc2c0457c62509fa1dbcb9347c/byron-proxy/src/exec/Validator.hs#L136

It seems we're bumping into https://github.com/input-output-hk/cardano-shell/issues/210 once more, as we're lacking a generalised, unified mechanism for as single-source-of-truth configuration.

**Comment by coot** [comment]
@avieth

**Comment by deepfire** [comment]
We've had a call with @CodiePP and @ksaric on this matter.  We're working on the generalised configuration mechanism.

**Comment by deepfire** [comment]
I'll be working on this soon.

**Comment by mrBliss** [comment]
This is related to the proxy, which now lives in a separate repository. @deepfire can you open a ticket in that repository if this still applies (and you haven't done so already).

**Comment by avieth** [comment]
> This is related to the proxy, which now lives in a separate repository. @deepfire can you open a ticket in that repository if this still applies (and you haven't done so already).

The program it refers to has also been deleted from that repository.
