### ISSUE TITLE
Chain DB: handle and test clock changes

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#759]
See https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-consensus/docs/ChainDB.md#clock-changes

**Comment by mrBliss** [comment]
Possible approach: start a thread that "watches" the current time and when it rolls back, shut down the node (and restart).

**Comment by mrBliss** [comment]
TODO: do we deal correctly with blocks (on-disk) from the future?

**Comment by edsko** [comment]
Moving this to `daedalus` since exchange and core nodes won't be changing their clocks.

**Comment by edsko** [comment]
Marked as high priority because this is totally untested.

**Comment by mrBliss** [comment]
An NTP client will be running and notify the wallet when it is out of sync. Think about what we should do.

**Comment by mrBliss** [comment]
Current plan:

* If time moved forward: `waitUntilNextSlot` will handle it correctly. We might briefly lag behind, but we'll correct it when waiting for the next slot.
* If time moved backward: we can check in `waitUntilNextSlot` whether the computed next slot number is actually the next one. If it is not, time must have moved back. We could allow staying on the same slot number, but we certainly can't allow going back a slot, we should throw an exception, shutting down the node.

Note that we (the node) don't have to run an NTP client for this. We are using `getCurrentTime` (wall clock) in `waitUntilNextSlot`.

**Comment by mrBliss** [comment]
Implementation: @edsko 
(Protocol) testing: @nfrisby

**Comment by mrBliss** [comment]
The implementation was completed in #1554. We have created a new ticket for testing it: #1572.

**Comment by edsko** [comment]
Re-opening as this isn't merged yet due to dependency on https://github.com/input-output-hk/ouroboros-network/pull/1539 . Since it's only the _tests_ that depend on that, though, will submit two separate PRs.

**Comment by edsko** [comment]
Mind that it _does_ come with tests, it just doesn't do consensus-level tests.

**Comment by edsko** [comment]
Closed as of https://github.com/input-output-hk/ouroboros-network/pull/1554 .
