### ISSUE TITLE
Ouroboros.Consensus.Util relies on Int being 64-bit

### ISSUE THREAD

**Issue by Vtec234** [input-output-hk/ouroboros-network#770]
In ouroboros-consensus/, `Ouroboros.Consensus.Util.nonNegIntR` ([link](https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-consensus/src/Ouroboros/Consensus/Util/Random.hs#L37)) sounds like it should return non-negative integers. However, it relies on the `Int` type being at least 33-bits wide (so that the max value is 2^32-1) (e.g. 64-bit), while the Haskell spec [states](https://hackage.haskell.org/package/base-4.12.0.0/docs/Data-Int.html) that `Int` has "at least the range [-2^29 .. 2^29-1]". In practice, if `Int` is `Int32`, half of the time this function will return a negative value.

**Comment by mrBliss** [comment]
Thanks for notifying us @Vtec234. I have discovered that this function isn't actually used anymore. It previously was used by the crypto testsuite, but that moved to cardano-base in https://github.com/input-output-hk/cardano-base/pull/27. Can you open a similar issue for that repository?
