### ISSUE TITLE
Make it clearer that Ouroboros.Network.Chain is a test/mock module

### ISSUE THREAD

**Issue by Vtec234** [input-output-hk/ouroboros-network#771]
From what I understand, [`Ouroboros.Network.Chain`](https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-network/src/Ouroboros/Network/Chain.hs) is meant to be a test module/reference implementation without optimizations. To make this fact clearer, it could for example be called `MockChain`.

Functions from this module seem to then [be used](https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-consensus/src/Ouroboros/Consensus/Util/Chain.hs#L17) in `Ouroboros.Consensus.Util.Chain` - does that mean that it is also a mock module?

**Comment by mrBliss** [comment]
You are entirely correct. Here's a plan:
- [ ] Move the most used non-`Chain`-specific exports from `Chain`, i.e., `genesisPoint`, `genesisSlotNo`, .. (the sequel to #706 will impact the latter) to another place, e.g., `Ouroboros.Network.ChainFragment` (in that case, re-export them from `Ouroboros.Network.AnchoredFragment`), `Ouroboros.Network.Block`, or `Ouroboros.Network.Point`. After this, all remaining imports of `Ouroboros.Network.Chain` should import it to actually use the `Chain` type.
- [ ] Move `Ouroboros.Consensus.Util.Chain` to `test-consensus` (or `test-util`).
- [ ] Rename `Ouroboros.Network.Chain` to `Ouroboros.Network.MockChain`. Rename the type to `MockChain`?

I'm not sure about moving `Ouroboros.Network.Chain` to the testsuite, as it is nice to have conversion functions from/to `ChainFragment` and `AnchoredFragment` (they could be moved to the `Chain` module?), and the [model implementation](https://github.com/input-output-hk/ouroboros-network/blob/1c291da70decc003b474b192e335e86e80c252b3/ouroboros-consensus/src/Ouroboros/Consensus/Protocol/Abstract.hs#L231) of chain selection uses `Chain`s.

**Comment by mrBliss** [comment]
Fixed by #809
