### ISSUE TITLE
Fix bracketSyncWithFetchClient Test Case

### ISSUE THREAD

**Issue by karknu** [input-output-hk/ouroboros-network#781]
Implement `bracketSyncWithFetchClient` with TVar/TMVar instead of timeouts for synchronization so that it can be enabled again.

**Comment by coot** [comment]
@karknu `bracketSyncWithFetchClient` is already implemmet with a `TVar`, which tests case did had in mind?

**Comment by karknu** [comment]
I'm talking about the `_unit_bracketSyncWithFetchClient` test case.
It is still implemented using timeouts and it is still disabled, see https://github.com/input-output-hk/ouroboros-network/blob/5de5ec77d505e17e49fcb2fd22b36c826cba13cb/ouroboros-network/test/Test/Ouroboros/Network/BlockFetch.hs#L490

**Comment by karknu** [comment]
Fixed by #4559 .
