### ISSUE TITLE
Parameterise protocolInfoByron so that it can work for a real node

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#789]
See https://github.com/input-output-hk/ouroboros-network/blob/3d9fbb319fb3ed73d9d0444dd6877f50c7130a93/ouroboros-consensus/src/Ouroboros/Consensus/Node/ProtocolInfo/Byron.hs#L43

Related: https://github.com/input-output-hk/cardano-node/pull/60

**Comment by deepfire** [comment]
https://github.com/input-output-hk/ouroboros-network/pull/794/files#diff-3d865d85b325870a0a147510240e27c6R82 is the agreed-upon approach.

**Comment by mrBliss** [comment]
Progress has been made in #795.

**Comment by mrBliss** [comment]
More progress in #794, #857, #838, and #824.
