### ISSUE TITLE
Move block invariants into `HasHeader` class.

### ISSUE THREAD

**Issue by nc6** [input-output-hk/ouroboros-network#792]
We already have a `blockInvariant` method in the `HasHeader` class. However, we also use further invariants defined in places such as `validExtension`.

Many of these invariants may depend on the block type, so move them to `blockInvariant`

**Comment by mrBliss** [comment]
One potential issue is that `validExtension` is given both the chain(fragment), i.e. the previous block, and the block, whereas `blockInvariant` is only given the block itself.

**Comment by nc6** [comment]
I've just taken a look at this ticket, and I think it no longer makes sense (or, if it does, I've forgotten exactly what I was referring to when I filed it). So closing it.

**Comment by mrBliss** [comment]
Yeah, I think `HeaderValidation` covers it now.
