### ISSUE TITLE
Implement protocol combinator for hard forks

### ISSUE THREAD

**Issue by ruhatch** [input-output-hk/ouroboros-network#806]
We want to be able to combine two protocol, for example, pbft and praos, into a single protocol, where the first hard forks to the other. We should be able to do this in a generic way using a protocol combinator, which calls into the two protocols' definitions.

Setting up the general infrastructure is fairly simple, but the complexity lies in dealing with interaction between the hard fork, chain selection, and rollback. Functions from `OuroborosTag` such as `preferCandidate` have non-trivial semantics, and may even depend on the exact hard fork in some way. We should examine each of these tricky scenarios in turn to arrive at a principled mechanism for switching protocols.

**Comment by edsko** [comment]
Obsoleted by #946.
