### ISSUE TITLE
Add `mapConcurrently` to `MonadAsync`.

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#825]
Add `mapConcurrently` and friends (e.g. `forConcurently`, `replicateConcurently` etc) to `MonadAsync`.  `Async` module implements them by means of `Concurently` newtype wrapper.  It might be best to add `Concurently m` (as associated type family) to the `MonadAsync` type class and instantiate the original for `MonadAsync IO` instance.

**Comment by mgajda** [comment]
I will take a look at it next week.
