### ISSUE TITLE
Immutable DB: better recovery of index files

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#865]
During validation of the on-disk files stored by the ImmutableDB, each epoch file is parsed and verified against the offsets in the corresponding index file. When the index file is missing or corrupt, we can only be sure that the epoch file is complete when the last slot of the epoch is filled with a block, otherwise it is possible that the last block(s) might not have been written to disk or might have been truncated somehow. If we ignore this possibility, we could end up restarting with a chain that contains a gap.

This is unfortunate, as it would be very useful to be able to throw away all index files and reconstruct them (e.g., in #756). Duncan suggested checking the back pointer of the first block of the next epoch, but the ImmutableDB doesn't know about blocks (with `blockPrevHash` and `blockHash`), only about binary blobs. However, the `EpochFileParser` might be able to return us the hash of the first block.

**Comment by mrBliss** [comment]
I have played around with this. I was blocked by the lack of a correct `blockPrevHash` implementation for the test blocks.

We want simple test blocks that we can generate without (much) state. For example, we use the block itself as its hash or use a path through the chain as a hash. We derive the slot and block number from each other or from the hash.

Unfortunately, this prevents us from implementing `blockPrevHash`, as the hash of the block would need to include the hash of the previous block, which includes the hash of the block before it, and so on. Deriving the `blockPrevHash` deterministically is not really an option, because we wouldn't be able to skip slots or EBBs.

I think we should bite the bullet and implement more complex test blocks that resemble real blocks more, and support all desired features (EBBs!). They will need a real hash, but a simple and quick one.

See #872 and #966.

**Comment by edsko** [comment]
Further enhancements will be part of https://github.com/input-output-hk/ouroboros-network/issues/1253 .

**Comment by mrBliss** [comment]
Done in #1244.
