### ISSUE TITLE
rewindChainState in PBFT returns the whole chain

### ISSUE THREAD

**Issue by Vtec234** [input-output-hk/ouroboros-network#876]
The function `rewindChainState` is [described as](https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-consensus/src/Ouroboros/Consensus/Protocol/Abstract.hs#L172) "should attempt to rewind the chain state to the state at some given slot, or Origin to rewind to the state with no blocks.". The [implementation for PBFT](https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-consensus/src/Ouroboros/Consensus/Protocol/PBFT.hs#L235) checks whether a rewound prefix exists using `Seq.takeWhileL`, but then, if the prefix does exist, it returns the whole chain again - `Just cs` - rather than the prefix. It is unclear why it should not return the prefix instead.

**Comment by mrBliss** [comment]
@Vtec234 hint: use permalinks (which include the commit hash in the URL) when referring to code, because your second link is no longer up to date.

**Comment by mrBliss** [comment]
Addressed as part of #893
