### ISSUE TITLE
PBFT.hs#L205 could always be returning Nothing

### ISSUE THREAD

**Issue by ishaq** [input-output-hk/ouroboros-network#881]
the code in question: https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-consensus/src/Ouroboros/Consensus/Protocol/PBFT.hs#L205

spec of  `Seq.lookup` says `i < 0 || i >= length xs ==> lookup i xs = Nothing` therefore, `Seq.lookup` will always return `Nothing`.

Or did we misunderstand something?

_PS: can someone please add `audit` adn `consensus` labels, I don't seem to have permission._

**Comment by nc6** [comment]
Good catch, should be addressed with #893
