### ISSUE TITLE
Move CDDL tests to cardano-ledger

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#908]
The aim is to validate epoch files in immutable db.

**Comment by MarcFontaine** [comment]
I was able to download the EBBs from the immutable DB.
I manually validated the EBBs against to the CDDL spec (up to some depth, but not totally).
The EBBs and the CDDL spec looks good but the `cddl`-tool fails to load the CBOR diag representation with a `(JSON::ParserError)`

**Comment by MarcFontaine** [comment]
The CDDL tests for the EBBs work now.
The tests run as an standalone tool that can be run with the Chain DB and the cddl-spec as input.
The PR was merged in the cardano-byron-proxy repo.
https://github.com/input-output-hk/cardano-byron-proxy/pull/18
