### ISSUE TITLE
Resolve semantic conflict between `WithEBBs` and CS intersections at EBBs

### ISSUE THREAD

**Issue by nfrisby** [input-output-hk/ouroboros-network#925]
The `WithEBB` protocol combinator's `applyChainState` method forwards regular blocks to the underlying protocol but suppresses EBBs. (See #704.)

https://github.com/input-output-hk/ouroboros-network/blob/4ae0997add0305102810a54097e684753782d4f7/ouroboros-consensus/src/Ouroboros/Consensus/Protocol/WithEBBs.hs#L55-L60

However, a chain sync client may receive `MsgIntersectFound` with an EBB intersection point. This can lead the corresponding `rewindChainState` to fail, cascading to an exception such as a chain sync client's `InvalidIntersection`. I'm specifically seeing this failure in the `RealPBFT` test when the chain is just one EBB and the `MsgIntersectFound` identifies that EBB. This arises on my #773 branch that lets some nodes join later than others.

That is a very specific and seemingly unrealistic corner case, but it highlights the more general conflict between `WithEBB`'s suppression of EBBs and the general semantics of `applyChainState`/`rewindChainState`: Can `rewindChainState` assume that the target point corresponds to a prior call to `applyChainState`? Currently `applyChainState @WithEBB` violates that assumption.

`PBFT` currently makes a similar assumption. Its `rewindChainState` refuses to rewind past the earliest block in its chain state for a non-`Origin` request. Hence the `RealPBFT` failure, since the requested EBB intersection point is the first (and only) block in the chain but never made it into the chain state.

https://github.com/input-output-hk/ouroboros-network/blob/4ae0997add0305102810a54097e684753782d4f7/ouroboros-consensus/src/Ouroboros/Consensus/Protocol/PBFT.hs#L232-L236

So: Should `WithEBB` stop suppressing EBBs or should `rewindChainState` methods make fewer assumptions? Or something else?

cc: @nc6 @edsko @mrBliss

**Comment by nfrisby** [comment]
My current repro is unfortunately tangled up with #773 details, and I'm unfamiliar with the ledger details etc involved in setting up a standalone repro forked off `master`.

FYI, simplifying `PBFT`'s `rewindChainState` to permit returning the empty sequence in the `At` alternative avoids the exception -- I'm doing that locally for now, but it seems presumptuous to assume that's The Right Fix.

**Comment by mrBliss** [comment]
@nfrisby Another nice find! 

@nc6: is there a reason for ignoring EBBs in `rewindChainState`?

**Comment by nc6** [comment]
I think the correct solution here is to wrap `rewindChainState` such that, if asked to rewind to an EBB, we rewind to the previous slot. This may possibly be `Origin`. This corresponds with EBBs not affecting the chain state.

**Comment by nfrisby** [comment]
> I think the correct solution here is to wrap `rewindChainState` such that, if asked to rewind to an EBB, we rewind to the previous slot.

I'm wondering about the case where the `EBB` itself is the oldest block that `rewindChainState` could rewind to? That is, when the EBB's predecessor is just out of reach? Maybe `rewindChainState` is too late to be the function that "skips over EBBs"? In my repro above, for example, `rewindChainState` is invoked with an EBB because that was the intersection point. So maybe the function that finds intersection points (and other functions upstream of `rewindChainState`?) should be the ones to skip over EBBs? Just thinking aloud.

**Comment by nc6** [comment]
I think it should be perfectly reasonable for the network layer to treat EBBs much as regular blocks - they add to the hash chain. The WithEBB combinator encapsulates the knowledge that EBBs don't actually modify the chain state, and so it's reasonable to ignore them in both advancing and rewinding the state.

**Comment by nfrisby** [comment]
I consider Issues #966 and #967 to block this Issue.

The merged PR 951 resolved this issue to the extent that the current test suite passes, even on the pending PR 773 on which some nodes can join the network in later slots during the test.

However, merging PR 951 only addressed the exact failure we were seeing. That's a specific case in `RealPBFT`, which only forges exactly one EBB at slot 0, disregarding its specified epoch size. I think the tests would pass even if they were to forge additional EBBs, but that might only be because the `RealPBFT` protocol uses `PBft`, whose `rewindChainState` only fails when it's rewinding to an empty `ChainState` (ie "essentially Origin"). Would a more demanding `rewindChainState` (e.g. Praos's?) still fail even with PR 951 merged if we were to rewind it to the EBB of some epoch other than the first? I think Issues #966 and #967 should involve answering that.

**Comment by nfrisby** [comment]
Executive Summary: We want to unmerge PR #951 and replace it with a refinement of the ChainSync server: never intersect/rollback to an EBB, keep searching further backward instead. Such a PR will fully resolve this Issue.

While reviewing Edsko's PR #978, I noticed that the previous special case of `rewindChainState @PBft` for rewinding to `Origin` was being eliminated, which cast doubt on PR #951 since it hinged on that case specifically. Edsko and I had a call about it and agreed we should unmerge PR #951.

So instead of adding a component to the `WithEBBs` `ChainState` (as PR #951 did), we will instead change the ChainSync server to never choose EBBs for intersections/rollbacks. Roughly: when searching backwards for an intersection, it should "skip over" EBBs. Note that such skipping may cause the mini protocol to now send `MsgIntersectNotFound` where it formerly sent `MsgIntersectFound` at an EBB. This happens when that EBB was exactly within `k` EBB-or-proper-blocks. This change is actually reasonable since there is in fact no "proper" block within `k` EBB-or-proper-blocks.

I think Edsko and/or Clarke can elaborate on why this constraint is appropriate for the wire protocol etc. Something along the lines of: once The Hard Fork is older than `k` blocks, no EBBs will be within `k`, so ChainSync at that point might not need to consider them at all. We won't miss the tiresome distinction been EBB, non-EBB, and "either/both".

Related: The Issues 966 and 967 discuss adding mock EBB cases to the test framework, so we can test EBBs without the heavy footprint of also testing Byron blocks. They seems particularly relevant to this kind of change to the ChainSync client.

cc: @edsko @nc6

**Comment by edsko** [comment]
@nfrisby , after https://github.com/input-output-hk/ouroboros-network/pull/1189 has been merged, `WithEBBs`, and with it its special bookkeeping, is entirely gone. However, @mrBliss and I have reconsidered the problem in this particular ticket, and I think the somewhat hacky bookkeeping in `WIthEBBs` was only necessary due to the somewhat hacky nature of the original PBFT chain state. With the chain state entirely rewritten a while ago, I believe that there is no problem here anymore, it should handle EBBs just fine with no extra help. I think this ticket can be closed, but it would be good if you could confirm :)

**Comment by nfrisby** [comment]
I'll revisit this @edsko. IIRC PR 978 might even have sufficed -- but it's not obviously clear to me, so I'll dig in.

(Also, bors just merged PR 1189 into master).

**Comment by edsko** [comment]
Yes, I suspect that #978 did suffice, but at that point the special bookkeeping in `WithEBBs` was still present. It is now gone.

**Comment by nfrisby** [comment]
Currently, there is no apparent bug involving EBBs. Here is why. As of PR 978:

  * `applyChainState` ignores EBBs blocks; the chain state is entirely unchanged.
  * For non-EBBs it inserts the block and also immediately prunes the oldest parts so that the resulting payload corresponds to only the most recent `k` insertions.
  * In addition to truncating the payload, pruning also records the slot of the latest block that was pruned away. This part of the chain state is initialized to and remains `Origin` until a block is pruned away.
  * `rewindChainState` only fails if the requested slot precedes the slot of the most recently pruned block.

As a result, `rewindChainState` is always able to rewind past up to `k` non-EBBs. While doing so, it can also rewind past any number of EBBs. This was not the case before PR 978 (see this ticket's description).

-----

The only work I would suggest for this ticket is to record something like the above discussion about EBBs in the code comments.

Relatedly, I'm unclear what this comment on the PBFT implementation of `rewindChainState` is supposed to convey.

https://github.com/input-output-hk/ouroboros-network/blob/cd65d46cb427d786b59f67a4547d6b2484f00171/ouroboros-consensus/src/Ouroboros/Consensus/Protocol/PBFT/ChainState.hs#L224-L226

Why can't we rewind to slots between blocks? Depending on what exactly "applied" and "block" mean here (`ChainState.insert` and "non-EBB"? `applyChainState` and "EBB or non-EBB"? etc), this seems like exactly what we're doing when we rewind to an EBB.

-----

The `test-consensus` suite exercises this ticket. Here are the relevant facts.

  * Our test nodes only ever forge the EBB for epoch 0.
      * Considering chains with only one early EBB makes sense, because no EBBs will be forged after the Hard Fork.
      * However, we might want to try testing with chains that have blocks prior to the sole EBB too.
  * Our test nodes use `k = 10`.
  * Our only test with EBBs is (and, as of PR 1189, must be) the PBFT protocol.
  * `rewindChainState` is only called by the ChainSync client, when it is handling `MsgFoundIntersect` and `MsgRollBackward`.
  * The PBFT signing threshold (`1/N + ϵ`) and hardwired round-robin leader schedule makes it difficult to manually fabricate repros for some of the interesting cases. For example, the case with the EBB as the last point in the `MsgFindIntersect` message -- I intervened (essentially disabled the signing threshold) and created and validated one by hand and that case was handled smoothly. I'm not currently thinking of any more extreme cases than that one. I'm not certain the test suite is exercising all such interesting cases, but I think it will once network outages are enabled (what I'm currently working on).

-----

When revisiting this Issue today, I at first conflated it with another. The key ingredient is that `blockPoint ebb` is the first slot of the epoch, even though that EBB might have been forged by a node leading a later slot. I don't think that's relevant here (see #998 for more).

**Comment by nfrisby** [comment]
Summary of resolution:

  * PR 1189 - `WithEBBs` was fused into `PBft`.
  * PR 1317 - We begrudgingly added a component to the `PBft` chain state that tracks EBBs so that it is able to rewind to slots that contain only an EBB and no proper block.

So ChainSync still sometimes chooses EBBs as an intersection -- if the EBB is the only block in the slot, then those two PRs suffice. If it's accompanied by non-EBB in the same slot, then ChainSync's `rewindChainState` call fails. Issue 1352 tracks that.
