### ISSUE TITLE
Node fails to start on a system without IPv6 configured -- fallback needed?

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/ouroboros-network#926]
Here's what one gets when the system isn't configured with IPv6, but IPv6 is requested in node configuration (as per `scripts/shelley-testnet2.sh`/topology in recent `cardano-node` `master`):

```
cardano-node: ExceptionInForkedThread Network.Socket.bind: unsupported operation (Cannot assign requested address)
```

..which seems to basically come from:
https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-network/src/Ouroboros/Network/Socket.hs#L283

While we might want to ship with IPv6 defaults, we'd want some kind of transparent fallback for those people who don't have it enabled.

**Comment by avieth** [comment]
If a user requests that `cardano-node` use IPv6, but UPv6 is not supported by their system, what else can we do? IMO it would be wrong to disobey orders and use IPv4.

**Comment by dcoutts** [comment]
We could improve the reporting of the exception, but I agree that this is really a configuration error.

Our default config will be to use either IPv6 or IPv4, so would not have this problem, right @karknu?

**Comment by karknu** [comment]
That is true, we should use either IPv4 or IPv6 and if one is broken we will fall back to the other.
If a user has manually only configured IPv6 peers as in Alex's scenario we would not fall back to IPv4.
