### ISSUE TITLE
Avoid deserialising blocks when copying from VolDB to ImmDB

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#944]
In the ChainDB, we copy blocks older than `k` from the VolatileDB to the ImmutableDB in the background. Currently, we're deserialising the blocks even though we could also simply copy the bytes without (de)serialising. An argument for this is that it's a final check that the blocks we're adding to the ImmutableDB are correct. When a node is up-to-date, this is no bottleneck, as it only happens once every 20s. But when catching up, this will slow us down.

Duncan:
> Perhaps ideally what we should do is to sync without this check, and then when we're more or less up to date, do a background scan of all the recent epochs. So that's done async later.
I think for now, it'd be better to not do the extra checks in the hot path. We can make a ticket for the extra checking.
Indeed even when we're in sync, probably the best time to check a completed epoch file is several hours (or even days) after it has been written. That's when it's been written out and no longer in the page cache

Issue:  the ImmutableDB needs to know whether a block is an EBB or not, and to know this, we currently need to deserialise it. If we are able to only deserialise the header (while leaving the body serialised), we can still apply this optimisation.

**Comment by mrBliss** [comment]
Related: #501

**Comment by edsko** [comment]
Let's do this as part of #1178 .

**Comment by mrBliss** [comment]
This is mainly important for improving the sync speed.

**Comment by mrBliss** [comment]
This conflicts with the validity checks we describe in #1304.

Note that this validation will not be done in the hot path (of chain sync), as it already happens in a background thread.
