### ISSUE TITLE
Finish HardForksTo combinator

### ISSUE THREAD

**Issue by ruhatch** [input-output-hk/ouroboros-network#946]
There were a few pieces left out of the first PR of the `HardForksTo`:

- Decoding values from both sides of the fork (right now we just do after)
- `anachronisticProtocolLedgerView` (right now just do after)
- Doing a proper implementation of the chain selection functions (@edsko though this could be made generic)
- Moving the specific hard fork instances for the simple hard fork to their own file
- Figuring out what to do with the protocol security param
- Figuring out when to delete the snapshot from the chain state
- Getting the dynamic tests passing before and after fork, requires other things

**Comment by mrBliss** [comment]
>     * Decoding values from both sides of the fork (right now we just do after)
I heard you'll need cborg support to do this efficiently.
However, doing this for mock blocks should be simple, as we have complete control of the format, so something like:
```haskell
encodeForked :: forall before after. 
                (SerialiseTag before, SerialiseTag after)
             => (       before       -> CBOR.Encoding)
             -> (              after -> CBOR.Encoding)
             -> (Forked before after -> CBOR.Encoding)
encodeForked encodeBefore encodeAfter = (CBOR.encodeListLen 2 <>) . forked
 -> (\before -> encode (serialiseTag @before) <> encodeBefore before)
    (\after  -> encode (serialiseTag @after)  <> encodeAfter after)

decodeForked :: forall before after s.
                (SerialiseTag before, SerialiseTag after)
             => CBOR.Decoder s         before
             -> CBOR.Decoder s                after
             -> CBOR.Decoder s (Forked before after)
decodeForked decodeBefore decodeAfter = do
    CBOR.decodeListLenOf 2
    decode >>= \(tag :: Word8) -> if 
      | tag == serialiseTag @before
      -> BeforeFork <$> decodeBefore
      | tag == serialiseTag @after
      -> AfterFork  <$> decodeAfter
      | otherwise
      -> fail $ "decode: invalid tag: " <> show tag                            

decodeForked' :: forall before after s.
                (SerialiseTag before, SerialiseTag after)
             => CBOR.Decoder s (Lazy.ByteString ->        before)
             -> CBOR.Decoder s (Lazy.ByteString ->               after)
             -> CBOR.Decoder s (Lazy.ByteString -> Forked before after)
decodeForked' decodeBefore decodeAfter = do
    CBOR.decodeListLenOf 2
    decode >>= \(tag :: Word8) -> if
      | tag == serialiseTag @before
      -> (BeforeFork .) <$> decodeBefore
      | tag == serialiseTag @after
      -> (AfterFork .)  <$> decodeAfter
      | otherwise
      -> fail $ "decode: invalid tag: " <> show tag
```
This will allow you to test with forks that happen later than at `SlotNo 0`

**Comment by edsko** [comment]
I've done a lot of work on the hard fork combinator, but it's still WIP. The list above in the ticket is not up to date.

**Comment by edsko** [comment]
Draft PR implementing a lot, but not all, of Ru's work is available at https://github.com/input-output-hk/ouroboros-network/pull/1175 , which depends on https://github.com/input-output-hk/ouroboros-network/pull/1227 to be done first.

**Comment by edsko** [comment]
Blocked on:

* https://github.com/input-output-hk/ouroboros-network/issues/1637
* https://github.com/input-output-hk/ouroboros-network/issues/1205 (especially https://github.com/input-output-hk/ouroboros-network/issues/1205#issuecomment-585650574)

**Comment by edsko** [comment]
Obsoleted by #2034.
