### ISSUE TITLE
Protocol testing: WithEBBs

### ISSUE THREAD

**Issue by nfrisby** [input-output-hk/ouroboros-network#967]
Once Issue #966 introduces the infrastructure, we should in particular test the `WithEBBs` protocol combinator's interesting methods, especially `applyChainState` and `rewindChainState`. There should be a separate test suite specific to that, in addition to the more integration-level test running the protocol on something like `WithEBBs TestBlock` (whatever #966 enables).

This Issue partly represents the obligation to write a more specific test for PR #951 (Issue #925).

cc: @mrBliss

**Comment by mrBliss** [comment]
`WithEBBs` will be gone in #1196. #966 already focuses on EBBs.
