### ISSUE TITLE
Do not overcount inflight BlockFetch requests

### ISSUE THREAD

**Issue by nfrisby** [input-output-hk/ouroboros-network#973]
While working on PR #829 Issue #228 (which I began developing atop PR #773 for Issue #231), a late joining node in one of the non-mesh topologies revealed that BlockFetch sometimes overcounts the number of in-flight requests. This may unnecessarily prevent block fetches since the node incorrectly believes it would be exceeding its concurrent inflight request thresholds. That in turn can prevent reaching consensus, at least not promptly and perhaps even not ever.

The cause is a hot-path optimization that merges some chain fragments when they're added to the queue that accumulates the next fetch request.

https://github.com/input-output-hk/ouroboros-network/blob/4d0ccd8061f7b2e0c53d782595da1bcd32dd9a41/ouroboros-network/src/Ouroboros/Network/BlockFetch/ClientState.hs#L247-L250

The inflight requests counter is incremented for each unmerged request (apple) going into the queue

https://github.com/input-output-hk/ouroboros-network/blob/4d0ccd8061f7b2e0c53d782595da1bcd32dd9a41/ouroboros-network/src/Ouroboros/Network/BlockFetch/ClientState.hs#L211-L212

whereas the same counter is decremented for each possibly-merged request (orange) that came out of the queue, was sent to the peer, and was fully replied to by the peer

https://github.com/input-output-hk/ouroboros-network/blob/4d0ccd8061f7b2e0c53d782595da1bcd32dd9a41/ouroboros-network/src/Ouroboros/Network/BlockFetch/ClientState.hs#L405

but fewer (oranges) may come out than (apples) went in, if some requests were merged while in the queue. Thus the counter might never reach 0 again even when no requests remain in-flight.

**Comment by coot** [comment]
Thanks @nfrisby I will take a look at this.
