### ISSUE TITLE
Introduce strict variant of `FingerTree`

### ISSUE THREAD

**Issue by intricate** [input-output-hk/ouroboros-network#975]
We should introduce a strict variant of `FingerTree` such that we can ensure its elements are in WHNF.

@edsko: 
> folks, I started adding some isNormalForm assertions to the chain DB, but many of them fail. some of those failures might be genuine bugs, but... ChainFragment uses FingerTree, which is not strict. There are some packages with a strict variant, but the paper (http://www.staff.city.ac.uk/~ross/papers/FingerTree.pdf) says that "the structure makes essential use of laziness, though it is also suitable for strict languages that provide a lazy evaluation primitive", so I worry about using a strict variant -- it may affect asymptotic complexity in non-trivial ways.

@dcoutts:
> Right we want it to be strict in its leaves/elements/content
> yeah it'd mess up the asymptotic complexity

@edsko:
> right, that's what I was was worried about. @intricate, perhaps we should put FingerTree behind a module of our own (FingerTree.Strict) that does ensure that the elements are always in WHNF.

**Comment by edsko** [comment]
Related: #380.
