### ISSUE TITLE
Add "pre-anchor signers" to PBftChainState

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#979]
In the rewrite of the `PBftChainState`, https://github.com/input-output-hk/ouroboros-network/pull/978 , I missed one subtlety. Suppose that the chain looks like

```
[b1, b2, b3, b4, b5, b6, b7, b8, b9, b10]
```

that we have a window size of 5,  and this satisfies the window check, but _only_ if `b6` is not signed by key `GS1`; i.e., if `B6` would have been signed by `GS1`, the window `[b2, b3, b4, b5, b6]` would fail the check.

If we now roll back to `b4`, ending up with a window of `[]`, if block `b5'` _would_ be signed by `GS1`, we'd end up with a window `[b5']`, which would not fail the window check (indeed, we would not run a window check at all until the window fills up again). 

This is a potential security risk, and so we should address this. The easiest way to address is to add a list of "pre anchor signers". Most of the logic would remain the same, but when we rewind, the window (in terms of `signers` and `counts`) does not shrink.

**Comment by edsko** [comment]
Moving this to 1.1 because this only really becomes a concern when the core nodes in the system start becoming responsible for the blockchain.

**Comment by edsko** [comment]
This has an easy solution: given window size of `n`, and maximum roll back `k`, we just need to make sure that we keep `n+k` slots in the history; when we evaluate a block, we use the last `n` slots from the history; rollback can still be implemented as throwing away a suffix as normal, but since the history is now a bit longer, we wil still end up with a window of `n` slots.

**Comment by mrBliss** [comment]
Addressed in #1307.
