### ISSUE TITLE
Double check codecs and the test code for codecs

### ISSUE THREAD

**Issue by MarcFontaine** [input-output-hk/ouroboros-network#985]
There was a bug in a codec that caused the generation of invalid cbor.
(a manually provided list length was inconsistent.)
See:
https://github.com/input-output-hk/ouroboros-network/pull/549/commits/64d1f6b15e4077b487cb7bc33bec04a6c9f6d8e5
TODO:
Double check for similar bugs and make sure that
the test suites catch this class of bugs.

**Comment by coot** [comment]
That's related to #984. I'd expect when solving #984 this issues will get resolved as well.
