### ISSUE TITLE
Address comment in `Ouroboros.Consensus.Ledger.Byron.Forge` claiming that "this is a demo"

### ISSUE THREAD

**Issue by intricate** [input-output-hk/ouroboros-network#988]
From @dcoutts:

> Is the module Ouroboros.Consensus.Ledger.Byron.Forge for production or testing/demo? There's a comment in there:
> https://github.com/input-output-hk/ouroboros-network/blob/fe93af9e1a76ede191c98e458aaec83290607357/ouroboros-consensus/src/Ouroboros/Consensus/Ledger/Byron/Forge.hs#L72-L73
> We should clarify this, perhaps simply by correcting the comment.

**Comment by mrBliss** [comment]
Will be gone in #1196.
