### ISSUE TITLE
Unused function Ouroboros.Consensus.Ledger.Byron.toCBORAHeaderOrBoundary

### ISSUE THREAD

**Issue by Vtec234** [input-output-hk/ouroboros-network#995]
In Ouroboros.Consensus.Ledger.Byron, the function [`toCBORAHeaderOrBoundary`](https://github.com/input-output-hk/ouroboros-network/blob/6c937ec0d65d5df5f44ce9f496ebcfcd07762f56/ouroboros-consensus/src/Ouroboros/Consensus/Ledger/Byron.hs#L794) is defined, but never used internally. It's also exported from the module, but a GitHub search indicates that it's not used anywhere. The complementary decoding function `fromCBORAHeaderOrBoundary` *is* used within the module, in [`decodeByronHeader`](https://github.com/input-output-hk/ouroboros-network/blob/6c937ec0d65d5df5f44ce9f496ebcfcd07762f56/ouroboros-consensus/src/Ouroboros/Consensus/Ledger/Byron.hs#L670).

**Comment by mrBliss** [comment]
The function was removed in https://github.com/input-output-hk/ouroboros-network/commit/867d616e75f1f20a4d289f120270f73d075c9866.
